### ISSUE TITLE
XA cache logs Exception raised while running eviction advisor: NullPointerException

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#1027]
This happens when running `XACacheTest`, full stack trace:

```
[tx2] ERROR org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore - Exception raised while running eviction advisor - Eviction will assume entry is NOT advised against eviction
java.lang.NullPointerException
	at org.ehcache.transactions.xa.internal.XAStore$XAEvictionAdvisor.adviseAgainstEviction(XAStore.java:987)
	at org.ehcache.transactions.xa.internal.XAStore$XAEvictionAdvisor.adviseAgainstEviction(XAStore.java:977)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore$OffHeapEvictionAdvisorWrapper.adviseAgainstEviction(AbstractOffHeapStore.java:1310)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore$OffHeapEvictionAdvisorWrapper.adviseAgainstEviction(AbstractOffHeapStore.java:1299)
	at org.ehcache.impl.internal.store.offheap.EhcacheConcurrentOffHeapClockCache$1.apply(EhcacheConcurrentOffHeapClockCache.java:163)
	at org.ehcache.impl.internal.store.offheap.EhcacheConcurrentOffHeapClockCache$1.apply(EhcacheConcurrentOffHeapClockCache.java:152)
	at org.terracotta.offheapstore.OffHeapHashMap.computeWithMetadata(OffHeapHashMap.java:1914)
	at org.terracotta.offheapstore.AbstractLockedOffHeapHashMap.computeWithMetadata(AbstractLockedOffHeapHashMap.java:581)
	at org.terracotta.offheapstore.concurrent.AbstractConcurrentOffHeapMap.computeWithMetadata(AbstractConcurrentOffHeapMap.java:728)
	at org.ehcache.impl.internal.store.offheap.EhcacheConcurrentOffHeapClockCache.compute(EhcacheConcurrentOffHeapClockCache.java:152)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.replace(AbstractOffHeapStore.java:560)
	at org.ehcache.impl.internal.store.tiering.TieredStore.replace(TieredStore.java:199)
	at org.ehcache.transactions.xa.internal.XATransactionContext.replaceInUnderlyingStore(XATransactionContext.java:289)
	at org.ehcache.transactions.xa.internal.XATransactionContext.commit(XATransactionContext.java:199)
	at org.ehcache.transactions.xa.internal.EhcacheXAResource.commit(EhcacheXAResource.java:79)
	at bitronix.tm.twopc.Committer$CommitJob.commitResource(Committer.java:202)
	at bitronix.tm.twopc.Committer$CommitJob.execute(Committer.java:191)
	at bitronix.tm.twopc.executor.Job.run(Job.java:72)
	at bitronix.tm.twopc.executor.SyncExecutor.submit(SyncExecutor.java:31)
	at bitronix.tm.twopc.AbstractPhaseEngine.runJobsForPosition(AbstractPhaseEngine.java:121)
	at bitronix.tm.twopc.AbstractPhaseEngine.executePhase(AbstractPhaseEngine.java:85)
	at bitronix.tm.twopc.Committer.commit(Committer.java:86)
	at bitronix.tm.BitronixTransaction.commit(BitronixTransaction.java:289)
	at bitronix.tm.BitronixTransactionManager.commit(BitronixTransactionManager.java:143)
	at org.ehcache.integration.transactions.xa.XACacheTest$TxThread.run(XACacheTest.java:840)
```

**Comment by ljacomet** [comment]
Of course eviction advisor can be `null` - my bad when I added the support for it in XA
