### ISSUE TITLE
Puts to an offheap or disk cache with a loader/writer can misreport statistics.

### ISSUE THREAD

**Issue by chrisdennis** [ehcache/ehcache3#1056]
The atomic reference used to return the previous mapping by side affect from the function used in EhcacheWithLoaderWriters.put(...) method is incorrectly memoized.  This means the statistics reported for a call will be correct for the first function invocation, and not for the final 'correct' invocation in the case the store invokes the method multiple times.

**Comment by chrisdennis** [comment]
This might be fixed by Louis' long ago written "closable" event listener logic. Someone should revisit this code and make that assessment.

**Comment by jitendra-nalwaya** [comment]
Hi @chrisdennis ,

**Observations when configure heap+offheap with CacheLoaderWriter:**

**Note:** EhcacheWithLoaderWriter is removed by PR https://github.com/ehcache/ehcache3/pull/2501 in Oct 2018

1) Additions to statistics count depend on observer.
   a) The count increased when the observer's end() method was called.
   b) When OversizeMappingException throws in this scenario, the count is not increased.
      - In AbstractOffHeapStore, computeObserver's end() method is not called.
      - In EhcacheBase, putObserver's end() method called with PutOutcome.FAILURE status due to StoreAccessException.

2) The compute function is applied multiple times when an OversizeMappingException occurs during the put operation.

    try {
      computeResult = backingMap().compute(key, computeFunction, fault);  // [1]
    } catch (OversizeMappingException ex) {
      try {
        evictionAdvisor().setSwitchedOn(false);
        invokeValve();
        computeResult = backingMap().compute(key, computeFunction, fault); // [2]
      } catch (OversizeMappingException e) {
        throw new StoreAccessException("The element with key '" + key + "' is too large to be stored"
                                       + " in this offheap store.", e);
      } catch (RuntimeException e) {
        throw handleException(e);
      } finally {
        evictionAdvisor().setSwitchedOn(true);
      }
    } catch (RuntimeException re) {
      throw handleException(re);
    }
            
     a) OversizeMappingException triggered from org.terracotta.offheapstore.AbstractOffHeapClockCache (Offheap-store-2.5.3.jar).
     b) at [1] : Compute function is applied three times due to Offheap-store code flow.
     c) at [2] : Compute function is applied one time due to handleOversizeMappingException(key.hashCode()) method. 

OversizeMappingException stacktrace:

2023-06-13 17:50:00.754 [Time-limited test] INFO org.ehcache.impl.internal.resilience.RobustLoaderWriterResilienceStrategy - Ehcache key long01 recovered from
org.ehcache.spi.resilience.StoreAccessException: The element with key 'long01' is too large to be stored in this offheap store.
            at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.computeWithRetry(AbstractOffHeapStore.java:1047)
            at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.getAndCompute(AbstractOffHeapStore.java:575)
            at org.ehcache.impl.internal.store.tiering.TieredStore.getAndCompute(TieredStore.java:308)
            at org.ehcache.impl.internal.store.loaderwriter.LocalLoaderWriterStore.put(LocalLoaderWriterStore.java:98)
            at org.ehcache.core.Ehcache.doPut(Ehcache.java:94)
            at org.ehcache.core.EhcacheBase.put(EhcacheBase.java:188)
            at org.ehcache.clustered.management.LoaderWriterSingleThreadTest.testSimplePutGetExistsInStore(LoaderWriterSingleThreadTest.java:69)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
---
------
Caused by: org.terracotta.offheapstore.exceptions.OversizeMappingException: Storage Engine and Eviction Failed - Empty Map
--
-----
            at org.terracotta.offheapstore.AbstractOffHeapClockCache.storageEngineFailure(AbstractOffHeapClockCache.java:82)
            at org.terracotta.offheapstore.OffHeapHashMap.writeEntry(OffHeapHashMap.java:685)
            at org.terracotta.offheapstore.OffHeapHashMap.computeWithMetadata(OffHeapHashMap.java:1958)
            at org.terracotta.offheapstore.AbstractLockedOffHeapHashMap.computeWithMetadata(AbstractLockedOffHeapHashMap.java:520)
            at org.terracotta.offheapstore.concurrent.AbstractConcurrentOffHeapMap.computeWithMetadata(AbstractConcurrentOffHeapMap.java:739)
            at org.ehcache.impl.internal.store.offheap.EhcacheConcurrentOffHeapClockCache.compute(EhcacheConcurrentOffHeapClockCache.java:152)
            at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.computeWithRetry(AbstractOffHeapStore.java:1044)
            ... 21 more
