### ISSUE TITLE
Cannot create a standalone cache manager if the clustered jars are on the classpath

### ISSUE THREAD

**Issue by mathieucarbou** [ehcache/ehcache3#1098]
Code:

```
      CacheConfiguration<String, String> cacheConfiguration = CacheConfigurationBuilder.newCacheConfigurationBuilder(
          String.class,
          String.class, ResourcePoolsBuilder.newResourcePoolsBuilder()
          .heap(10, EntryUnit.ENTRIES)
          .offheap(1, MemoryUnit.MB)
          .build())
          .build()

      StatisticsProviderConfiguration statisticsProviderConfiguration = new EhcacheStatisticsProviderConfiguration(
          1, TimeUnit.MINUTES,
          100, 1, TimeUnit.SECONDS,
          30, TimeUnit.SECONDS)

      ManagementRegistry managementRegistry = new DefaultManagementRegistryService(new DefaultManagementRegistryConfiguration()
          .setCacheManagerAlias("my-cm-name")
          .addConfiguration(statisticsProviderConfiguration));

      CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
          .using(managementRegistry)
          .build(true);

      cacheManager.createCache("cache-1", cacheConfiguration);
      cacheManager.createCache("cache-2", cacheConfiguration);
```

Stack trace:

```
Caught: org.ehcache.StateTransitionException
org.ehcache.StateTransitionException
	at org.ehcache.core.StatusTransitioner$Transition.failed(StatusTransitioner.java:235)
	at org.ehcache.core.EhcacheManager.init(EhcacheManager.java:592)
	at org.ehcache.config.builders.CacheManagerBuilder.build(CacheManagerBuilder.java:72)
	at org.ehcache.config.builders.CacheManagerBuilder$build$1.call(Unknown Source)
	at client$_run_closure2.doCall(client.groovy:148)
	at client.run(client.groovy:101)
Caused by: java.lang.NullPointerException
	at org.ehcache.clustered.client.service.DefaultClusteringService.<init>(DefaultClusteringService.java:84)
	at org.ehcache.clustered.client.service.ClusteringServiceFactory.create(ClusteringServiceFactory.java:32)
	at org.ehcache.clustered.client.service.ClusteringServiceFactory.create(ClusteringServiceFactory.java:28)
	at org.ehcache.core.internal.service.ServiceLocator.discoverServices(ServiceLocator.java:96)
	at org.ehcache.core.internal.service.ServiceLocator.findServices(ServiceLocator.java:258)
	at org.ehcache.core.internal.service.ServiceLocator.loadDependenciesOf(ServiceLocator.java:380)
	at org.ehcache.core.internal.service.ServiceLocator.resolveMissingDependencies(ServiceLocator.java:330)
	at org.ehcache.core.internal.service.ServiceLocator.startAllServices(ServiceLocator.java:297)
	at org.ehcache.core.EhcacheManager.init(EhcacheManager.java:564)
	... 4 more
```

It seems to come from this `ServiceLocator` line that would load the clustered stuff whereas I do not want it to...

```
for (ServiceFactory<T> factory : ServiceLocator.<T> getServiceFactories(serviceFactory)) {
```

**Comment by mathieucarbou** [comment]
@anthonydahanne : FYI

**Comment by cljohnso** [comment]
I've reproduced the problem -- investigating now.

**Comment by cljohnso** [comment]
A maze of twisty little passages, all alike.

`EhcacheManager.ServiceDeps` declares a dependency on `Store.Provider`.  During dependency resolution in `ServiceLocator`, `ClusteredStore.Provider` is found in the class path to match `Store.Provider`.  `ClusteredStore.Provider` declares a dependency on `ClusteringService` for which the `ClusteringServiceFactory` is located (in `ServiceLocator.discoverServices`).  The factory `create` method is called and, since this is during dependency discovery instead of being driven by configuration, null is passed in for the configuration leading to a NullPointerException.

We can permit `ClusteringServiceFactory` to avoid instantiating `DefaultClusteringService` when it has no configuration and change `ServiceLocator` to just not add a `DefaultClusteringService` instance.  But this strikes me as being a _little_ unclean since `ClusteredStore.Provider` is already loaded.

Ideally, we want to unload (or even prevent loading of) `ClusteredStore.Provider` if we have no cluster configuration but this might be a little difficult to manage.

Solving this _properly_ is going to need some discussion.

**Comment by cljohnso** [comment]
Another alternative is to have `ClusteringServiceFactory` provide a _null_ configuration or some kind -- the dependencies remain "happy" without having to wreck `ServiceLocator`.

**Comment by mathieucarbou** [comment]
Could we have the same issue if for example the service locator tries to load an external service developed by a client because it is on the class path,  but it actually shouldn't  load it ? I mean... could the service locator decide to load from the CP something it shouldn't?

**Comment by ljacomet** [comment]
Have a look at #798, this problem has been resolved for XA store already and we just need to apply the same recipe there.

Since `Store.Provider` are loaded eagerly because of ranking, they cannot fail to load and cannot declare dependencies on services that have mandatory configuration.

**Comment by mathieucarbou** [comment]
Thanks 👍
