### ISSUE TITLE
CacheManager.close() indefinitely waits when closing

### ISSUE THREAD

**Issue by mathieucarbou** [ehcache/ehcache3#1108]
In our system tests, if at the end we shutdown the server before the cache manager, the the application blocks because the CM cannot be closed.

Groovy code to reproduce:

```
package com.terracottatech.issues

import org.ehcache.PersistentCacheManager
import org.ehcache.clustered.client.config.builders.ClusteringServiceConfigurationBuilder
import org.ehcache.config.builders.CacheManagerBuilder

CacheManagerBuilder<PersistentCacheManager> clusteredCacheManagerBuilder = CacheManagerBuilder.newCacheManagerBuilder()
    .with(ClusteringServiceConfigurationBuilder.cluster(URI.create('terracotta://localhost:9510').resolve("/MyCacheManagerName?auto-create"))
    .defaultServerResource("primary-server-resource"))
cacheManager = clusteredCacheManagerBuilder.build(false)
cacheManager.init()
println "Press a key to close..."
System.in.read()
cacheManager.close()
```

1. Start the server
2. Run the code
3. Stop te server
4. Press a key to continue to `cacheManager.close()`

It blocks.

Stack trace:

```
"main@1" prio=5 tid=0x1 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:502)
	  at com.tc.object.InFlightMessage.get(InFlightMessage.java:141)
	  at com.tc.object.InFlightMessage.get(InFlightMessage.java:42)
	  at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl$1.get(EntityClientEndpointImpl.java:164)
	  at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl$1.get(EntityClientEndpointImpl.java:155)
	  at org.terracotta.voltron.proxy.client.VoltronProxyInvocationHandler.invoke(VoltronProxyInvocationHandler.java:109)
	  at com.sun.proxy.$Proxy7.delist(Unknown Source:-1)
	  at org.terracotta.consensus.CoordinationService.delist(CoordinationService.java:176)
	  at org.ehcache.clustered.client.internal.EhcacheClientEntityFactory.abandonLeadership(EhcacheClientEntityFactory.java:78)
	  at org.ehcache.clustered.client.internal.service.DefaultClusteringService.stop(DefaultClusteringService.java:182)
	  at org.ehcache.core.internal.service.ServiceLocator.stopAllServices(ServiceLocator.java:350)
	  at org.ehcache.core.EhcacheManager.close(EhcacheManager.java:608)
	  at org.ehcache.CacheManager$close$0.call(Unknown Source:-1)
	  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	  at com.terracottatech.issues.EhcacheIssue.run(EhcacheIssue.groovy:14)
```

**Comment by mathieucarbou** [comment]
I think we shouldn't block when closing because suppose you have 1,000 webapps depending on a server and the server fails, then it would mean that you'll have to force a kill on 1,000 servers if you cannot restart the voltron server on time ?

**Comment by mathieucarbou** [comment]
__Temporary workaround:__

Launch a thread that would interrupt the main thread after a certain amount of time:

```
[...]
println "Press a key to close..."
System.in.read()

Thread me = Thread.currentThread()
Thread.startDaemon {
  sleep(3_000)
  me.interrupt()
}

cacheManager.close()
```

**Comment by mathieucarbou** [comment]
__Full thread dump:__

```
```

**Comment by mathieucarbou** [comment]
@cljohnso : are there some progress or decision or fix made to avoid blocking on CM.close() ?
Thanks :-)

**Comment by cljohnso** [comment]
PR #1134 will prevent `CacheManager.close` from stalling but has no impact on other operations which may stall following a server termination.  The general issue is being discussed elsewhere and will be addressed under other issues.

**Comment by mathieucarbou** [comment]
Thanks @cljohnso !

**Comment by mathieucarbou** [comment]
I reopen because I was able to reproduce again.

Code (groovy):

```
import org.ehcache.CacheManager
import org.ehcache.clustered.client.config.builders.ClusteredResourcePoolBuilder
import org.ehcache.clustered.client.config.builders.ClusteringServiceConfigurationBuilder
import org.ehcache.config.CacheConfiguration
import org.ehcache.config.builders.CacheConfigurationBuilder
import org.ehcache.config.builders.CacheManagerBuilder
import org.ehcache.config.units.MemoryUnit
import org.ehcache.management.config.EhcacheStatisticsProviderConfiguration
import org.ehcache.management.config.StatisticsProviderConfiguration
import org.ehcache.management.registry.DefaultManagementRegistryConfiguration
import org.ehcache.management.registry.DefaultManagementRegistryService
import org.terracotta.management.registry.ManagementRegistry

import java.util.concurrent.TimeUnit

import static org.ehcache.config.builders.ResourcePoolsBuilder.heap

StatisticsProviderConfiguration statisticsProviderConfiguration = new EhcacheStatisticsProviderConfiguration(
    1, TimeUnit.MINUTES,
    100, 1, TimeUnit.SECONDS,
    30, TimeUnit.SECONDS)

ManagementRegistry managementRegistry = new DefaultManagementRegistryService(new DefaultManagementRegistryConfiguration()
    .setCacheManagerAlias("my-cm")
    .addConfiguration(statisticsProviderConfiguration));

CacheConfiguration<String, String> cacheConfiguration = CacheConfigurationBuilder.newCacheConfigurationBuilder(
    String.class, String.class,
    heap(10)
        .offheap(1, MemoryUnit.MB)
        .with(ClusteredResourcePoolBuilder.fixed("primary-server-resource", 1, MemoryUnit.MB))
).build()

CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
    .with(ClusteringServiceConfigurationBuilder.cluster(URI.create("terracotta://localhost:9510").resolve("/my-cm?auto-create"))
    .defaultServerResource("primary-server-resource"))
    .using(managementRegistry)
    .withCache("cache-1", cacheConfiguration)
    .withCache("cache-2", cacheConfiguration)
    .build(true);

println "Press a key to close..."
System.in.read()

cacheManager.close()
```

1. Start Voltron
2. run the client code
3. when it waits for a key, kill the server
4. press a key to continue the client.

The client blocks. Thread dump:

```
2016-06-15 11:50:53
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.51-b03 mixed mode):

"ConnectionEstablisher-0-1615744966" #29 daemon prio=5 os_prio=31 tid=0x00007f9ef21d3800 nid=0x7203 waiting on condition [0x00007000021f9000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at com.tc.net.protocol.transport.ClientConnectionEstablisher.handleConnectException(ClientConnectionEstablisher.java:351)
	at com.tc.net.protocol.transport.ClientConnectionEstablisher.reconnect(ClientConnectionEstablisher.java:265)
	at com.tc.net.protocol.transport.ClientConnectionEstablisher$AsyncReconnect.run(ClientConnectionEstablisher.java:501)
	at java.lang.Thread.run(Thread.java:745)

"Ehcache [null]-0" #28 prio=5 os_prio=31 tid=0x00007f9ef334a800 nid=0x700f waiting on condition [0x00007000020f6000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076c93ac18> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"Out of band notifier - Main" #27 daemon prio=5 os_prio=31 tid=0x00007f9ef2350000 nid=0x6a07 waiting on condition [0x0000700001ff3000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076f8711b0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at com.tc.cluster.ClusterImpl$OutOfBandNotifier$1.run(ClusterImpl.java:417)
	at java.lang.Thread.run(Thread.java:745)

"WorkerThread(lock_response_stage, 0)" #25 daemon prio=5 os_prio=31 tid=0x00007f9ef2d4c800 nid=0x6803 waiting on condition [0x0000700001ef0000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076b8cca70> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(server_entity_message_sender_stage, 0)" #24 daemon prio=5 os_prio=31 tid=0x00007f9ef2d4c000 nid=0x6603 waiting on condition [0x0000700001ded000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076b679e40> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(cluster_membership_event_stage, 0)" #23 daemon prio=5 os_prio=31 tid=0x00007f9ef2d4b000 nid=0x6403 waiting on condition [0x0000700001cea000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076b8faa10> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(server_entity_message_stage, 0)" #22 daemon prio=5 os_prio=31 tid=0x00007f9ef2d48800 nid=0x6203 waiting on condition [0x0000700001be7000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076b68f620> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(request_ack_stage, 0)" #21 daemon prio=5 os_prio=31 tid=0x00007f9ef2d47800 nid=0x6003 waiting on condition [0x0000700001ae4000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076b684588> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(hydrate_message_stage, 0)" #20 daemon prio=5 os_prio=31 tid=0x00007f9ef2d42800 nid=0x5e03 waiting on condition [0x00007000019e1000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076b8de3c0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(client_coordination_stage, 0)" #19 daemon prio=5 os_prio=31 tid=0x00007f9ef2d26000 nid=0x5c03 waiting on condition [0x00007000018de000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076b8efe48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(cluster_events_stage, 0)" #18 daemon prio=5 os_prio=31 tid=0x00007f9ef1a18800 nid=0x5a03 waiting on condition [0x00007000017db000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076b380618> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"task-runner-thread-0" #17 daemon prio=5 os_prio=31 tid=0x00007f9ef1b2d000 nid=0x5803 waiting on condition [0x00007000016d8000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076f896c90> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.poll(ScheduledThreadPoolExecutor.java:1134)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.poll(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"TC Memory Monitor" #16 prio=5 os_prio=31 tid=0x00007f9ef1b2f800 nid=0x5603 waiting on condition [0x00007000015d5000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at com.tc.runtime.TCMemoryManagerImpl$MemoryMonitor.run(TCMemoryManagerImpl.java:144)

"HealthChecker" #15 daemon prio=5 os_prio=31 tid=0x00007f9ef3317800 nid=0x5403 waiting on condition [0x00007000014d2000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at com.tc.util.concurrent.ThreadUtil.reallySleep(ThreadUtil.java:45)
	at com.tc.util.concurrent.ThreadUtil.reallySleep(ThreadUtil.java:31)
	at com.tc.net.protocol.transport.ConnectionHealthCheckerImpl$HealthCheckerMonitorThreadEngine.run(ConnectionHealthCheckerImpl.java:240)
	at java.lang.Thread.run(Thread.java:745)

"L1_L2:TCComm Main Selector Thread_W (listen 0:0:0:0:0:0:0:0:53697)" #14 daemon prio=5 os_prio=31 tid=0x00007f9ef2b64800 nid=0x5203 runnable [0x00007000013cf000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x000000076afc3418> (a sun.nio.ch.Util$2)
	- locked <0x000000076afc3408> (a java.util.Collections$UnmodifiableSet)
	- locked <0x000000076afc32e8> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	at com.tc.net.core.CoreNIOServices$CommThread.selectLoop(CoreNIOServices.java:566)
	at com.tc.net.core.CoreNIOServices$CommThread.run(CoreNIOServices.java:310)

"L1_L2:TCComm Main Selector Thread_R (listen 0:0:0:0:0:0:0:0:53697)" #13 daemon prio=5 os_prio=31 tid=0x00007f9ef2d2d000 nid=0x5003 runnable [0x00007000012cc000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x000000076afab230> (a sun.nio.ch.Util$2)
	- locked <0x000000076afab1a8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x000000076afa9890> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	at com.tc.net.core.CoreNIOServices$CommThread.selectLoop(CoreNIOServices.java:566)
	at com.tc.net.core.CoreNIOServices$CommThread.run(CoreNIOServices.java:310)

"SampledCounterManager Timer" #12 daemon prio=5 os_prio=31 tid=0x00007f9ef1a13800 nid=0x4e03 in Object.wait() [0x00007000011c9000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076ab1bc08> (a java.util.TaskQueue)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x000000076ab1bc08> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"Monitor Ctrl-Break" #9 daemon prio=5 os_prio=31 tid=0x00007f9ef3050000 nid=0x4c03 runnable [0x00007000010c6000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x000000076e0f4228> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	- locked <0x000000076e0f4228> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at com.intellij.rt.execution.application.AppMain$1.run(AppMain.java:93)
	at java.lang.Thread.run(Thread.java:745)

"Service Thread" #8 daemon prio=9 os_prio=31 tid=0x00007f9ef3029800 nid=0x4803 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007f9ef3029000 nid=0x4603 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007f9ef2844000 nid=0x4403 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007f9ef2015000 nid=0x4203 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007f9ef3028000 nid=0x320f waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007f9ef185a000 nid=0x3003 in Object.wait() [0x000070000092e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076f5908d8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x000000076f5908d8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007f9ef281c000 nid=0x2e03 in Object.wait() [0x000070000082b000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076f590a90> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
	- locked <0x000000076f590a90> (a java.lang.ref.Reference$Lock)

"main" #1 prio=5 os_prio=31 tid=0x00007f9ef280d800 nid=0x1003 in Object.wait() [0x0000700000181000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076e00a4f8> (a com.tc.object.InFlightMessage)
	at java.lang.Object.wait(Object.java:502)
	at com.tc.object.InFlightMessage.get(InFlightMessage.java:141)
	- locked <0x000000076e00a4f8> (a com.tc.object.InFlightMessage)
	at com.tc.object.InFlightMessage.get(InFlightMessage.java:42)
	at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl$1.get(EntityClientEndpointImpl.java:164)
	at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl$1.get(EntityClientEndpointImpl.java:155)
	at org.ehcache.clustered.client.internal.EhcacheClientEntity.invokeInternal(EhcacheClientEntity.java:227)
	at org.ehcache.clustered.client.internal.EhcacheClientEntity.releaseCache(EhcacheClientEntity.java:171)
	at org.ehcache.clustered.client.internal.service.DefaultClusteringService.releaseServerStoreProxy(DefaultClusteringService.java:327)
	at org.ehcache.clustered.client.internal.store.ClusteredStore$Provider.releaseStore(ClusteredStore.java:408)
	at org.ehcache.clustered.client.internal.store.ClusteredStore$Provider.releaseAuthoritativeTier(ClusteredStore.java:485)
	at org.ehcache.impl.internal.store.tiering.TieredStore$Provider.releaseStore(TieredStore.java:494)
	at org.ehcache.core.EhcacheManager$7.close(EhcacheManager.java:495)
	at org.ehcache.core.StatusTransitioner.runCloseHooks(StatusTransitioner.java:158)
	at org.ehcache.core.StatusTransitioner.access$200(StatusTransitioner.java:33)
	at org.ehcache.core.StatusTransitioner$Transition.succeeded(StatusTransitioner.java:198)
	at org.ehcache.core.Ehcache.close(Ehcache.java:654)
	at org.ehcache.core.EhcacheManager.removeCache(EhcacheManager.java:193)
	at org.ehcache.core.EhcacheManager.close(EhcacheManager.java:598)
	at org.ehcache.CacheManager$close.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at com.terracottatech.issues.Ehcache_1108.run(Ehcache_1108.groovy:47)
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:263)
	at groovy.lang.GroovyShell.run(GroovyShell.java:518)
	at groovy.lang.GroovyShell.run(GroovyShell.java:507)
	at groovy.ui.GroovyMain.processOnce(GroovyMain.java:652)
	at groovy.ui.GroovyMain.run(GroovyMain.java:384)
	at groovy.ui.GroovyMain.process(GroovyMain.java:370)
	at groovy.ui.GroovyMain.processArgs(GroovyMain.java:129)
	at groovy.ui.GroovyMain.main(GroovyMain.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:109)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

"VM Thread" os_prio=31 tid=0x00007f9ef200e800 nid=0x2c03 runnable 

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007f9ef2008800 nid=0x2403 runnable 

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007f9ef180d800 nid=0x2603 runnable 

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007f9ef2817800 nid=0x2803 runnable 

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007f9ef1805800 nid=0x2a03 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x00007f9ef2011800 nid=0x4a03 waiting on condition 

JNI global references: 342

Heap
 PSYoungGen      total 76288K, used 63833K [0x000000076ab00000, 0x0000000770000000, 0x00000007c0000000)
  eden space 65536K, 85% used [0x000000076ab00000,0x000000076e197f48,0x000000076eb00000)
  from space 10752K, 73% used [0x000000076f580000,0x000000076fd3e640,0x0000000770000000)
  to   space 10752K, 0% used [0x000000076eb00000,0x000000076eb00000,0x000000076f580000)
 ParOldGen       total 175104K, used 80K [0x00000006c0000000, 0x00000006cab00000, 0x000000076ab00000)
  object space 175104K, 0% used [0x00000006c0000000,0x00000006c0014010,0x00000006cab00000)
 Metaspace       used 20703K, capacity 21084K, committed 21248K, reserved 1067008K
  class space    used 2592K, capacity 2718K, committed 2816K, reserved 1048576K
```
