### ISSUE TITLE
Overriding cache level service configuration extensions from template is not working

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#1116]
For cache level service extensions, there is a bug in the way the configuration parser works that prevents a cache from overriding what a template defined.

Example:
```xml
<cache alias="template-override-consistency-cache" uses-template="strong-consistency-template">
  <tc:clustered-store consistency="eventual"/>
</cache>

<cache-template name="strong-consistency-template">
  <resources>
    <tc:cluster-fixed unit="MB">5</tc:cluster-fixed>
  </resources>
  <tc:clustered-store consistency="strong"/>
</cache-template>
```

fails with:

    Caused by: java.lang.IllegalStateException: Cannot add a generic service configuration when another one already exists. Rely on specific with* methods or make sure your remove other configuration first.
	at org.ehcache.config.builders.CacheConfigurationBuilder.add(CacheConfigurationBuilder.java:131)
	at org.ehcache.xml.XmlConfiguration.parseConfiguration(XmlConfiguration.java:296)

**Comment by ljacomet** [comment]
In the context of 3.0.2, the example is not applicable, but a similar problem exists with the transaction extension.
