### ISSUE TITLE
Changing a cache from using a fixed pool to a shared one gives internal error message

### ISSUE THREAD

**Issue by GaryWKeim** [ehcache/ehcache3#1130]
```
Caused by: java.lang.ClassCastException: org.ehcache.clustered.common.ServerStoreConfiguration$PoolAllocation$Shared cannot be cast to org.ehcache.clustered.common.ServerStoreConfiguration$PoolAllocation$Fixed
	at org.ehcache.clustered.common.ServerStoreCompatibility.verify(ServerStoreCompatibility.java:50)
	at org.ehcache.clustered.server.EhcacheActiveEntity.validateServerStore(EhcacheActiveEntity.java:717)
```

**Comment by ljacomet** [comment]
This should be tackled by #859 which is still in progress.
