### ISSUE TITLE
Improve exception message when a clustered cachemanager entity doesn't exist

### ISSUE THREAD

**Issue by aurbroszniowski** [ehcache/ehcache3#1184]
Using 

  ```
  Ehcache Clustered Implementation-Version: 3.1.0-SNAPSHOT 081007b2d8a41f018abe55f85407069
   dc8e53e9a
  ```

  and 

  ```
  Terracotta 5.0.0-SNAPSHOT, as of 2016-06-14 at 09:28:52 EDT (Revision 2a5deb444144e54c75f6996454cc2470e6a1308f from UNKNOWN)
  ```
  
When trying to programmatically create a Clustered CacheManager, and not setting the autocreate flag of the ClusteringServiceConfigurationBuilder to true, if the Cache Manager entity doesn't exist yet, then the exception is

```
org.ehcache.StateTransitionException: org.terracotta.exception.EntityNotFoundException: Entity: org.ehcache.clustered.client.internal.EhcacheClientEntity:myCachemanager not found

	at org.ehcache.core.StatusTransitioner$Transition.failed(StatusTransitioner.java:235)
	at org.ehcache.core.EhcacheManager.init(EhcacheManager.java:585)
	at org.ehcache.config.builders.CacheManagerBuilder.build(CacheManagerBuilder.java:72)
	at com.terracotta.qa.performance.clustered.Ehcache3HeapOffheapTsa.test(Ehcache3HeapOffheapTsa.java:114)
	
Caused by: java.lang.IllegalStateException: org.terracotta.exception.EntityNotFoundException: Entity: org.ehcache.clustered.client.internal.EhcacheClientEntity:myCachemanager not found
	at org.ehcache.clustered.client.internal.service.DefaultClusteringService.start(DefaultClusteringService.java:140)
	at org.ehcache.core.internal.service.ServiceLocator.startAllServices(ServiceLocator.java:306)
	at org.ehcache.core.EhcacheManager.init(EhcacheManager.java:557)
	... 31 more
Caused by: org.terracotta.exception.EntityNotFoundException: Entity: org.ehcache.clustered.client.internal.EhcacheClientEntity:myCachemanager not found
	at com.tc.objectserver.handler.ProcessTransactionHandler.addMessage(ProcessTransactionHandler.java:246)
	at com.tc.objectserver.handler.ProcessTransactionHandler.access$200(ProcessTransactionHandler.java:59)
	at com.tc.objectserver.handler.ProcessTransactionHandler$1.handleEvent(ProcessTransactionHandler.java:87)
	at com.tc.objectserver.handler.ProcessTransactionHandler$1.handleEvent(ProcessTransactionHandler.java:70)
	at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197)
```

which is not helping to understand what the solution is.

I would suggest to improve the message, otherwise this issue looks like a good candidate to be one of the most popular Ehcache related questions on StackOverflow

**Comment by chrisdennis** [comment]
@aurbroszniowski - it's pretty simple to modify the message to something a little more user-friendly.  You have any suggestions for wording?

**Comment by aurbroszniowski** [comment]
Maybe something like "The server-side entity clustering your cache manager needs to be created, Please review your cache manager configuration" (feel free to rephrase in proper english)

Also, what is partly missing in the current documentation is an explanation of the concept of entities. There are some details about the fact that a clustered cache manager uses a server side entity, but no details about what entities are.
