### ISSUE TITLE
Second Clustered Ehcache client blocks when auto-create is set to true

### ISSUE THREAD

**Issue by aurbroszniowski** [ehcache/ehcache3#1186]
Using 

```
Ehcache Clustered Implementation-Version: 3.1.0-SNAPSHOT 081007b2d8a41f018abe55f85407069
 dc8e53e9a
```

and 

```
Terracotta 5.0.0-SNAPSHOT, as of 2016-06-14 at 09:28:52 EDT (Revision 2a5deb444144e54c75f6996454cc2470e6a1308f from UNKNOWN)
```

With the following config builder:

```
    CacheManagerBuilder<PersistentCacheManager> managerBuilder = newCacheManagerBuilder()
        .with(ClusteringServiceConfigurationBuilder.cluster(URI.create("terracotta://myhost/my-application")).autoCreate(true))
        .withCache("cache", CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, byte[].class,
            ResourcePoolsBuilder.newResourcePoolsBuilder()
                .heap(nbElementsHeap, EntryUnit.ENTRIES)
                .offheap(offheap, MemoryUnit.GB)
                .with(ClusteredResourcePoolBuilder.fixed("primary-server-resource", tsa, MemoryUnit.GB)))
            .build());
```

the auto-create flag is set to true, the first client starts and the second one blocks with the following thread dump:

```
2016-06-18 15:19:37
Full thread dump Java HotSpot(TM) 64-Bit Server VM (24.72-b04 mixed mode):

"Attach Listener" daemon prio=10 tid=0x00007ff3d8001000 nid=0xaf66 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Out of band notifier - Main" daemon prio=10 tid=0x00007ff4646ab000 nid=0xaf23 waiting on condition [0x00007ff387ffe000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000782f79508> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at com.tc.cluster.ClusterImpl$OutOfBandNotifier$1.run(ClusterImpl.java:417)
	at java.lang.Thread.run(Thread.java:745)

"WorkerThread(lock_response_stage, 0)" daemon prio=10 tid=0x00007ff4646a9000 nid=0xaf21 waiting on condition [0x00007ff3dc15a000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007837c2bb0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(client_coordination_stage, 0)" daemon prio=10 tid=0x00007ff4646a7000 nid=0xaf20 waiting on condition [0x00007ff3dc25b000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007837d8270> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(server_entity_message_sender_stage, 0)" daemon prio=10 tid=0x00007ff4646a5000 nid=0xaf1f waiting on condition [0x00007ff3dc35c000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007836ba9b8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(server_entity_message_stage, 0)" daemon prio=10 tid=0x00007ff4646a2800 nid=0xaf1e waiting on condition [0x00007ff3dc45d000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007836c8988> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(cluster_events_stage, 0)" daemon prio=10 tid=0x00007ff4646a0800 nid=0xaf1d waiting on condition [0x00007ff3dc55e000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007834f0750> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(request_ack_stage, 0)" daemon prio=10 tid=0x00007ff46469e800 nid=0xaf1c waiting on condition [0x00007ff3dc65f000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007836c1708> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(hydrate_message_stage, 0)" daemon prio=10 tid=0x00007ff46469d000 nid=0xaf1b waiting on condition [0x00007ff3dc760000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007837cd778> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"WorkerThread(cluster_membership_event_stage, 0)" daemon prio=10 tid=0x00007ff464699000 nid=0xaf1a waiting on condition [0x00007ff3dc861000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007837def28> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

"task-runner-thread-0" daemon prio=10 tid=0x00007ff464692800 nid=0xaf19 waiting on condition [0x00007ff3dc962000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000783063ee0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.poll(ScheduledThreadPoolExecutor.java:1130)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.poll(ScheduledThreadPoolExecutor.java:807)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

"TC Memory Monitor" prio=10 tid=0x00007ff46468d800 nid=0xaf18 waiting on condition [0x00007ff3dca63000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at com.tc.runtime.TCMemoryManagerImpl$MemoryMonitor.run(TCMemoryManagerImpl.java:144)

"HealthChecker" daemon prio=10 tid=0x00007ff464656000 nid=0xaf17 waiting on condition [0x00007ff3dcd6c000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at com.tc.util.concurrent.ThreadUtil.reallySleep(ThreadUtil.java:45)
	at com.tc.util.concurrent.ThreadUtil.reallySleep(ThreadUtil.java:31)
	at com.tc.net.protocol.transport.ConnectionHealthCheckerImpl$HealthCheckerMonitorThreadEngine.run(ConnectionHealthCheckerImpl.java:240)
	at java.lang.Thread.run(Thread.java:745)

"L1_L2:TCComm Main Selector Thread_W (listen 0:0:0:0:0:0:0:0:55280)" daemon prio=10 tid=0x00007ff464653000 nid=0xaf16 runnable [0x00007ff3dce6d000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x0000000783384200> (a sun.nio.ch.Util$2)
	- locked <0x00000007833841f0> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000007833840d8> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
	at com.tc.net.core.CoreNIOServices$CommThread.selectLoop(CoreNIOServices.java:566)
	at com.tc.net.core.CoreNIOServices$CommThread.run(CoreNIOServices.java:310)

"L1_L2:TCComm Main Selector Thread_R (listen 0:0:0:0:0:0:0:0:55280)" daemon prio=10 tid=0x00007ff46461d800 nid=0xaf15 runnable [0x00007ff3dcf6e000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x0000000783364f48> (a sun.nio.ch.Util$2)
	- locked <0x0000000783364ee0> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000783364d60> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
	at com.tc.net.core.CoreNIOServices$CommThread.selectLoop(CoreNIOServices.java:566)
	at com.tc.net.core.CoreNIOServices$CommThread.run(CoreNIOServices.java:310)

"SampledCounterManager Timer" daemon prio=10 tid=0x00007ff4645f9000 nid=0xaf14 in Object.wait() [0x00007ff3dd06f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000783132758> (a java.util.TaskQueue)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x0000000783132758> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"Service Thread" daemon prio=10 tid=0x00007ff46435f800 nid=0xaf12 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" daemon prio=10 tid=0x00007ff464357000 nid=0xaf11 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" daemon prio=10 tid=0x00007ff464355000 nid=0xaf10 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM JFR Buffer Thread" daemon prio=10 tid=0x00007ff464338800 nid=0xaf0f waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JFR request timer" daemon prio=10 tid=0x00007ff4640dc800 nid=0xaf0e in Object.wait() [0x00007ff3f045b000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000078005d7a0> (a java.util.TaskQueue)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x000000078005d7a0> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"Signal Dispatcher" daemon prio=10 tid=0x00007ff4640d6800 nid=0xaf0d runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" daemon prio=10 tid=0x00007ff46409b000 nid=0xaf0c in Object.wait() [0x00007ff3f129f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007800047f8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
	- locked <0x00000007800047f8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" daemon prio=10 tid=0x00007ff464099000 nid=0xaf0b in Object.wait() [0x00007ff3f13a0000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000780004410> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:503)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)
	- locked <0x0000000780004410> (a java.lang.ref.Reference$Lock)

"main" prio=10 tid=0x00007ff46400a000 nid=0xaef2 waiting on condition [0x00007ff46c3be000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000783b08f08> (a java.util.concurrent.Semaphore$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:994)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
	at java.util.concurrent.Semaphore.acquire(Semaphore.java:317)
	at com.tc.object.locks.LockStateNode$PendingLockHold.park(LockStateNode.java:222)
	at com.tc.object.locks.ClientLockImpl.acquireQueued(ClientLockImpl.java:924)
	at com.tc.object.locks.ClientLockImpl.acquireQueued(ClientLockImpl.java:898)
	at com.tc.object.locks.ClientLockImpl.lock(ClientLockImpl.java:104)
	at com.tc.object.locks.ClientLockManagerImpl.lock(ClientLockManagerImpl.java:123)
	at com.terracotta.connection.entity.MaintenanceModeService.lock(MaintenanceModeService.java:66)
	at com.terracotta.connection.entity.MaintenanceModeService.enterMaintenanceMode(MaintenanceModeService.java:51)
	at com.terracotta.connection.entity.TerracottaEntityRef.create(TerracottaEntityRef.java:126)
	at org.ehcache.clustered.client.internal.EhcacheClientEntityFactory$2.call(EhcacheClientEntityFactory.java:101)
	at org.ehcache.clustered.client.internal.EhcacheClientEntityFactory$2.call(EhcacheClientEntityFactory.java:95)
	at org.terracotta.consensus.CoordinationService.executeIfLeader(CoordinationService.java:124)
	- locked <0x0000000783ab3ed8> (a java.lang.Object)
	- locked <0x0000000783ab3ed8> (a java.lang.Object)
	at org.ehcache.clustered.client.internal.EhcacheClientEntityFactory.asLeaderOf(EhcacheClientEntityFactory.java:196)
	at org.ehcache.clustered.client.internal.EhcacheClientEntityFactory.create(EhcacheClientEntityFactory.java:95)
	at org.ehcache.clustered.client.internal.service.DefaultClusteringService.start(DefaultClusteringService.java:127)
	at org.ehcache.core.internal.service.ServiceLocator.startAllServices(ServiceLocator.java:306)
	at org.ehcache.core.EhcacheManager.init(EhcacheManager.java:557)
	at org.ehcache.config.builders.CacheManagerBuilder.build(CacheManagerBuilder.java:72)
	at com.terracotta.qa.performance.clustered.Ehcache3HeapOffheapTsa.test(Ehcache3HeapOffheapTsa.java:110)
	at com.terracotta.qa.performance.clustered.Ehcache3HeapOffheapTsa.testHeapOffheapDisk(Ehcache3HeapOffheapTsa.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
```

**Comment by rrbadam** [comment]
I want to take the issue. Can I know who is managing this community

**Comment by chrisdennis** [comment]
@rrbadam we pretty confident that this issue is both outdated since the symptoms will have changed after the merge of #1152 and that any fix will really have to happen under Terracotta-OSS/terracotta-core#212 for which work is already in process.  All this taken together I don't think this is a good issue to be picking up as a first issue.

All this makes me wonder if we should have a label that we can use for issues that are suitable to be picked up as "first contributor" issues.  Let me discuss that with some people internally and get back to you.

**Comment by rrbadam** [comment]
Thanks Chris for the reply. Kindly let me know if you find anything which I can start working on. I will be more than happy to be part of community.

**Comment by chrisdennis** [comment]
@aurbroszniowski 
So much has changed here that this is going to be invalid anyway.  If this still occurs lets file a new bug.
