### ISSUE TITLE
Second Clustered Ehcache client throws exception when auto-create is set to false

### ISSUE THREAD

**Issue by aurbroszniowski** [ehcache/ehcache3#1187]
Using 

  ```
  Ehcache Clustered Implementation-Version: 3.1.0-SNAPSHOT 081007b2d8a41f018abe55f85407069
   dc8e53e9a
  ```

  and 

  ```
  Terracotta 5.0.0-SNAPSHOT, as of 2016-06-14 at 09:28:52 EDT (Revision 2a5deb444144e54c75f6996454cc2470e6a1308f from UNKNOWN)
  ```
  
With the following config builder:

```
    CacheManagerBuilder<PersistentCacheManager> managerBuilder = newCacheManagerBuilder()
        .with(ClusteringServiceConfigurationBuilder.cluster(URI.create("terracotta://myhost/my-application")).autoCreate(myflag))
        .withCache("cache", CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, byte[].class,
            ResourcePoolsBuilder.newResourcePoolsBuilder()
                .heap(nbElementsHeap, EntryUnit.ENTRIES)
                .offheap(offheap, MemoryUnit.GB)
                .with(ClusteredResourcePoolBuilder.fixed("primary-server-resource", tsa, MemoryUnit.GB)))
            .build());
```

the auto-create flag is set to true for the first client, and false for the second one

The second one throws the exception below after starting, then seems to work correctly.

```
  [testng] java.lang.AbstractMethodError: org.ehcache.impl.internal.store.offheap.EhcacheConcurrentOffHeapClockCache.removeAllWithHash(I)Ljava/util/Map;
  [testng] 	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.invalidateAllWithHash(AbstractOffHeapStore.java:982)
  [testng] 	at org.ehcache.impl.internal.store.tiering.CompoundCachingTier.invalidateAllWithHash(CompoundCachingTier.java:186)
  [testng] 	at org.ehcache.impl.internal.store.tiering.TieredStore$2.invalidateAllWithHash(TieredStore.java:96)
  [testng] 	at org.ehcache.clustered.client.internal.store.ClusteredStore$Provider$1.onInvalidateHash(ClusteredStore.java:524)
  [testng] 	at org.ehcache.clustered.client.internal.store.EventualServerStoreProxy$2.onResponse(EventualServerStoreProxy.java:65)
  [testng] 	at org.ehcache.clustered.client.internal.store.EventualServerStoreProxy$2.onResponse(EventualServerStoreProxy.java:55)
  [testng] 	at org.ehcache.clustered.client.internal.EhcacheClientEntity.fireResponseEvent(EhcacheClientEntity.java:108)
  [testng] 	at org.ehcache.clustered.client.internal.EhcacheClientEntity.access$000(EhcacheClientEntity.java:49)
  [testng] 	at org.ehcache.clustered.client.internal.EhcacheClientEntity$1.handleMessage(EhcacheClientEntity.java:74)
  [testng] 	at com.tc.object.EntityClientEndpointImpl.handleMessage(EntityClientEndpointImpl.java:87)
  [testng] 	at com.tc.object.ClientEntityManagerImpl.handleMessage(ClientEntityManagerImpl.java:162)
  [testng] 	at com.tc.object.servermessage.ServerMessageReceiveHandler.handleEvent(ServerMessageReceiveHandler.java:46)
  [testng] 	at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502)
  [testng] 	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197)
```

**Comment by ljacomet** [comment]
Can you give information on your classpath? This looks like there is an older version of ehcache 3 on it.

**Comment by cljohnso** [comment]
`offheap-store-2.2.1.jar` must not be included in your classpath; the version of it used by Ehcache3 is included in the `ehcache-clustered` jar.

You _may_ run into some difficulties combining the Ehcache3 jars with the `ehcache-ee` and `terracotta-toolkit-runtime-ee` jars but that is less clear than the need to omit the `offheap-store` jar from your classpath.

**Comment by aurbroszniowski** [comment]
After removing the extra offheap dependency, I don't see the exception anymore
