### ISSUE TITLE
Clustered cache when allocated insufficient resources fails disgracefully

### ISSUE THREAD

**Issue by kedar031** [ehcache/ehcache3#1254]
Client version:

```
org.ehcache.ehcache-clustered
Implementation-Version: 3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2
```

Server version:

```
Terracotta 5.0.0-SNAPSHOT, as of 2016-06-28 at 17:34:13 EDT (Revision 1918ff0b95bb691aa6eb65cfbe001fbde815aee7 from UNKNOWN)
```

Cache congiuration:

``` java
CacheManagerBuilder.newCacheManagerBuilder()
        .with(ClusteringServiceConfigurationBuilder.cluster(CLUSTER_URI).autoCreate()
        .defaultServerResource("primary-server-resource")
        .resourcePool("resource-pool-a", 64, MemoryUnit.MB)
        .resourcePool("resource-pool-b", 64, MemoryUnit.MB, "secondary-server-resource"))
        .withCache(CACHE_NAME, CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, AddressProto.Address.class,
            ResourcePoolsBuilder.newResourcePoolsBuilder()
                .with(ClusteredResourcePoolBuilder.clusteredDedicated("primary-server-resource", 32, MemoryUnit.KB)))
            .add(new ClusteredStoreConfiguration(Consistency.STRONG)));
```

Test code snippet:

``` java
     LOG.info("Going to await for other clients ");
      id = barrier.await();

      AddressGenerator valueGen = new AddressGenerator();

      if (0 == id) {
        for (long i = 0; i < 1; i++) {
          cache.put(i, valueGen.generate(i));
        }
      }
      barrier.await();
      if (1 == id) {
        LOG.info("Going to await for other clients ");
        for (long i = 0; i < 1; i++) {
          assertThat(cache.get(i), is(valueGen.generate(i)));
        }
      }
      barrier.await();
```

When two clients are started, the first does put and hits the below exception; while the other client tries get and fails with Assertion error.
Note that the below exception repeats for each put resulting in flooding the stdout.
Also note that when increased resources for the cache, the test passes fine.

Exception:

```
17:39:02.085 [main] INFO  c.t.q.e.test.MultipleClientsTest - Going to await for other threads 
17:39:02.153 [main] ERROR o.e.c.i.r.LoggingRobustResilienceStrategy - Ehcache key 0 in possible inconsistent state due to 
org.ehcache.core.spi.store.StoreAccessException: java.lang.RuntimeException: org.ehcache.clustered.client.internal.store.ServerStoreProxyException: java.lang.RuntimeException: SERVER_STORE_OP#GET_AND_APPEND error: org.terracotta.offheapstore.exceptions.OversizeMappingException: Storage Engine and Eviction Failed - Empty Map
Storage Engine : org.ehcache.clustered.server.offheap.OffHeapChainStorageEngine@6959044e
    at org.ehcache.core.exceptions.StorePassThroughException.handleRuntimeException(StorePassThroughException.java:72) ~[ehcache-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    at org.ehcache.clustered.client.internal.store.ClusteredStore.silentPut(ClusteredStore.java:187) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    at org.ehcache.clustered.client.internal.store.ClusteredStore.put(ClusteredStore.java:158) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    at org.ehcache.core.Ehcache.put(Ehcache.java:196) ~[ehcache-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    at com.terracotta.qa.ehcache.test.MultipleClientsTest.testCRUDOps(MultipleClientsTest.java:111) [test-classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85) [testng-6.8.17.jar:na]
    at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200) [testng-6.8.17.jar:na]
    at org.jboss.byteman.contrib.bmunit.BMNGAbstractRunner.run(BMNGAbstractRunner.java:58) [byteman-bmunit-2.1.2.jar:na]
    at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212) [testng-6.8.17.jar:na]
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:689) [testng-6.8.17.jar:na]
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882) [testng-6.8.17.jar:na]
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189) [testng-6.8.17.jar:na]
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124) [testng-6.8.17.jar:na]
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108) [testng-6.8.17.jar:na]
    at org.testng.TestRunner.privateRun(TestRunner.java:767) [testng-6.8.17.jar:na]
    at org.testng.TestRunner.run(TestRunner.java:617) [testng-6.8.17.jar:na]
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:348) [testng-6.8.17.jar:na]
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343) [testng-6.8.17.jar:na]
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305) [testng-6.8.17.jar:na]
    at org.testng.SuiteRunner.run(SuiteRunner.java:254) [testng-6.8.17.jar:na]
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.8.17.jar:na]
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.8.17.jar:na]
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224) [testng-6.8.17.jar:na]
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1149) [testng-6.8.17.jar:na]
    at org.testng.TestNG.run(TestNG.java:1057) [testng-6.8.17.jar:na]
    at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74) [testng-plugin.jar:na]
    at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:121) [testng-plugin.jar:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:na]
Caused by: java.lang.RuntimeException: org.ehcache.clustered.client.internal.store.ServerStoreProxyException: java.lang.RuntimeException: SERVER_STORE_OP#GET_AND_APPEND error: org.terracotta.offheapstore.exceptions.OversizeMappingException: Storage Engine and Eviction Failed - Empty Map
Storage Engine : org.ehcache.clustered.server.offheap.OffHeapChainStorageEngine@6959044e
    at org.ehcache.clustered.client.internal.store.StrongServerStoreProxy.performWaitingForHashInvalidation(StrongServerStoreProxy.java:197) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    at org.ehcache.clustered.client.internal.store.StrongServerStoreProxy.getAndAppend(StrongServerStoreProxy.java:292) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    at org.ehcache.clustered.client.internal.store.ClusteredStore.silentPut(ClusteredStore.java:179) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    ... 34 common frames omitted
Caused by: org.ehcache.clustered.client.internal.store.ServerStoreProxyException: java.lang.RuntimeException: SERVER_STORE_OP#GET_AND_APPEND error: org.terracotta.offheapstore.exceptions.OversizeMappingException: Storage Engine and Eviction Failed - Empty Map
Storage Engine : org.ehcache.clustered.server.offheap.OffHeapChainStorageEngine@6959044e
    at org.ehcache.clustered.client.internal.store.NoInvalidationServerStoreProxy.getAndAppend(NoInvalidationServerStoreProxy.java:85) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    at org.ehcache.clustered.client.internal.store.StrongServerStoreProxy$8.apply(StrongServerStoreProxy.java:295) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    at org.ehcache.clustered.client.internal.store.StrongServerStoreProxy$8.apply(StrongServerStoreProxy.java:292) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    at org.ehcache.clustered.client.internal.store.StrongServerStoreProxy.performWaitingForHashInvalidation(StrongServerStoreProxy.java:190) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    ... 36 common frames omitted
Caused by: java.lang.RuntimeException: SERVER_STORE_OP#GET_AND_APPEND error: org.terracotta.offheapstore.exceptions.OversizeMappingException: Storage Engine and Eviction Failed - Empty Map
Storage Engine : org.ehcache.clustered.server.offheap.OffHeapChainStorageEngine@6959044e
    at org.ehcache.clustered.client.internal.EhcacheClientEntity.invokeInternal(EhcacheClientEntity.java:216) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    at org.ehcache.clustered.client.internal.EhcacheClientEntity.invoke(EhcacheClientEntity.java:203) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    at org.ehcache.clustered.client.internal.store.NoInvalidationServerStoreProxy.getAndAppend(NoInvalidationServerStoreProxy.java:83) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    ... 39 common frames omitted
org.terracotta.offheapstore.exceptions.OversizeMappingException: Storage Engine and Eviction Failed - Empty Map
Storage Engine : org.ehcache.clustered.server.offheap.OffHeapChainStorageEngine@6959044e
    at org.terracotta.offheapstore.AbstractOffHeapClockCache.storageEngineFailure(AbstractOffHeapClockCache.java:84) ~[ehcache-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    at org.terracotta.offheapstore.OffHeapHashMap.writeEntry(OffHeapHashMap.java:689) ~[ehcache-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    at org.terracotta.offheapstore.OffHeapHashMap.put(OffHeapHashMap.java:471) ~[ehcache-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    at org.terracotta.offheapstore.AbstractLockedOffHeapHashMap.put(AbstractLockedOffHeapHashMap.java:145) ~[ehcache-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    at org.terracotta.offheapstore.OffHeapHashMap.put(OffHeapHashMap.java:461) ~[ehcache-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    at org.terracotta.offheapstore.AbstractLockedOffHeapHashMap.put(AbstractLockedOffHeapHashMap.java:134) ~[ehcache-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    at org.ehcache.clustered.server.offheap.OffHeapChainMap.getAndAppend(OffHeapChainMap.java:98) ~[na:na]
    at org.ehcache.clustered.server.offheap.OffHeapServerStore.getAndAppend(OffHeapServerStore.java:107) ~[na:na]
    at org.ehcache.clustered.server.ServerStoreImpl.getAndAppend(ServerStoreImpl.java:70) ~[na:na]
    at org.ehcache.clustered.server.EhcacheActiveEntity.invokeServerStoreOperation(EhcacheActiveEntity.java:375) ~[na:na]
    at org.ehcache.clustered.server.EhcacheActiveEntity.invoke(EhcacheActiveEntity.java:287) ~[na:na]
    at org.ehcache.clustered.server.EhcacheActiveEntity.invoke(EhcacheActiveEntity.java:86) ~[na:na]
    at com.tc.objectserver.entity.ManagedEntityImpl.lambda$performAction$27(ManagedEntityImpl.java:610) ~[na:na]
    at com.tc.objectserver.entity.ManagedEntityImpl.runWithHelper(ManagedEntityImpl.java:259) ~[na:na]
    at com.tc.objectserver.entity.ManagedEntityImpl.performAction(ManagedEntityImpl.java:610) ~[na:na]
    at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:358) ~[na:na]
    at com.tc.objectserver.entity.ManagedEntityImpl.lambda$processInvokeRequest$20(ManagedEntityImpl.java:204) ~[na:na]
    at com.tc.objectserver.entity.ManagedEntityImpl$SchedulingRunnable.run(ManagedEntityImpl.java:837) ~[na:na]
    at com.tc.objectserver.entity.RequestProcessor$EntityRequest.invoke(RequestProcessor.java:219) ~[na:na]
    at com.tc.objectserver.entity.RequestProcessor$EntityRequest.run(RequestProcessor.java:211) ~[na:na]
    at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:27) ~[na:na]
    at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:23) ~[na:na]
    at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
    at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT 2042c854cd7c837e93ea21e2cc09559bd2ca7af2]
```

**Comment by chrisdennis** [comment]
The logging might be verbose, but it's not inaccurate. A system running in this state is not tenable long term.
