### ISSUE TITLE
Clustered buffer underflow seen when under pressure

### ISSUE THREAD

**Issue by cschanck** [ehcache/ehcache3#1277]
o.e.c.i.r.LoggingRobustResilienceStrategy - Ehcache key 45099 in possible inconsistent state due to 
org.ehcache.core.spi.store.StoreAccessException: java.nio.BufferUnderflowException
	at org.ehcache.core.exceptions.StorePassThroughException.handleRuntimeException(StorePassThroughException.java:72) ~[ehcache-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT dbaf9901e0e2786eef9e107b174c3f9a869650cf]
	at org.ehcache.clustered.client.internal.store.ClusteredStore.silentPut(ClusteredStore.java:189) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT dbaf9901e0e2786eef9e107b174c3f9a869650cf]
	at org.ehcache.clustered.client.internal.store.ClusteredStore.put(ClusteredStore.java:160) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT dbaf9901e0e2786eef9e107b174c3f9a869650cf]
	at org.ehcache.impl.internal.store.tiering.TieredStore.put(TieredStore.java:149) ~[ehcache-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT dbaf9901e0e2786eef9e107b174c3f9a869650cf]
	at org.ehcache.core.Ehcache.put(Ehcache.java:196) ~[ehcache-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT dbaf9901e0e2786eef9e107b174c3f9a869650cf]
	at com.terracotta.qa.ehcache.validation.ValidatingPutOperation.exec(ValidatingPutOperation.java:56) [classes/:na]
	at io.rainfall.execution.RunsDuring$1.call(RunsDuring.java:79) [rainfall-core-1.1.3-20160624.105609-14.jar:na]
	at io.rainfall.execution.RunsDuring$1.call(RunsDuring.java:71) [rainfall-core-1.1.3-20160624.105609-14.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
Caused by: java.nio.BufferUnderflowException: null
	at java.nio.Buffer.nextGetIndex(Buffer.java:500) ~[na:1.8.0_66]
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:135) ~[na:1.8.0_66]
	at org.ehcache.clustered.client.internal.store.operations.codecs.OperationsCodec.decode(OperationsCodec.java:41) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT dbaf9901e0e2786eef9e107b174c3f9a869650cf]
	at org.ehcache.clustered.client.internal.store.operations.ChainResolver.resolve(ChainResolver.java:65) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT dbaf9901e0e2786eef9e107b174c3f9a869650cf]
	at org.ehcache.clustered.client.internal.store.ClusteredStore.silentPut(ClusteredStore.java:182) ~[ehcache-clustered-3.1.0-SNAPSHOT.jar:3.1.0-SNAPSHOT dbaf9901e0e2786eef9e107b174c3f9a869650cf]
	... 10 common frames omitted

**Comment by lorban** [comment]
The problem lies in the `OffHeapServerStore`: `append`, `getAndAppend` and `replaceAtHead` all consume the `ByteBuffer`'s bytes when delegating to the segment, but if the segment fails with `OversizeMappingException` then the operation is re-tried with the same buffer... and all its bytes already consumed.
