### ISSUE TITLE
Exception when destroying clustered ehcache manager

### ISSUE THREAD

**Issue by esebasti** [ehcache/ehcache3#1382]
It is observed sporadically in both local environment and jenkins job. It seems read lock held by cache manager entity is not released explicitly from client when closing cache manager. Instead, the lock is released through entity disconnected event triggered by closing connection. This can cause race condition with subsequent write lock needed by destroy. 

Caused by: java.lang.IllegalStateException: Couldn't acquire cluster-wide maintenance lease
	at org.ehcache.clustered.client.internal.service.DefaultClusteringService.startForMaintenance(DefaultClusteringService.java:220)
	at org.ehcache.core.EhcacheManager.startMaintainableServices(EhcacheManager.java:694)
	at org.ehcache.core.EhcacheManager.destroy(EhcacheManager.java:674)

**Comment by ljacomet** [comment]
I am going to mark this one as blocked and dependent on having the changes based on terracotta-oss/terracotta-apis#130 be made available.

**Comment by ljacomet** [comment]
Unblocked

**Comment by ljacomet** [comment]
@esebasti Can you confirm this is still a problem?

**Comment by esebasti** [comment]
It was probably taken care as I don't see this problem anymore with recent builds.

**Comment by ljacomet** [comment]
Closing as not reproducible
