### ISSUE TITLE
Ehcache jars create component scan errors in Tomcat because of Class-Path manifest entry

### ISSUE THREAD

**Issue by mathieucarbou** [ehcache/ehcache3#1467]
Tomcat is scanning jar files (like some containers do to support some types of jars such as web jars).

It logically also goes through the `Class-Path` manifest entry.

The scanning crashes because Tomcat cannot find the SLF4J jar near the ehcache jars.

This is a valid use case, because in this case, tomcat is used as an embedded container, started from a maven project. It is exactly the same as if we were using an app in heroku, cloudfoundry, etc where the web application is no more a traditional war deployed within a container in an isolated classloader.

But anyway... The question is much more... __What is the valid requirement for Ehcache jar and Ehcache clustered jar to have this `Class-Path` entry in the manifest ?__ 

Normal libraries to not declare their dependencies in a `Class-Path` section that could be eventually scanned or used in a way we do not want: ehcache being a library, I think it should not force people to have the slf4j jar in the same place as the ehcache jars.

```
Sep 27, 2016 3:07:07 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8081"]
Sep 27, 2016 3:07:07 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Sep 27, 2016 3:07:07 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Sep 27, 2016 3:07:07 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.5.5
Sep 27, 2016 3:07:07 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Sep 27, 2016 3:07:07 PM org.apache.tomcat.util.scan.StandardJarScanner scan
WARNING: Failed to scan [file:/Users/matc/.m2/repository/org/ehcache/ehcache-clustered/3.2.0-SNAPSHOT/slf4j-api-1.7.7.jar] from classloader hierarchy
java.io.FileNotFoundException: /Users/matc/.m2/repository/org/ehcache/ehcache-clustered/3.2.0-SNAPSHOT/slf4j-api-1.7.7.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at org.apache.tomcat.util.scan.JarFileUrlJar.<init>(JarFileUrlJar.java:60)
	at org.apache.tomcat.util.scan.JarFactory.newInstance(JarFactory.java:43)
	at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:327)
	at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:277)
	at org.apache.catalina.startup.ContextConfig.processJarsForWebFragments(ContextConfig.java:1898)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1126)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:775)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5087)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1403)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ljacomet** [comment]
Closed by #1472
