### ISSUE TITLE
Memory from Offheap tier is not reclaimed after a cachemanager.close()

### ISSUE THREAD

**Issue by aurbroszniowski** [ehcache/ehcache3#1477]
Tested on Ehcache 3.1.2 and 3.2.0-SNAPSHOT

Running this code :

```

import org.ehcache.Cache;
import org.ehcache.CacheManager;
import org.ehcache.config.builders.CacheManagerBuilder;
import org.ehcache.config.units.EntryUnit;
import org.testng.annotations.Test;

import static org.ehcache.config.builders.CacheConfigurationBuilder.newCacheConfigurationBuilder;
import static org.ehcache.config.builders.CacheManagerBuilder.newCacheManagerBuilder;
import static org.ehcache.config.builders.ResourcePoolsBuilder.newResourcePoolsBuilder;
import static org.ehcache.config.units.MemoryUnit.MB;

public class OffheapAllocation {

  @Test
  public void testPool() {

    for (int i = 0; i < 10; i++) {
      CacheManagerBuilder cacheManagerBuilder = newCacheManagerBuilder();
      CacheManager cacheManager = cacheManagerBuilder
          .withCache("cache", newCacheConfigurationBuilder(Long.class, byte[].class, newResourcePoolsBuilder()
              .heap(1, EntryUnit.ENTRIES)
              .offheap(2000, MB)
              ).build())
          .build(true);

      Cache<Long, byte[]> cache = cacheManager.getCache("cache", Long.class, byte[].class);
      cache.put(1L, new byte[1000]);
      cacheManager.close();
    }
  }

}
```

Will cause an OutOfMemory error.
First iteration in the loop will allocate around 2GB of Offheap but on subsequent iterations, the memory will lower down until there is not enough anymore to allocate Offheap and then throw the following exception:

```
1820 [main] WARN  o.t.o.p.UpfrontAllocatingPageSource - Attempting to allocate 2.4GB of offheap when there is only 776.4MB of free physical memory - some paging will therefore occur.
1820 [main] DEBUG o.t.o.p.UpfrontAllocatingPageSource - Allocating 2.4GB in chunks
2843 [main] DEBUG o.t.o.b.OffHeapBufferSource - Failed to allocate 1073741824 byte offheap buffer
java.lang.OutOfMemoryError: Direct buffer memory
    at java.nio.Bits.reserveMemory(Bits.java:658)
    at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
    at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
    at org.terracotta.offheapstore.buffersource.OffHeapBufferSource.allocateBuffer(OffHeapBufferSource.java:36)
    at org.terracotta.offheapstore.buffersource.TimingBufferSource.allocateBuffer(TimingBufferSource.java:45)
    at org.terracotta.offheapstore.paging.UpfrontAllocatingPageSource.allocateBackingBuffers(UpfrontAllocatingPageSource.java:464)
    at org.terracotta.offheapstore.paging.UpfrontAllocatingPageSource.<init>(UpfrontAllocatingPageSource.java:136)
    at org.terracotta.offheapstore.paging.UpfrontAllocatingPageSource.<init>(UpfrontAllocatingPageSource.java:119)
    at org.ehcache.impl.internal.store.offheap.OffHeapStore.createBackingMap(OffHeapStore.java:94)
    at org.ehcache.impl.internal.store.offheap.OffHeapStore.access$500(OffHeapStore.java:65)
    at org.ehcache.impl.internal.store.offheap.OffHeapStore$Provider.init(OffHeapStore.java:186)
    at org.ehcache.impl.internal.store.offheap.OffHeapStore$Provider.initStore(OffHeapStore.java:182)
    at org.ehcache.impl.internal.store.offheap.OffHeapStore$Provider.initAuthoritativeTier(OffHeapStore.java:212)
    at org.ehcache.impl.internal.store.tiering.TieredStore$Provider.initStore(TieredStore.java:505)
    at org.ehcache.core.EhcacheManager$8.init(EhcacheManager.java:496)
    at org.ehcache.core.StatusTransitioner.runInitHooks(StatusTransitioner.java:135)
    at org.ehcache.core.StatusTransitioner.access$000(StatusTransitioner.java:33)
    at org.ehcache.core.StatusTransitioner$Transition.succeeded(StatusTransitioner.java:194)
    at org.ehcache.core.Ehcache.init(Ehcache.java:582)
    at org.ehcache.core.EhcacheManager.createCache(EhcacheManager.java:258)
    at org.ehcache.core.EhcacheManager.init(EhcacheManager.java:564)
    at org.ehcache.config.builders.CacheManagerBuilder.build(CacheManagerBuilder.java:72)
```

**Comment by cljohnso** [comment]
Release of off-heap memory is not under direct control of the CacheManager (_or any other Java code sticking to published APIs_) -- it's ultimately released when the JVM's garbage collector gets around to noticing there are no live references to the off-heap storage.  Absent **heap** memory pressure, this can take a while and can lead to off-heap allocation failures when you're repeatedly allocating and releasing off-heap storage.

You can run something like the following within your test loop to _encourage_ GC to get rid of the no longer needed off-heap allocation:

```
    Runtime runtime = Runtime.getRuntime();
    for (int i = 0; i < 10; i++) {
      runtime.gc();
      runtime.runFinalization();
      Thread.yield();
    }
```

**Comment by aurbroszniowski** [comment]
just to add some context : the included test is not a use case but just to reproduce what we encountered when having a couple of cachemanagers with large offheap allocation, which resulted in the OOME. If this is a known and accepted case then it would be great to document it, thanks.

**Comment by henri-tremblay** [comment]
Just tried on a 1.8.0_102 and no problem whatsoever. Using `-Xmx4G -XX:MaxDirectMemorySize=3221225472`

I agree with @cljohnso 's answer but was looking for a magic trick.

@aurbroszniowski  Which environment are you on?

**Comment by henri-tremblay** [comment]
Could be related to #1328

**Comment by henri-tremblay** [comment]
I just retried now that #1328 is closed.

I can't reproduce this issue exactly. I tried multiple JVM. The Hotspot behaviour is to trigger a full GC when going out of offheap memory. This will free some space. So it is slow but it never goes in OOME. You might have used a buggy JVM.

However, I still see a memory leak, albeit a slow one, in PassThroughStatistic. So I will address it.
