### ISSUE TITLE
BasicClusteredCacheCRUDReplicationTest freezes during build

### ISSUE THREAD

**Issue by henri-tremblay** [ehcache/ehcache3#1526]
It happens to me once in a while.

The gradle build freezes.

The stacktrace looks like that (the full stack is in attachment):

	"Test worker" #12 prio=5 os_prio=31 tid=0x00007fc3eb879000 nid=0x5703 in Object.wait() [0x000070000a2a4000]
	   java.lang.Thread.State: TIMED_WAITING (on object monitor)
		at java.lang.Object.wait(Native Method)
		at java.lang.Object.wait(Object.java:460)
		at com.tc.object.InFlightMessage.getWithTimeout(InFlightMessage.java:170)
		- locked <0x00000007ab8254c0> (a com.tc.object.InFlightMessage)
		at com.tc.object.InFlightMessage.getWithTimeout(InFlightMessage.java:42)
		at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl$1.getWithTimeout(EntityClientEndpointImpl.java:174)
		at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl$1.getWithTimeout(EntityClientEndpointImpl.java:156)
		at org.ehcache.clustered.client.internal.EhcacheClientEntity.waitFor(EhcacheClientEntity.java:312)
		at org.ehcache.clustered.client.internal.EhcacheClientEntity.invokeInternal(EhcacheClientEntity.java:275)
		at org.ehcache.clustered.client.internal.EhcacheClientEntity.invoke(EhcacheClientEntity.java:266)
		at org.ehcache.clustered.client.internal.store.NoInvalidationServerStoreProxy.getAndAppend(NoInvalidationServerStoreProxy.java:88)
		at org.ehcache.clustered.client.internal.store.StrongServerStoreProxy$8.apply(StrongServerStoreProxy.java:303)
		at org.ehcache.clustered.client.internal.store.StrongServerStoreProxy$8.apply(StrongServerStoreProxy.java:300)
		at org.ehcache.clustered.client.internal.store.StrongServerStoreProxy.performWaitingForHashInvalidation(StrongServerStoreProxy.java:190)
		at org.ehcache.clustered.client.internal.store.StrongServerStoreProxy.getAndAppend(StrongServerStoreProxy.java:300)
		at org.ehcache.clustered.client.internal.store.ClusteredStore.putIfAbsent(ClusteredStore.java:262)
		at org.ehcache.impl.internal.store.tiering.TieredStore.putIfAbsent(TieredStore.java:148)
		at org.ehcache.core.Ehcache.putIfAbsent(Ehcache.java:455)
		at org.ehcache.clustered.replication.BasicClusteredCacheCRUDReplicationTest.testCAS(BasicClusteredCacheCRUDReplicationTest.java:174)

[stack.txt](https://github.com/ehcache/ehcache3/files/522483/stack.txt)

**Comment by henri-tremblay** [comment]
I think it is still possible to freeze the build for other reasons but I'll reopen an issue when it happens. This one was caused by a `validateCache` called after a `createCache` by a client. It was crashing the server (see Terracotta-OSS/terracotta-core#320) and so the client was trying to reconnect forever (that should probably be fixed as well)
