### ISSUE TITLE
Demo 01-CacheAside throws an exception at startup

### ISSUE THREAD

**Issue by henri-tremblay** [ehcache/ehcache3#1534]
We get the following exception:

	org.ehcache.spi.serialization.UnsupportedTypeException: No serializer found for type 'java.util.List'
	        at org.ehcache.impl.internal.spi.serialization.DefaultSerializationProvider.getSerializerClassFor(DefaultSerializationProvider.java:137) ~[main/:na]
	        at org.ehcache.impl.internal.spi.serialization.DefaultSerializationProvider.createSerializer(DefaultSerializationProvider.java:99) ~[main/:na]
	        at org.ehcache.impl.internal.spi.serialization.DefaultSerializationProvider.createValueSerializer(DefaultSerializationProvider.java:91) ~[main/:na]
	        at org.ehcache.config.builders.UserManagedCacheBuilder.build(UserManagedCacheBuilder.java:256) [main/:na]
	        at org.ehcache.config.builders.UserManagedCacheBuilder.build(UserManagedCacheBuilder.java:390) [main/:na]
	        at org.ehcache.demos.peeper.DataCache.setupCache(DataCache.java:35) [main/:na]
	        at org.ehcache.demos.peeper.DataStore.init(DataStore.java:44) [main/:na]
	        at org.ehcache.demos.peeper.PeeperServletContextListener.contextInitialized(PeeperServletContextListener.java:31) [main/:na]

**Comment by henri-tremblay** [comment]
You are right. I think we should at least change the message to something nicer that explains why it is still fine. And probably remove the debug level.

What happens when no serializer is found? We rely on the inferface implementation to be  serializable?

**Comment by henri-tremblay** [comment]
PR #1553 to have a nicer message and Issue #1554 to remove the search for a serializer.
