### ISSUE TITLE
NPE during replication

### ISSUE THREAD

**Issue by esebasti** [ehcache/ehcache3#1590]
Passive entity throws & logs this NPE for every message it applies.

java.lang.NullPointerException
at org.ehcache.clustered.server.EhcachePassiveEntity.untrackHashInvalidationForEventualCache(EhcachePassiveEntity.java:152)
at org.ehcache.clustered.server.EhcachePassiveEntity.invokeRetirementMessages(EhcachePassiveEntity.java:138)
at org.ehcache.clustered.server.EhcachePassiveEntity.invoke(EhcachePassiveEntity.java:92)
at org.ehcache.clustered.server.EhcachePassiveEntity.invoke(EhcachePassiveEntity.java:60)
at com.tc.objectserver.entity.ManagedEntityImpl.performAction(ManagedEntityImpl.java:636)
at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:380)
at com.tc.objectserver.entity.ManagedEntityImpl.lambda$processInvokeRequest$62(ManagedEntityImpl.java:238)
at com.tc.objectserver.entity.ManagedEntityImpl$SchedulingRunnable.run(ManagedEntityImpl.java:911)
at com.tc.objectserver.entity.RequestProcessor$EntityRequest.invoke(RequestProcessor.java:153)
at com.tc.objectserver.entity.RequestProcessor$EntityRequest.run(RequestProcessor.java:145)
at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:27)
at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:23)
at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502)
at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197)

**Comment by albinsuresh** [comment]
Just to add to that, this behavior is seen only with eventual caches when a passive is brought up while mutative cache operations are in progress (mix up replication and sync).

**Comment by AbfrmBlr** [comment]
This is die to the fact that no invalidation tracking is being done for eventual caches during creation while sync. Please see this PR for reference https://github.com/ehcache/ehcache3/pull/1588.
