### ISSUE TITLE
NPE when active restarted immediately

### ISSUE THREAD

**Issue by kedar031** [ehcache/ehcache3#1591]
When active is restarted immediately while the Ehcache client is doing mutations, below exception is noticed

````
[WorkerThread(request_processor_stage, 2, 8)] ERROR org.ehcache.clustered.server.EhcachePassiveEntity - Unexpected exception raised during operation: REPLICATION_OP
java.lang.NullPointerException
	at org.ehcache.clustered.server.state.ClientMessageTracker.applied(ClientMessageTracker.java:41)
	at org.ehcache.clustered.server.EhcachePassiveEntity.invokeRetirementMessages(EhcachePassiveEntity.java:130)
	at org.ehcache.clustered.server.EhcachePassiveEntity.invoke(EhcachePassiveEntity.java:92)
	at org.ehcache.clustered.server.EhcachePassiveEntity.invoke(EhcachePassiveEntity.java:60)
	at com.tc.objectserver.entity.ManagedEntityImpl.performAction(ManagedEntityImpl.java:636)
	at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:380)
	at com.tc.objectserver.entity.ManagedEntityImpl.lambda$processInvokeRequest$62(ManagedEntityImpl.java:238)
	at com.tc.objectserver.entity.ManagedEntityImpl$SchedulingRunnable.run(ManagedEntityImpl.java:911)
	at com.tc.objectserver.entity.RequestProcessor$EntityRequest.invoke(RequestProcessor.java:153)
	at com.tc.objectserver.entity.RequestProcessor$EntityRequest.run(RequestProcessor.java:145)
	at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:27)
	at com.tc[WorkerThread(request_processor_stage, 5, 8)] INFO org.ehcache.clustered.server.EhcacheActiveEntity - Disconnecting ClientDescriptorImpl{nodeID=ClientID[0], entityDescriptor=com.tc.object.EntityDescriptor@9bd4bd7e}
````

**Comment by AbfrmBlr** [comment]
Stack trace is confusing. It has both 'EhcacheActiveEntity' & 'EhcachePassiveEntity' in same stack trace.

**Comment by AbfrmBlr** [comment]
Had a chat with @kedar031, the problem of log is just due to log outout so ignoring that.

**Comment by AbfrmBlr** [comment]
This exception is coming due to the fact that a passive sync starts, even before client-reconnect window is closed on a newly promoted Active. Since the state is not reconstructed fully on active reason being ongoing re-connection, the passive sync fails to fully sync the state.

**Comment by kedar031** [comment]
tested this and reported exception does not occur anymore.
