### ISSUE TITLE
One of the Ehcache client waits until other completes

### ISSUE THREAD

**Issue by kedar031** [ehcache/ehcache3#1593]
In Strong consistency mode, one of the Ehcache client hangs until the other completes during mutations (seen with put,putIfAbsent and replace operations so far)
Waiting client continues once other client is completed.

1. Start  Active and Passive servers
2. Start two clients in strong consistency mode doing mutation (issue seen with put/replace<K,V>/putIfAbsent operations so far)

````
PersistentCacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
        .with(ClusteringServiceConfigurationBuilder.cluster(CLUSTER_URI)
            .autoCreate()
            .defaultServerResource("primary-server-resource")
            .resourcePool("resource-pool-a", 128, MemoryUnit.KB)
            .resourcePool("resource-pool-b", 128, MemoryUnit.KB, "secondary-server-resource"))
        .withCache("clustered-cache1", CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, String.class,
            ResourcePoolsBuilder.newResourcePoolsBuilder()
                .with(ClusteredResourcePoolBuilder.clusteredDedicated("primary-server-resource", 256, MemoryUnit.MB)))
            .add(new ClusteredStoreConfiguration(Consistency.STRONG))).build(true);


    Cache cache1 = cacheManager.getCache("clustered-cache1", Long.class, String.class);


    for (long i = 0; i < 20000; i++) {
      cache1.put(i, "hello" + i);
    }
````

One of the client waits until other completes (continues after other client is done), stack trace as below

````

"main" #1 prio=5 os_prio=0 tid=0x00000000021bd000 nid=0x3428 waiting on condition [0x00000000023fc000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076f2e5f40> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at org.ehcache.clustered.client.internal.store.StrongServerStoreProxy.awaitOnLatch(StrongServerStoreProxy.java:260)
	at org.ehcache.clustered.client.internal.store.StrongServerStoreProxy.performWaitingForHashInvalidation(StrongServerStoreProxy.java:200)
	at org.ehcache.clustered.client.internal.store.StrongServerStoreProxy.getAndAppend(StrongServerStoreProxy.java:309)
	at org.ehcache.clustered.client.internal.store.ClusteredStore.replace(ClusteredStore.java:347)
	at org.ehcache.core.Ehcache.replace(Ehcache.java:520)
	at com.terracotta.qa.ehcache.ApCrudTest.testCrudOperations(ApCrudTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.jboss.byteman.contrib.bmunit.BMNGAbstractRunner.run(BMNGAbstractRunner.java:58)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:689)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

````

**Comment by ljacomet** [comment]
Had a chat with @albinsuresh on this last week. The issue comes from a window during which the new client is known server side and thus notified of invalidations, but on the client side the message listeners are not registered yet.

The fix is to properly lifecycle the server store proxy by creating it before registration of the client, including the listeners registration.
And while looking at the code we noticed that no de-registration ever takes place. Which is a potential leak that needs fixing as well.
