### ISSUE TITLE
 RELEASE_SERVER_STORE error when destroying a clustered cache after the terracotta servers are shutdown

### ISSUE THREAD

**Issue by aurbroszniowski** [ehcache/ehcache3#1661]
Using the latest 3.2.-SNAPSHOT kit.
Terracotta 5.0.12-beta, as of 2016-11-22 at 10:10:13 PST (Revision 27f937f710eede1ce8f0071d85c6a822483ea387 from UNKNOWN)

I have an AP stripe, with transitions between Active and Passive after consecutive shutdown/startups.

Eventually I shutdown servers, and after this, the clustered cache are destroyed :
```
PersistentCacheManager persistentCacheManager = (PersistentCacheManager)cacheManager;
persistentCacheManager.destroyCache(alias);
```

I get then the following exception:
```
org.ehcache.StateTransitionException: RELEASE_SERVER_STORE error: com.tc.object.ExceptionUtils$1: Entity: org.ehcache.clustered.client.internal.EhcacheClientEntity:org.ehcache.clustered.client.internal.EhcacheClientEntity connection closed
	at org.ehcache.core.StatusTransitioner$Transition.succeeded(StatusTransitioner.java:209)
	at org.ehcache.core.Ehcache.close(Ehcache.java:596)
	at org.ehcache.core.EhcacheManager.removeAndCloseWithoutNotice(EhcacheManager.java:649)
	at org.ehcache.core.EhcacheManager.destroyCache(EhcacheManager.java:683)
	at com.terracotta.qa.ehcache.configuration.ClusteredProvider.terminate(ClusteredProvider.java:75)
	at com.terracotta.qa.framework.CacheConfigurationsProvider.release(CacheConfigurationsProvider.java:93)
	at com.terracotta.qa.framework.BaseTest.singleThreadedTest(BaseTest.java:239)
	at com.terracotta.qa.framework.BaseTest.singleThreadedTest(BaseTest.java:183)
	at com.terracotta.qa.ehcache.load.AbstractHaCrudTest.basicTest(AbstractHaCrudTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.jboss.byteman.contrib.bmunit.BMNGAbstractRunner.run(BMNGAbstractRunner.java:58)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:689)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
Caused by: java.lang.RuntimeException: RELEASE_SERVER_STORE error: com.tc.object.ExceptionUtils$1: Entity: org.ehcache.clustered.client.internal.EhcacheClientEntity:org.ehcache.clustered.client.internal.EhcacheClientEntity connection closed
	at org.ehcache.clustered.client.internal.EhcacheClientEntity.invokeInternal(EhcacheClientEntity.java:327)
	at org.ehcache.clustered.client.internal.EhcacheClientEntity.releaseCache(EhcacheClientEntity.java:274)
	at org.ehcache.clustered.client.internal.service.DefaultClusteringService.releaseServerStoreProxy(DefaultClusteringService.java:425)
	at org.ehcache.clustered.client.internal.store.ClusteredStore$Provider.releaseStore(ClusteredStore.java:638)
	at org.ehcache.core.EhcacheManager$8.close(EhcacheManager.java:504)
	at org.ehcache.core.StatusTransitioner.runCloseHooks(StatusTransitioner.java:158)
	at org.ehcache.core.StatusTransitioner.access$200(StatusTransitioner.java:33)
	at org.ehcache.core.StatusTransitioner$Transition.succeeded(StatusTransitioner.java:198)
	... 34 more
Caused by: com.tc.object.ExceptionUtils$1: Entity: org.ehcache.clustered.client.internal.EhcacheClientEntity:org.ehcache.clustered.client.internal.EhcacheClientEntity connection closed
	at com.tc.object.InFlightMessage.getWithTimeout(InFlightMessage.java:177)
	at com.tc.object.InFlightMessage.getWithTimeout(InFlightMessage.java:42)
	at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl$1.getWithTimeout(EntityClientEndpointImpl.java:174)
	at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl$1.getWithTimeout(EntityClientEndpointImpl.java:156)
	at org.ehcache.clustered.client.internal.EhcacheClientEntity.waitFor(EhcacheClientEntity.java:356)
	at org.ehcache.clustered.client.internal.EhcacheClientEntity.invokeInternal(EhcacheClientEntity.java:320)
	... 41 more
Caused by: com.tc.object.ClientEntityManagerImpl$3: Entity: org.ehcache.clustered.client.internal.EhcacheClientEntity:load-tests connection closed
	at com.tc.object.ClientEntityManagerImpl.throwClosedExceptionOnMessage(ClientEntityManagerImpl.java:397)
	at com.tc.object.ClientEntityManagerImpl.access$400(ClientEntityManagerImpl.java:74)
	at com.tc.object.ClientEntityManagerImpl$1.handleEvent(ClientEntityManagerImpl.java:132)
	at com.tc.object.ClientEntityManagerImpl$1.handleEvent(ClientEntityManagerImpl.java:106)
	at com.tc.object.ClientEntityManagerImpl$2.addSingleThreaded(ClientEntityManagerImpl.java:147)
	at com.tc.object.ClientEntityManagerImpl.createInFlightMessageAfterAcks(ClientEntityManagerImpl.java:507)
	at com.tc.object.ClientEntityManagerImpl.invokeAction(ClientEntityManagerImpl.java:267)
	at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl.invoke(EntityClientEndpointImpl.java:155)
	at org.ehcache.clustered.client.internal.EhcacheClientEntity.invokeAsync(EhcacheClientEntity.java:345)
	... 42 more
Caused by: org.terracotta.connection.ConnectionException
```

See attached console log which includes the exception

[output.txt](https://github.com/ehcache/ehcache3/files/618648/output.txt)

**Comment by ljacomet** [comment]
The exception is expected as we cannot destroy caches from a `PersistentCacheManager` that is clustered.

I am guessing you would want the top message to better indicate why? If not, can you clarify what different behaviour you would expect.

**Comment by aurbroszniowski** [comment]
I guess that the javadoc must be updated because currently the contract is not valid since it indicates that the destroy() method will destroy all persistent data associated to the cache manager, without specifying any particular behavior regarding clustering. (sounds minor but a user moving from standalone caches to clustered caches will need to change his code if he uses this method).
