### ISSUE TITLE
Destroying a non-existing clustered cache will prevent exiting main

### ISSUE THREAD

**Issue by henri-tremblay** [ehcache/ehcache3#1679]
Run twice the following code (having a TC server running in localhost)

```java
  public static void main(String[] args) throws Exception {
    final URI clusterURI = URI.create("terracotta://localhost:9510/cachemanager");
    CacheManagerBuilder<PersistentCacheManager> cacheManagerBuilder =
        CacheManagerBuilder.newCacheManagerBuilder()
            .with(ClusteringServiceConfigurationBuilder.cluster(clusterURI)
                .autoCreate().defaultServerResource("primary-server-resource"));
    EhcacheManager cacheManager = (EhcacheManager) cacheManagerBuilder.build();
    cacheManager.destroy();
  }
```

The second time you will get an exception (as expected)

     Caused by: org.terracotta.exception.EntityNotFoundException: Entity: org.ehcache.clustered.client.internal.EhcacheClientEntity:cachemanager not found

And then main will never exit. This doesn't happen if the entity does exist. So some cleanup doesn't occur in case of error.

Here is the stack dump:

    "Out of band notifier - Main" #25 daemon prio=5 os_prio=31 tid=0x00007fe187155800 nid=0x7107 waiting on condition [0x000070000b0a5000]
	   java.lang.Thread.State: WAITING (parking)
		at sun.misc.Unsafe.park(Native Method)
		- parking to wait for  <0x000000076c35a940> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
		at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
		at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
		at com.tc.cluster.ClusterImpl$OutOfBandNotifier$1.run(ClusterImpl.java:417)
		at java.lang.Thread.run(Thread.java:745)

	"WorkerThread(multi_request_ack_stage, 0)" #23 daemon prio=5 os_prio=31 tid=0x00007fe18a937000 nid=0x6f03 waiting on condition [0x000070000afa2000]
	   java.lang.Thread.State: TIMED_WAITING (parking)
		at sun.misc.Unsafe.park(Native Method)
		- parking to wait for  <0x000000076cee82c0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
		at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
		at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
		at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
		at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

	"WorkerThread(cluster_membership_event_stage, 0)" #22 daemon prio=5 os_prio=31 tid=0x00007fe18a936800 nid=0x6d03 waiting on condition [0x000070000ae9f000]
	   java.lang.Thread.State: TIMED_WAITING (parking)
		at sun.misc.Unsafe.park(Native Method)
		- parking to wait for  <0x000000076cfbd138> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
		at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
		at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
		at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
		at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

	"WorkerThread(server_entity_message_stage, 0)" #21 daemon prio=5 os_prio=31 tid=0x00007fe18a935800 nid=0x6b03 waiting on condition [0x000070000ad9c000]
	   java.lang.Thread.State: TIMED_WAITING (parking)
		at sun.misc.Unsafe.park(Native Method)
		- parking to wait for  <0x000000076cef24b8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
		at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
		at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
		at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
		at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

	"WorkerThread(request_ack_stage, 0)" #20 daemon prio=5 os_prio=31 tid=0x00007fe18a935000 nid=0x6903 waiting on condition [0x000070000ac99000]
	   java.lang.Thread.State: TIMED_WAITING (parking)
		at sun.misc.Unsafe.park(Native Method)
		- parking to wait for  <0x000000076cee6650> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
		at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
		at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
		at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
		at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

	"WorkerThread(hydrate_message_stage, 0)" #19 daemon prio=5 os_prio=31 tid=0x00007fe18805c000 nid=0x6703 waiting on condition [0x000070000ab96000]
	   java.lang.Thread.State: TIMED_WAITING (parking)
		at sun.misc.Unsafe.park(Native Method)
		- parking to wait for  <0x000000076cfa43e8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
		at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
		at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
		at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
		at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

	"WorkerThread(client_coordination_stage, 0)" #18 daemon prio=5 os_prio=31 tid=0x00007fe1880dd800 nid=0x6503 waiting on condition [0x000070000aa93000]
	   java.lang.Thread.State: TIMED_WAITING (parking)
		at sun.misc.Unsafe.park(Native Method)
		- parking to wait for  <0x000000076cfb3620> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
		at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
		at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
		at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
		at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

	"WorkerThread(cluster_events_stage, 0)" #17 daemon prio=5 os_prio=31 tid=0x00007fe187925000 nid=0x6303 waiting on condition [0x000070000a990000]
	   java.lang.Thread.State: TIMED_WAITING (parking)
		at sun.misc.Unsafe.park(Native Method)
		- parking to wait for  <0x000000076cd10a98> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
		at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
		at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
		at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
		at com.tc.async.impl.StageQueueImpl$SourceQueueImpl.poll(StageQueueImpl.java:353)
		at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:194)

	"TC Memory Monitor" #16 prio=5 os_prio=31 tid=0x00007fe18a0bc800 nid=0x6103 waiting on condition [0x000070000a88d000]
	   java.lang.Thread.State: TIMED_WAITING (sleeping)
		at java.lang.Thread.sleep(Native Method)
		at com.tc.runtime.TCMemoryManagerImpl$MemoryMonitor.run(TCMemoryManagerImpl.java:140)

	"HealthChecker" #15 daemon prio=5 os_prio=31 tid=0x00007fe18790c800 nid=0x5f03 in Object.wait() [0x000070000a78a000]
	   java.lang.Thread.State: TIMED_WAITING (on object monitor)
		at java.lang.Object.wait(Native Method)
		- waiting on <0x000000076c8bb750> (a com.tc.util.concurrent.SetOnceFlag)
		at com.tc.net.protocol.transport.ConnectionHealthCheckerImpl$HealthCheckerMonitorThreadEngine.run(ConnectionHealthCheckerImpl.java:247)
		- locked <0x000000076c8bb750> (a com.tc.util.concurrent.SetOnceFlag)
		at java.lang.Thread.run(Thread.java:745)

	"L1_L2:TCComm Main Selector Thread_W (listen 0:0:0:0:0:0:0:0:49467)" #14 daemon prio=5 os_prio=31 tid=0x00007fe187923000 nid=0x5d03 runnable [0x000070000a687000]
	   java.lang.Thread.State: RUNNABLE
		at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
		at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
		at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
		at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
		- locked <0x000000076c894358> (a sun.nio.ch.Util$3)
		- locked <0x000000076c894348> (a java.util.Collections$UnmodifiableSet)
		- locked <0x000000076c894228> (a sun.nio.ch.KQueueSelectorImpl)
		at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
		at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
		at com.tc.net.core.CoreNIOServices$CommThread.selectLoop(CoreNIOServices.java:566)
		at com.tc.net.core.CoreNIOServices$CommThread.run(CoreNIOServices.java:310)

	"L1_L2:TCComm Main Selector Thread_R (listen 0:0:0:0:0:0:0:0:49467)" #13 daemon prio=5 os_prio=31 tid=0x00007fe187919000 nid=0x5b03 runnable [0x000070000a584000]
	   java.lang.Thread.State: RUNNABLE
		at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
		at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
		at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
		at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
		- locked <0x000000076c8807e8> (a sun.nio.ch.Util$3)
		- locked <0x000000076c880760> (a java.util.Collections$UnmodifiableSet)
		- locked <0x000000076c87ecf8> (a sun.nio.ch.KQueueSelectorImpl)
		at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
		at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
		at com.tc.net.core.CoreNIOServices$CommThread.selectLoop(CoreNIOServices.java:566)
		at com.tc.net.core.CoreNIOServices$CommThread.run(CoreNIOServices.java:310)

	"SampledCounterManager Timer" #12 daemon prio=5 os_prio=31 tid=0x00007fe18791d800 nid=0x5903 in Object.wait() [0x000070000a481000]
	   java.lang.Thread.State: TIMED_WAITING (on object monitor)
		at java.lang.Object.wait(Native Method)
		- waiting on <0x000000076c558428> (a java.util.TaskQueue)
		at java.util.TimerThread.mainLoop(Timer.java:552)
		- locked <0x000000076c558428> (a java.util.TaskQueue)
		at java.util.TimerThread.run(Timer.java:505)

**Comment by chrisdennis** [comment]
The underlying client code has shifted quite a bit since this was filed. This may still be a bug, but the symptoms are almost certainly different. We should validate how it currently behaves.
