### ISSUE TITLE
NPE in ExceptionCodec.

### ISSUE THREAD

**Issue by esebasti** [ehcache/ehcache3#1698]
Here is the full stack trace.

java.lang.NullPointerException
org.ehcache.clustered.common.internal.messages.ExceptionCodec.decode(ExceptionCodec.java:78)
org.ehcache.clustered.common.internal.messages.ResponseCodec.decode(ResponseCodec.java:201)
org.ehcache.clustered.common.internal.messages.EhcacheCodec.decodeResponse(EhcacheCodec.java:117)
org.ehcache.clustered.common.internal.messages.EhcacheCodec.decodeResponse(EhcacheCodec.java:37)
at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl$1.getWithTimeout(EntityClientEndpointImpl.java:174)
at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl$1.getWithTimeout(EntityClientEndpointImpl.java:156)
at org.ehcache.clustered.client.internal.EhcacheClientEntity.waitFor(EhcacheClientEntity.java:356)
at org.ehcache.clustered.client.internal.EhcacheClientEntity.invokeInternal(EhcacheClientEntity.java:320)
at org.ehcache.clustered.client.internal.EhcacheClientEntity.configure(EhcacheClientEntity.java:246)
at org.ehcache.clustered.client.internal.EhcacheClientEntityFactory.create(EhcacheClientEntityFactory.java:116)
at org.ehcache.clustered.client.internal.service.DefaultClusteringService.autoCreateEntity(DefaultClusteringService.java:196)
at org.ehcache.clustered.client.internal.service.DefaultClusteringService.start(DefaultClusteringService.java:144)
at org.ehcache.core.internal.service.ServiceLocator.startAllServices(ServiceLocator.java:118)
at org.ehcache.core.EhcacheManager.init(EhcacheManager.java:560)
... 28 more

**Comment by ljacomet** [comment]
@esebasti Can you give the context in which you had this problem? There is effectively a missing null check in decode, but I am curious to understand what caused an exception to leave the server without a stack trace.

**Comment by ljacomet** [comment]
Well, from looking deeper at the code, that exception makes no sense. So really interested in understanding under which conditions you saw that!

**Comment by esebasti** [comment]
I saw that during load test in one of big memory machines which seems failing due to invalid offheap resource configurations. Trying to gather more details on it.

**Comment by esebasti** [comment]
It looks like I was running new client against old kit. Closing it.
