### ISSUE TITLE
BasicClusteredCacheOpsReplicationWithMultipleClientsTest randomly fails

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#1782]
`testBulkOps` sometimes fails at random, with such failure:

```
java.lang.AssertionError: 
Expected: not null
     but: was null
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.ehcache.clustered.replication.BasicClusteredCacheOpsReplicationWithMultipleClientsTest.lambda$testBulkOps$8(BasicClusteredCacheOpsReplicationWithMultipleClientsTest.java:186)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.ehcache.clustered.replication.BasicClusteredCacheOpsReplicationWithMultipleClientsTest.testBulkOps(BasicClusteredCacheOpsReplicationWithMultipleClientsTest.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

When it does fail, this stack trace gets logged:

```
2017-01-11 05:39:02.743 [Time-limited test] WARN class.com.tc.net.protocol.tcm.TCMessageImpl - message not sent
java.io.IOException: connection not established
	at com.tc.net.protocol.transport.MessageTransportBase.send(MessageTransportBase.java:185)
	at com.tc.net.protocol.tcm.AbstractMessageChannel.send(AbstractMessageChannel.java:206)
	at com.tc.net.protocol.tcm.ClientMessageChannelImpl.send(ClientMessageChannelImpl.java:167)
	at com.tc.net.protocol.tcm.TCMessageImpl.basicSend(TCMessageImpl.java:399)
	at com.tc.net.protocol.tcm.TCMessageImpl.send(TCMessageImpl.java:385)
	at com.tc.object.InFlightMessage.send(InFlightMessage.java:87)
	at com.tc.object.ClientEntityManagerImpl$1.handleEvent(ClientEntityManagerImpl.java:135)
	at com.tc.object.ClientEntityManagerImpl$1.handleEvent(ClientEntityManagerImpl.java:121)
	at com.tc.object.ClientEntityManagerImpl$2.addSingleThreaded(ClientEntityManagerImpl.java:162)
	at com.tc.object.ClientEntityManagerImpl.createInFlightMessageAfterAcks(ClientEntityManagerImpl.java:532)
	at com.tc.object.ClientEntityManagerImpl.invokeAction(ClientEntityManagerImpl.java:288)
	at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl.invoke(EntityClientEndpointImpl.java:155)
	at org.ehcache.clustered.client.internal.EhcacheClientEntity.invokeAsync(EhcacheClientEntity.java:345)
	at org.ehcache.clustered.client.internal.EhcacheClientEntity.invokeInternal(EhcacheClientEntity.java:320)
	at org.ehcache.clustered.client.internal.EhcacheClientEntity.invoke(EhcacheClientEntity.java:311)
	at org.ehcache.clustered.client.internal.store.CommonServerStoreProxy.get(CommonServerStoreProxy.java:159)
	at org.ehcache.clustered.client.internal.store.StrongServerStoreProxy.get(StrongServerStoreProxy.java:236)
	at org.ehcache.clustered.client.internal.store.ClusteredStore.getInternal(ClusteredStore.java:189)
	at org.ehcache.clustered.client.internal.store.ClusteredStore.getAndFault(ClusteredStore.java:515)
	at org.ehcache.impl.internal.store.tiering.TieredStore$3.apply(TieredStore.java:103)
	at org.ehcache.impl.internal.store.tiering.TieredStore$3.apply(TieredStore.java:99)
	at org.ehcache.impl.internal.store.heap.OnHeapStore$15.apply(OnHeapStore.java:727)
	at org.ehcache.impl.internal.store.heap.OnHeapStore$15.apply(OnHeapStore.java:724)
	at org.ehcache.impl.internal.store.heap.OnHeapStore$Fault.get(OnHeapStore.java:1023)
	at org.ehcache.impl.internal.store.heap.OnHeapStore$Fault.access$1000(OnHeapStore.java:996)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.resolveFault(OnHeapStore.java:760)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.getOrComputeIfAbsent(OnHeapStore.java:733)
	at org.ehcache.impl.internal.store.tiering.TieredStore.get(TieredStore.java:99)
	at org.ehcache.core.Ehcache.get(Ehcache.java:170)
	at org.ehcache.clustered.replication.BasicClusteredCacheOpsReplicationWithMultipleClientsTest.lambda$testBulkOps$7(BasicClusteredCacheOpsReplicationWithMultipleClientsTest.java:179)
	at java.util.HashMap$KeySet.forEach(HashMap.java:932)
	at org.ehcache.clustered.replication.BasicClusteredCacheOpsReplicationWithMultipleClientsTest.testBulkOps(BasicClusteredCacheOpsReplicationWithMultipleClientsTest.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lorban** [comment]
Note that I've seen a similar stack trace logged from `testClear` too but it doesn't make that test fail, so maybe that's normal but it's worth checking too:

```
2017-01-11 05:37:01.775 [Time-limited test] WARN class.com.tc.net.protocol.tcm.TCMessageImpl - message not sent
java.io.IOException: connection not established
	at com.tc.net.protocol.transport.MessageTransportBase.send(MessageTransportBase.java:185)
	at com.tc.net.protocol.tcm.AbstractMessageChannel.send(AbstractMessageChannel.java:206)
	at com.tc.net.protocol.tcm.ClientMessageChannelImpl.send(ClientMessageChannelImpl.java:167)
	at com.tc.net.protocol.tcm.TCMessageImpl.basicSend(TCMessageImpl.java:399)
	at com.tc.net.protocol.tcm.TCMessageImpl.send(TCMessageImpl.java:385)
	at com.tc.object.InFlightMessage.send(InFlightMessage.java:87)
	at com.tc.object.ClientEntityManagerImpl$1.handleEvent(ClientEntityManagerImpl.java:135)
	at com.tc.object.ClientEntityManagerImpl$1.handleEvent(ClientEntityManagerImpl.java:121)
	at com.tc.object.ClientEntityManagerImpl$2.addSingleThreaded(ClientEntityManagerImpl.java:162)
	at com.tc.object.ClientEntityManagerImpl.createInFlightMessageAfterAcks(ClientEntityManagerImpl.java:532)
	at com.tc.object.ClientEntityManagerImpl.invokeAction(ClientEntityManagerImpl.java:288)
	at com.tc.object.EntityClientEndpointImpl$InvocationBuilderImpl.invoke(EntityClientEndpointImpl.java:155)
	at org.ehcache.clustered.client.internal.EhcacheClientEntity.invokeAsync(EhcacheClientEntity.java:345)
	at org.ehcache.clustered.client.internal.EhcacheClientEntity.invokeInternal(EhcacheClientEntity.java:320)
	at org.ehcache.clustered.client.internal.EhcacheClientEntity.invoke(EhcacheClientEntity.java:311)
	at org.ehcache.clustered.client.internal.store.CommonServerStoreProxy.get(CommonServerStoreProxy.java:159)
	at org.ehcache.clustered.client.internal.store.EventualServerStoreProxy.get(EventualServerStoreProxy.java:55)
	at org.ehcache.clustered.client.internal.store.ClusteredStore.getInternal(ClusteredStore.java:189)
	at org.ehcache.clustered.client.internal.store.ClusteredStore.getAndFault(ClusteredStore.java:515)
	at org.ehcache.impl.internal.store.tiering.TieredStore$3.apply(TieredStore.java:103)
	at org.ehcache.impl.internal.store.tiering.TieredStore$3.apply(TieredStore.java:99)
	at org.ehcache.impl.internal.store.heap.OnHeapStore$15.apply(OnHeapStore.java:727)
	at org.ehcache.impl.internal.store.heap.OnHeapStore$15.apply(OnHeapStore.java:724)
	at org.ehcache.impl.internal.store.heap.OnHeapStore$Fault.get(OnHeapStore.java:1023)
	at org.ehcache.impl.internal.store.heap.OnHeapStore$Fault.access$1000(OnHeapStore.java:996)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.resolveFault(OnHeapStore.java:760)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.getOrComputeIfAbsent(OnHeapStore.java:733)
	at org.ehcache.impl.internal.store.tiering.TieredStore.get(TieredStore.java:99)
	at org.ehcache.core.Ehcache.get(Ehcache.java:170)
	at org.ehcache.clustered.replication.BasicClusteredCacheOpsReplicationWithMultipleClientsTest.lambda$testClear$12(BasicClusteredCacheOpsReplicationWithMultipleClientsTest.java:217)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.ehcache.clustered.replication.BasicClusteredCacheOpsReplicationWithMultipleClientsTest.testClear(BasicClusteredCacheOpsReplicationWithMultipleClientsTest.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lorban** [comment]
Here's the full standard output of the failing test.
[stdout.txt.gz](https://github.com/ehcache/ehcache3/files/698873/stdout.txt.gz)
