### ISSUE TITLE
offheap block org.ehcache.core.Ehcache.get method

### ISSUE THREAD

**Issue by LQZYC** [ehcache/ehcache3#1990]
we use ehcache on high concurrency env，find offheap block org.ehcache.core.Ehcache.get method cost more than 100 ms ,Analysis of the java stack， we find so many get method block on offheap flush action，here is the stack

```
"ConcurrentDataService15" #11285 daemon prio=5 os_prio=0 tid=0x00007f214b84e800 nid=0x18ea6 waiting on condition [0x0000000053fe1000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000065d43b5f0> (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:943)
	at org.terracotta.offheapstore.AbstractLockedOffHeapHashMap.computeIfPresentWithMetadata(AbstractLockedOffHeapHashMap.java:602)
	at org.terracotta.offheapstore.concurrent.AbstractConcurrentOffHeapMap.computeIfPresentWithMetadata(AbstractConcurrentOffHeapMap.java:785)
	at org.ehcache.impl.internal.store.offheap.EhcacheConcurrentOffHeapClockCache.computeIfPinned(EhcacheConcurrentOffHeapClockCache.java:213)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.flush(AbstractOffHeapStore.java:897)
	at org.ehcache.impl.internal.store.tiering.TieredStore$1.onInvalidation(TieredStore.java:84)
	at org.ehcache.impl.internal.store.heap.OnHeapStore$20.onInvalidation(OnHeapStore.java:921)
	at org.ehcache.impl.internal.store.heap.OnHeapStore$26.apply(OnHeapStore.java:1575)
	at org.ehcache.impl.internal.store.heap.OnHeapStore$26.apply(OnHeapStore.java:1568)
	at org.ehcache.impl.internal.concurrent.ConcurrentHashMap.computeIfPresent(ConcurrentHashMap.java:1793)
	- locked <0x00000006b40ccde8> (a org.ehcache.impl.internal.concurrent.ConcurrentHashMap$Node)
	at org.ehcache.impl.internal.store.heap.SimpleBackend.computeIfPresent(SimpleBackend.java:124)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.evict(OnHeapStore.java:1568)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.enforceCapacity(OnHeapStore.java:1535)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.getOrComputeIfAbsent(OnHeapStore.java:723)
	at org.ehcache.impl.internal.store.tiering.TieredStore.get(TieredStore.java:110)
	at org.ehcache.core.Ehcache.get(Ehcache.java:167)
	at com.taobao.mbus.data.cache.ehcache.EhCache.getRaw(EhCache.java:83)
	at com.taobao.mbus.data.cache.StatCache.getRaw(StatCache.java:57)
	at com.taobao.mbus.data.cache.service.CacheServiceImpl.getRaw(CacheServiceImpl.java:159)
	at com.taobao.mbus.data.cache.service.CacheServiceImpl.get(CacheServiceImpl.java:149)
	at com.taobao.mbus.data.impl.DataServiceImpl.getFromCache(DataServiceImpl.java:381)
	at com.taobao.mbus.data.impl.DataServiceImpl.getData0(DataServiceImpl.java:162)
	at com.taobao.mbus.data.impl.DataServiceImpl.access$000(DataServiceImpl.java:48)
	at com.taobao.mbus.data.impl.DataServiceImpl$GetValueTask.compute(DataServiceImpl.java:242)
	at com.taobao.mbus.data.impl.DataServiceImpl$GetValueTask.compute(DataServiceImpl.java:217)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at com.taobao.mbus.data.impl.DataServiceImpl$GetValueTask.compute(DataServiceImpl.java:252)
	at com.taobao.mbus.data.impl.DataServiceImpl$GetValueTask.compute(DataServiceImpl.java:217)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1107)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2046)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at com.taobao.mbus.data.impl.DataServiceImpl$GetValueTask.compute(DataServiceImpl.java:251)
	at com.taobao.mbus.data.impl.DataServiceImpl$GetValueTask.compute(DataServiceImpl.java:217)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1107)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2046)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at com.taobao.mbus.data.impl.DataServiceImpl$GetValueTask.compute(DataServiceImpl.java:251)
	at com.taobao.mbus.data.impl.DataServiceImpl$GetValueTask.compute(DataServiceImpl.java:217)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1107)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2046)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at com.taobao.mbus.data.impl.DataServiceImpl$GetValueTask.compute(DataServiceImpl.java:251)
	at com.taobao.mbus.data.impl.DataServiceImpl$GetValueTask.compute(DataServiceImpl.java:217)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1107)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2046)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at com.taobao.mbus.data.impl.DataServiceImpl$GetValueTask.compute(DataServiceImpl.java:252)
	at com.taobao.mbus.data.impl.DataServiceImpl$GetValueTask.compute(DataServiceImpl.java:217)
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by LQZYC** [comment]
how to solve it?  now  we use ehcache version is  3.1.3

**Comment by ljacomet** [comment]
Hello,

Thanks for your interest in Ehcache 3.

We request that users start the conversation on the [google group ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) before opening issues.

***

Please indicate your cache configuration, without it, impossible to answer anything relevant.

**Comment by LQZYC** [comment]
CacheConfig.heapSize = 1024  
        cacheExpireHours = 3 * 24
        CacheConfig.cacheStatistics = false
       CacheConfig.offheapSize=4096
CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder().build();
        cacheManager.init();

        ResourcePoolsBuilder rpBuilder = ResourcePoolsBuilder.newResourcePoolsBuilder();
        rpBuilder = rpBuilder.heap(CacheConfig.heapSize, MemoryUnit.MB);
        if (CacheConfig.offheapSize > 0) {
            rpBuilder = rpBuilder.offheap(CacheConfig.offheapSize, MemoryUnit.MB);
        }

        CacheConfigurationBuilder<Object, CacheWithExpiry> configBuilder =
            CacheConfigurationBuilder.newCacheConfigurationBuilder(Object.class, CacheWithExpiry.class, rpBuilder);
        CacheConfiguration<Object, CacheWithExpiry> config =
            configBuilder
                .withExpiry(Expirations.timeToLiveExpiration(Duration.of(CacheConfig.cacheExpireHours, TimeUnit.HOURS)))
                .withKeySerializer(new EhcacheKryoSerializer<Object>())
                .withValueSerializer(new EhcacheKryoSerializer<CacheWithExpiry>()).build();

       Cache<Object, CacheWithExpiry>  ehcache = cacheManager.createCache(name, config);

**Comment by LQZYC** [comment]
this is my cache configuration, this problem reduces the application throughput，After my observation, this problem appeared every time in java cms gc

**Comment by ljacomet** [comment]
Ok, thanks for the configuration information.

Could you run the same test without a heap tier, with only the off heap one?

**Comment by chrisdennis** [comment]
I'm going to close this as it's sat idle for so long.  If you want to re-engage by re-opening this issue feel free.
