### ISSUE TITLE
XML configuration fails when expiry is used in cache-template

### ISSUE THREAD

**Issue by axelwathne** [ehcache/ehcache3#2016]
Ehcache 3.3.1, JRE 1.8.0_131

The following XML configuration fails on the expiry element:

```xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.ehcache.org/v3" xsi:schemaLocation="http://www.ehcache.org/v3 http://www.ehcache.org/schema/ehcache-core-3.0.xsd" >

    <cache-template name="default">
        <heap>1000</heap>
        <expiry> 
            <ttl unit="minutes">10</ttl>
        </expiry>
    </cache-template>

    <cache uses-template="default" alias="mycache" />

</config>
```
Expiry works if it's directly in a cache, which is weird, since they both extend base-cache-type which defines the expiry element.

The output:<pre><code>
Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'expiry'. One of '{"http://www.ehcache.org/v3":heap-store-settings, "http://www.ehcache.org/v3":disk-store-settings, "http://www.ehcache.org/v3":service-configuration}' is expected.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:452) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3230) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1790) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:740) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243) ~[na:1.8.0_131]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[na:1.8.0_131]
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:177) ~[na:1.8.0_131]
	at org.ehcache.xml.ConfigurationParser.<init>(ConfigurationParser.java:159) ~[ehcache-3.3.1.jar:3.3.1 01f4b2121ef38b7e7d95c952c773881d5b1051d8]
	at org.ehcache.xml.XmlConfiguration.parseConfiguration(XmlConfiguration.java:175) ~[ehcache-3.3.1.jar:3.3.1 01f4b2121ef38b7e7d95c952c773881d5b1051d8]
	at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:163) ~[ehcache-3.3.1.jar:3.3.1 01f4b2121ef38b7e7d95c952c773881d5b1051d8]
</code></pre>

The same behavior is reported by someone else at https://stackoverflow.com/questions/44165149/echache3-xml-parsing-issue

**Comment by axelwathne** [comment]
Moving the heap down after the expiry tag fixes the problem. I can't say now if this is a bug in the schema or in Xerces.

**Comment by ljacomet** [comment]
Hello,

Thanks for your interest in Ehcache 3.

We request that users start the conversation on the [google group ehcache-users](https://groups.google.com/forum/#!forum/ehcache-users) before opening issues.

***

What you are seeing is the result of strict [XSD enforcement](http://www.ehcache.org/schema/ehcache-core.xsd) which specifies an ordering:

1. `key-type`
 2. `value-type`
 3. `expiry`
 4. `eviction-advisor`
 5. `loader-writer`
 6. `listeners`
 7. `resources` OR `heap`
 8. more ...

So closing as not an issue.

**Comment by axelwathne** [comment]
I am sorry, you are right. Thank you for your fast response. I guess I am too used to the xs:all from maven poms. May I suggest adding information about the google group to CONTRIBUTING.adoc, since it is referenced when creating an issue?

**Comment by ljacomet** [comment]
@axelwathne That's a very good suggestion! I'll do it.
