### ISSUE TITLE
XAStoreConfiguration gives NPE when adding a java serializable POJO

### ISSUE THREAD

**Issue by way2sukh** [ehcache/ehcache3#2159]
1.  Ehcache version :  3.4.0
2. Cache/CacheManager configuration : 
```java
CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
            .using(new LookupTransactionManagerProviderConfiguration(
                BitronixTransactionManagerLookup.class))
            .withCache("xaCache",
                CacheConfigurationBuilder
                    .newCacheConfigurationBuilder(Long.class, Person.class,
                        ResourcePoolsBuilder.heap(Long.MAX_VALUE))
                    .withExpiry(Expirations.noExpiration()).add(new XAStoreConfiguration("xaCache"))
                    .build())
            .build();
```
JDK 1.8 and Windows 10. 

Sample code : 
```java
BitronixTransactionManager manager = TransactionManagerServices.getTransactionManager();
CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
            .using(new LookupTransactionManagerProviderConfiguration(
                BitronixTransactionManagerLookup.class))
            .withCache("xaCache",
                CacheConfigurationBuilder
                    .newCacheConfigurationBuilder(Long.class, Person.class,
                        ResourcePoolsBuilder.heap(Long.MAX_VALUE))
                    .withExpiry(Expirations.noExpiration()).add(new XAStoreConfiguration("xaCache"))
                    .build())
            .build();
        cacheManager.init();

Cache<Long, Person> cc = cacheManager.getCache("xaCache", Long.class, Person.class);
        manager.begin();
        Person p = new Person("Sukhpal", 10);
        cc.put(1L, p);
        manager.commit();
```
Stacktrace : 

```
Caused by: org.ehcache.core.spi.store.StoreAccessException: java.lang.NullPointerException
	at org.ehcache.core.exceptions.StorePassThroughException.handleRuntimeException(StorePassThroughException.java:70)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.putIfAbsent(OnHeapStore.java:507)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.putIfAbsent(OnHeapStore.java:453)
	at org.ehcache.transactions.xa.internal.XATransactionContext.putIfAbsentInUnderlyingStore(XATransactionContext.java:296)
	at org.ehcache.transactions.xa.internal.XATransactionContext.prepare(XATransactionContext.java:154)
	at org.ehcache.transactions.xa.internal.XATransactionContext.commitInOnePhase(XATransactionContext.java:225)
	at org.ehcache.transactions.xa.internal.EhcacheXAResource.commit(EhcacheXAResource.java:69)
	... 10 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.ehcache.impl.serialization.CompactJavaSerializer.addMappingUnderLock(CompactJavaSerializer.java:165)
	at org.ehcache.impl.serialization.CompactJavaSerializer.getOrAddMapping(CompactJavaSerializer.java:149)
	at org.ehcache.impl.serialization.CompactJavaSerializer.access$000(CompactJavaSerializer.java:52)
	at org.ehcache.impl.serialization.CompactJavaSerializer$OOS.writeClassDescriptor(CompactJavaSerializer.java:200)
	at java.io.ObjectOutputStream.writeNonProxyDesc(Unknown Source)
	at java.io.ObjectOutputStream.writeClassDesc(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.writeObject(Unknown Source)
	at org.ehcache.impl.serialization.CompactJavaSerializer.serialize(CompactJavaSerializer.java:94)
	at org.ehcache.transactions.xa.internal.XAValueHolder.copyForSerialization(XAValueHolder.java:79)
	at org.ehcache.transactions.xa.internal.SoftLock.copyForSerialization(SoftLock.java:68)
	at org.ehcache.transactions.xa.internal.SoftLockValueCombinedSerializer.serialize(SoftLockValueCombinedSerializer.java:42)
	at org.ehcache.transactions.xa.internal.SoftLockValueCombinedSerializer.serialize(SoftLockValueCombinedSerializer.java:30)
	at org.ehcache.impl.internal.store.heap.holders.SerializedOnHeapValueHolder.<init>(SerializedOnHeapValueHolder.java:41)
	at org.ehcache.impl.internal.store.heap.holders.SerializedOnHeapValueHolder.<init>(SerializedOnHeapValueHolder.java:49)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.makeValue(OnHeapStore.java:1542)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.makeValue(OnHeapStore.java:1535)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.newCreateValueHolder(OnHeapStore.java:1481)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.access$500(OnHeapStore.java:114)
	at org.ehcache.impl.internal.store.heap.OnHeapStore$10.apply(OnHeapStore.java:476)
	at org.ehcache.impl.internal.store.heap.OnHeapStore$10.apply(OnHeapStore.java:467)
	at org.ehcache.impl.internal.store.heap.KeyCopyBackend$3.apply(KeyCopyBackend.java:159)
	at org.ehcache.impl.internal.store.heap.KeyCopyBackend$3.apply(KeyCopyBackend.java:156)
	at org.ehcache.impl.internal.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1878)
	at org.ehcache.impl.internal.store.heap.KeyCopyBackend.compute(KeyCopyBackend.java:156)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.putIfAbsent(OnHeapStore.java:467)
	... 15 common frames omitted
```

**Comment by ljacomet** [comment]
The issue is caused by the delegate serializer not carrying the stateful information. I will open a PR shortly that should fix that, still working on having a test though.

**Comment by ljacomet** [comment]
Given all the changes in master, I will open the PR there only once I have tests in.

**Comment by way2sukh** [comment]
In which version of ehcache this change would be available? 3.4.0? Or I need to build from github?

**Comment by henri-tremblay** [comment]
3.3.3, 3.4.1, 3.5.0

**Comment by ljacomet** [comment]
None of which are released yet. So if you want the fix now, you need to pick a snapshot or build yourself indeed.
Note that we are dropping java 6 and 7 support with 3.5.0

**Comment by way2sukh** [comment]
NPE seems to have gone with this change but now I'm not able get entries in another session i.e. if I put some values in session 1 and I start a new session then previous values aren't available.

**Comment by ljacomet** [comment]
Hi,

Make sure you have a proper equals method on your values as well.
Internally Ehcache uses compare-and-swap operations which means that
without the proper equals, the transaction results will not be made
available in the XA cache.

Regards,
Louis

**Comment by way2sukh** [comment]
Louis
Thanks, it worked once I implemented equals and hashCode on values. But what's the reason behind? Cache acts more or less like a map.  And it isn't mentioned in documentation too.
