### ISSUE TITLE
ehcache Management and Monitoring class not found NmsAgentEntity

### ISSUE THREAD

**Issue by nadeemamin** [ehcache/ehcache3#2216]
the sample code for  mgmt and monitoring of ehcache results in classnotfound 
the class is no where to be found.  is there a workaround or correction in the code ?

primary used in the class : 
https://github.com/ehcache/ehcache3/blob/2b3cf5da4480f8a74d903c1d112591a4844347e1/management/src/main/java/org/ehcache/management/cluster/DefaultClusteringManagementService.java

## stacktrace

gov.cbp.ace.st.common.cache.ClusteredCacheManagerTest.testTvsClusteredCacheManager(ClusteredCacheManagerTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassNotFoundException: org.terracotta.management.entity.nms.agent.client.NmsAgentEntity
	at java.net.URLClassLoader.findClass(URLClassLoader.java:607)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:844)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:823)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:325)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:803)
	... 26 more

## sample code 

 DefaultManagementRegistryConfiguration registryConfiguration = new DefaultManagementRegistryConfiguration().setCacheManagerAlias("myCacheManager1"); 
  ManagementRegistryService managementRegistry = new DefaultManagementRegistryService(registryConfiguration); 

  CacheConfiguration<Long, String> cacheConfiguration = CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, String.class,
    ResourcePoolsBuilder.newResourcePoolsBuilder().heap(1, MemoryUnit.MB).offheap(2, MemoryUnit.MB))
    .build();

  cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
      .withCache("myCache", cacheConfiguration)
      .using(managementRegistry) 
      .build(true);

**Comment by henri-tremblay** [comment]
Hi. Thank you for using Ehcache. We require encountered issues to first be discussed on our [mailing list](https://groups.google.com/forum/#!forum/ehcache-users).

In your case, you seem to have a classpath issue. Terracotta platform client jar is missing from the classpath. We can discuss about it more extensively on the mailing list.

**Comment by nadeemamin** [comment]
could you pl. clarify what Terracotta platform client jar needs to be in, i searched the whole 3.4 toolkit, don't see it anywhere  in the zipped distribution ?

**Comment by henri-tremblay** [comment]
It depends a bit how you classpath was created. Note also that monitoring is an enterprise feature. It will not cause your current issue but you will a license to use it correctly.

And again, please ask such questions on the mailing list. Or to the appropriate support channel if you already have a commercial license. I will now close this issue.

**Comment by anthonydahanne** [comment]
issue properly moved to the mailing list : https://groups.google.com/forum/#!category-topic/ehcache-users/ehcache-core/lc951In_e4E
