### ISSUE TITLE
ehcache toolkit 3.4 terracotta  server  restarts with  java.lang.ClassCastException when one of the node is started/restarted

### ISSUE THREAD

**Issue by nadeemamin** [ehcache/ehcache3#2273]
i am using ehcache toolkit 3.4  in a clustered mode .  : www.ehcache.org/documentation/3.4/
in a cluster with two nodes, if one of the node is started/or restarted,i always get the following exception.

018-02-05 14:30:42,673 [WorkerThread(passive_replication_ack_stage, 0)] INFO com.tc.objectserver.entity.PassiveReplicationBroker - Starting sync to NodeID[10.158.67.168:8090]
2018-02-05 14:30:43,755 [WorkerThread(request_processor_stage, 1, 1)] INFO org.ehcache.clustered.server.store.ClusterTierActiveEntity - Sync started for concurrency key 1.
2018-02-05 14:30:43,768 [WorkerThread(request_processor_stage, 1, 1)] ERROR com.tc.objectserver.entity.ManagedEntityImpl - caught exception during invoke
java.lang.ClassCastException: org.ehcache.clustered.server.internal.messages.EhcacheStateRepoSyncMessage cannot be cast to org.ehcache.clustered.server.internal.messages.EhcacheStateRepoSyncMessage
        at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_131]
        at org.ehcache.clustered.server.store.ClusterTierActiveEntity.synchronizeKeyToPassive(ClusterTierActiveEntity.java:603) ~[ehcache-server-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
        at com.tc.objectserver.entity.ManagedEntityImpl.performSync(ManagedEntityImpl.java:730) [dso-l2-5.3.2.jar:na]
        at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:513) [dso-l2-5.3.2.jar:na]
        at com.tc.objectserver.entity.ManagedEntityImpl.lambda$sync$12(ManagedEntityImpl.java:946) [dso-l2-5.3.2.jar:na]
        at com.tc.objectserver.entity.RequestProcessor$EntityRequest.invoke(RequestProcessor.java:171) ~[dso-l2-5.3.2.jar:na]
        at com.tc.objectserver.entity.RequestProcessor$EntityRequest.run(RequestProcessor.java:162) ~[dso-l2-5.3.2.jar:na]
        at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:27) ~[dso-l2-5.3.2.jar:na]
        at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:23) ~[dso-l2-5.3.2.jar:na]
        at com.tc.async.impl.AbstractStageQueueImpl$HandledContext.runWithHandler(AbstractStageQueueImpl.java:207) ~[common-5.3.2.jar:na]
        at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197) ~[common-5.3.2.jar:na]
2018-02-05 14:30:43,776 [WorkerThread(request_processor_stage, 1, 1)] ERROR com.tc.server.TCServerMain - Thread:Thread[WorkerThread(request_processor_stage, 1, 1),5,TC Thread Group] got an uncaugh

**Comment by henri-tremblay** [comment]
It was previously mentioned to you that these issues should be sent to the mailing list before filing an actual issue. I will now close this issue.
