### ISSUE TITLE
Cache item removing hangs thread

### ISSUE THREAD

**Issue by bjanczak** [ehcache/ehcache3#2298]
Ehcache: 3.4.0
Stacktrace:
```
"http-nio-8080-exec-871" - Thread t@1541611
   java.lang.Thread.State: BLOCKED
	at org.ehcache.impl.internal.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1893)
	- waiting to lock <21a354ce> (a org.ehcache.impl.internal.concurrent.ConcurrentHashMap$Node) owned by "http-nio-8080-exec-113" t@836399
	at org.ehcache.impl.internal.store.heap.SimpleBackend.compute(SimpleBackend.java:96)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.compute(OnHeapStore.java:1149)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.compute(OnHeapStore.java:1134)
	at org.ehcache.core.EhcacheWithLoaderWriter.removeInternal(EhcacheWithLoaderWriter.java:373)
	at org.ehcache.core.EhcacheWithLoaderWriter.remove(EhcacheWithLoaderWriter.java:347)
	at com.softwareplant.util.cacheint.provider.ehcache3.EhCache3.invalidate(EhCache3.java:71)
	at com.softwareplant.util.cacheext.CacheDelegate.invalidate(CacheDelegate.java:68)
	at com.softwareplant.extsystem.jiracloud.domain.JiraCloudAgileIssueRepository.fetchCacheEntry(JiraCloudAgileIssueRepository.java:34)
```

How we build a cache:
```java
log.debug("Creating cache: " + config.getName());

		ResourcePoolsBuilder resourcePoolsBuilder = ResourcePoolsBuilder.newResourcePoolsBuilder();
		if (config.getMaxEntriesLocalHeap() != null) {
			resourcePoolsBuilder = resourcePoolsBuilder.heap(config.getMaxEntriesLocalHeap(), EntryUnit.ENTRIES);
		}
		CacheConfigurationBuilder<K, V> cacheConfigurationBuilder = CacheConfigurationBuilder.newCacheConfigurationBuilder(
				config.getKeyClass(),
				config.getValueClass(),
				resourcePoolsBuilder)
				.withLoaderWriter(new EhCache3LoaderWriter<>(name, config.getLoader()));
		if (config.getExpirationMode() == CacheConfig.ExpirationMode.TIME_TO_IDLE) {
			cacheConfigurationBuilder =
					cacheConfigurationBuilder.withExpiry(Expirations.timeToIdleExpiration(Duration.of(config.getTimeout(), config.getTimeoutUnit())));
		}
		if (config.getExpirationMode() == CacheConfig.ExpirationMode.TIME_TO_LIVE) {
			cacheConfigurationBuilder =
					cacheConfigurationBuilder.withExpiry(Expirations.timeToLiveExpiration(Duration.of(config.getTimeout(), config.getTimeoutUnit())));
		}
		CacheConfiguration<K, V> cacheConfiguration = cacheConfigurationBuilder.build();
		cacheManager.createCache(name, cacheConfiguration);
		caches.put(name, config);`
```
Cache config:
```xml
<bean id="jiraCloudAgileIssueCache" factory-bean="cacheManager" factory-method="buildTenantCache">
		<constructor-arg>
			<bean class="com.softwareplant.util.cache.CacheConfig">
				<property name="name" value="${productName}.JiraSoftwareIssueCache"/>
				<property name="maxEntriesLocalHeap" value="100000"/>
				<property name="timeout" value="259200"/>
				<property name="timeoutUnit" value="SECONDS"/>
				<property name="expirationMode" value="TIME_TO_IDLE"/>
				<property name="loader" ref="jiraCloudAgileIssueCacheLoader"/>
				<property name="keyClass" value="java.lang.Long"/>
				<property name="valueClass" value="com.google.common.base.Optional"/>
			</bean>
		</constructor-arg>
	</bean>
```

We have like >800 http threads hanged in tomcat on cache invalidation.

Every 30 minutes we iterate over every cache in order to calculate it's size. Can this lead into deadlock?

**Comment by chrisdennis** [comment]
Until proven otherwise I doubt this is broken. Given where you are blocked I would guess that another thread is blocked inside the lock for this key trying to do a remove on whatever SOR the CacheLoaderWriter is talking to.  Until we've nailed this down to being a bug in Ehcache could we move discussion to the ehcache-users@googlegroups.com mailing list?
