### ISSUE TITLE
Spring Boot 2.0 Ehcache 3.5 cacheManager could't be created 

### ISSUE THREAD

**Issue by antonsafronov** [ehcache/ehcache3#2334]
I have application based on Spring boot 2.0 (2.0.0.RELEASE) and ehcache 3.5 when I try to run application I receive the following error:
```
Caused by: java.lang.NoSuchMethodError: org.terracotta.statistics.StatisticsManager.createPassThroughStatistic(Ljava/lang/Object;Ljava/lang/String;Ljava/util/Set;Lorg/terracotta/statistics/StatisticType;Ljava/util/function/Supplier;)V
	at org.ehcache.impl.internal.store.heap.OnHeapStore.<init>(OnHeapStore.java:265) ~[ehcache-3.5.0.jar:3.5.0 61be0279e82ff62e370d4a7c83fc3d41e24b9231]
	at org.ehcache.impl.internal.store.heap.OnHeapStore$Provider.createStoreInternal(OnHeapStore.java:1612) ~[ehcache-3.5.0.jar:3.5.0 61be0279e82ff62e370d4a7c83fc3d41e24b9231]
	at org.ehcache.impl.internal.store.heap.OnHeapStore$Provider.createHigherCachingTier(OnHeapStore.java:1713) ~[ehcache-3.5.0.jar:3.5.0 61be0279e82ff62e370d4a7c83fc3d41e24b9231]
	at org.ehcache.impl.internal.store.tiering.CompoundCachingTier$Provider.createCachingTier(CompoundCachingTier.java:206) ~[ehcache-3.5.0.jar:3.5.0 61be0279e82ff62e370d4a7c83fc3d41e24b9231]
	at org.ehcache.impl.internal.store.tiering.TieredStore$Provider.createStore(TieredStore.java:371) ~[ehcache-3.5.0.jar:3.5.0 61be0279e82ff62e370d4a7c83fc3d41e24b9231]
	at org.ehcache.core.EhcacheManager.getStore(EhcacheManager.java:506) ~[ehcache-3.5.0.jar:3.5.0 61be0279e82ff62e370d4a7c83fc3d41e24b9231]
	at org.ehcache.core.EhcacheManager.createNewEhcache(EhcacheManager.java:316) ~[ehcache-3.5.0.jar:3.5.0 61be0279e82ff62e370d4a7c83fc3d41e24b9231]
	at org.ehcache.core.EhcacheManager.createCache(EhcacheManager.java:265) ~[ehcache-3.5.0.jar:3.5.0 61be0279e82ff62e370d4a7c83fc3d41e24b9231]
	at org.ehcache.core.EhcacheManager.init(EhcacheManager.java:579) ~[ehcache-3.5.0.jar:3.5.0 61be0279e82ff62e370d4a7c83fc3d41e24b9231]
	at org.ehcache.jsr107.EhcacheCachingProvider.createCacheManager(EhcacheCachingProvider.java:151) ~[ehcache-3.5.0.jar:3.5.0 61be0279e82ff62e370d4a7c83fc3d41e24b9231]
	at org.ehcache.jsr107.EhcacheCachingProvider.getCacheManager(EhcacheCachingProvider.java:127) ~[ehcache-3.5.0.jar:3.5.0 61be0279e82ff62e370d4a7c83fc3d41e24b9231]
	at org.ehcache.jsr107.EhcacheCachingProvider.getCacheManager(EhcacheCachingProvider.java:90) ~[ehcache-3.5.0.jar:3.5.0 61be0279e82ff62e370d4a7c83fc3d41e24b9231]
	at ....core.spring.EhCacheConfiguration.createClusteredCacheManager(EhCacheConfiguration.java:88) ~[classes/:na]
```

The configuration class:
```java
@Configuration
public class EhCacheConfiguration extends CachingConfigurerSupport {

    private final Logger log = LoggerFactory.getLogger(CacheConfiguration.class);

    @Autowired
    private Environment env;

    @Autowired
    private ApplicationProperties properties;

    private CacheManager cacheManager;

    @Bean
    @Override
    public org.springframework.cache.CacheManager cacheManager() {
        cacheManager = env.acceptsProfiles(Constants.SPRING_PROFILE_PRODUCTION) ? createClusteredCacheManager() : createInMemoryCacheManager();
        return new JCacheCacheManager(cacheManager);
    }

    @PreDestroy
    public void destroy() {
        log.info("Close Cache Manager");
        cacheManager.close();
    }

    private CacheManager createInMemoryCacheManager() {
        EhcacheCachingProvider provider = getCachingProvider();
        return provider.getCacheManager(provider.getDefaultURI(), new XmlConfiguration(getClass().getResource("/ehcache.xml")));
    }

    private CacheManager createClusteredCacheManager() {
        ApplicationProperties.Cache.Ehcache.Cluster clusterProperties = properties.getCache().getEhcache().getCluster();

        long heapCacheSize = properties.getCache().getEhcache().getHeap();
        long ttl = properties.getCache().getEhcache().getTimeToLiveSeconds();

        ClusteringServiceConfigurationBuilder clusteringServiceConfigurationBuilder = ClusteringServiceConfigurationBuilder.cluster(clusterProperties.getUri());

        ServerSideConfigurationBuilder serverSideConfigurationBuilder =
                (clusterProperties.isAutoCreate() ? clusteringServiceConfigurationBuilder.autoCreate() : clusteringServiceConfigurationBuilder.expecting())
                    .defaultServerResource(properties.getCache().getServerResource());

        org.ehcache.config.CacheConfiguration cacheConfiguration = CacheConfigurationBuilder
                .newCacheConfigurationBuilder(Object.class, Object.class, ResourcePoolsBuilder
                        .newResourcePoolsBuilder()
                        .heap(heapCacheSize)
                        .offheap(clusterProperties.getOffheap(), MemoryUnit.MB)
                        .with(ClusteredResourcePoolBuilder.clusteredDedicated(clusterProperties.getSizeInMb(), MemoryUnit.MB)))
                .withExpiry(Expirations.timeToLiveExpiration(new org.ehcache.expiry.Duration(ttl, TimeUnit.SECONDS)))
                .add(new ClusteredStoreConfiguration(clusterProperties.getConsistency()))
                .build();

        Map<String, org.ehcache.config.CacheConfiguration<?, ?>> caches = createCacheConfigurations(cacheConfiguration);

        EhcacheCachingProvider provider = getCachingProvider();
        DefaultConfiguration configuration = new DefaultConfiguration(caches, provider.getDefaultClassLoader(), serverSideConfigurationBuilder.build());
        return provider.getCacheManager(provider.getDefaultURI(), configuration);
    }

    private Map<String, org.ehcache.config.CacheConfiguration<?, ?>> createCacheConfigurations(org.ehcache.config.CacheConfiguration<Object, Object> cacheConfiguration) {
        Map<String, org.ehcache.config.CacheConfiguration<?, ?>> caches = new HashMap<>();
        caches.put("cache.template", cacheConfiguration);
        caches.put("cache.template.placeholders", cacheConfiguration);
        caches.put("cache.template.adapters", cacheConfiguration);
        return caches;
    }

    private EhcacheCachingProvider getCachingProvider() {
        return (EhcacheCachingProvider) Caching.getCachingProvider();
    }

}
```
It worked on SB 2.0.M7 and ehcache 3.4

What is the reason of the issue?

**Comment by antonsafronov** [comment]
After the downgrade the ehcache version to 3.4.0 the application start working.

**Comment by anthonydahanne** [comment]
Hello @antonsafronov ,
Thanks for the bug report, this is the first time we hear about it.
Is it possible for you to create a reproducible test case on github? something very simple, using start.spring.io and enough code to reproduce the issue your describe.
Also, according to https://github.com/ehcache/ehcache3/blob/master/CONTRIBUTING.adoc#reporting-issues , we ask our users to first report issues on the mailing list : https://groups.google.com/forum/#!forum/ehcache-users

**Comment by chrisdennis** [comment]
This looks like a classpath issue to me.  That method is new in version 2 of the statistics library which we upgraded to with Ehcache 3.5.0.  Do you have a second copy of the Terracotta statistics classes on the classpath somewhere?  Possibly inside an Ehcache 2.x jar?

**Comment by ajaristi** [comment]
I had ehcache2 as part of another dependency. I excluded it and worked.

Thanks

**Comment by EminDeveloper** [comment]
So either find a compatible version or upgrade Spring Boot
