### ISSUE TITLE
Failed to find provider with satisfied dependency set for interface org.ehcache.core.spi.store.Store$Provider [candidates []]

### ISSUE THREAD

**Issue by lakshmankhcl** [ehcache/ehcache3#2357]
I tried using ehcache within Scala Application and it runs perfectly fine when I run it using sbt tool: `sbt my-service/run`. But, if I try to run the application JAR : `sbt my-service/assembly` `java -jar my-service.jar` I am getting below exception:

`Caused by: java.lang.IllegalStateException: org.ehcache.core.internal.service.ServiceLocator$DependencyException: Failed to find provider with satisfied dependency set for interface org.ehcache.core.spi.store.Store$Provider [candidates []]
        at org.ehcache.core.internal.service.ServiceLocator$DependencySet.build(ServiceLocator.java:319)
        at org.ehcache.core.EhcacheManager.resolveServices(EhcacheManager.java:145)
        at org.ehcache.core.EhcacheManager.<init>(EhcacheManager.java:118)
        at org.ehcache.core.EhcacheManager.<init>(EhcacheManager.java:108)
        at org.ehcache.config.builders.CacheManagerBuilder.newCacheManager(CacheManagerBuilder.java:114)
        at org.ehcache.config.builders.CacheManagerBuilder.build(CacheManagerBuilder.java:70)
`

I added following to my dependencies:

`"org.ehcache"                  % "ehcache"               % "3.5.2"`

Scala Version: 2.12.1

**Comment by chrisdennis** [comment]
My best guess is that sbt isn't correctly merging the `META-INF/services` files when build your application jar.  Ehcache relies on the Java `ServiceLoader` to locate the various services that a configuration might require.

**Comment by chrisdennis** [comment]
Sorry... this slipped from my radar.  Off the top of my head no... the first thing to validate is that sbt did actually munge the services files that are present in the ehcache jar files when assembling your application jar.  Assuming that is the case I would then pursue this as a sbt/scala issue.
