### ISSUE TITLE
cacheManager close result to IllegalStateException: Close not supported from UNINITIALIZED

### ISSUE THREAD

**Issue by zhang-shoukang** [ehcache/ehcache3#2476]
Exception in thread "main" java.lang.IllegalStateException: Close not supported from UNINITIALIZED
	at org.ehcache.core.InternalStatus.close(InternalStatus.java:74)
	at org.ehcache.core.StatusTransitioner.close(StatusTransitioner.java:86)
	at org.ehcache.core.EhcacheManager.close(EhcacheManager.java:601)
	at com.fancy.qutoutiao.Controller.BasicXML.main(BasicXML.java:34)

**Comment by anthonydahanne** [comment]
please provide more details to your issue and submit it to the forum : https://groups.google.com/forum/#!forum/ehcache-users

**Comment by henri-tremblay** [comment]
And you most probably forgot to initialized your `CacheManager` by calling `init()` or `build(true)` on the `CacheManagerBuilder`.

**Comment by zhang-shoukang** [comment]
@henri-tremblay Can i get you email,I was baffled by some problems，Thanks a lot.

**Comment by henri-tremblay** [comment]
@zhang-shoukang I am not a helpdesk support. Please use the mailing list for support. And read the documentation first.
