### ISSUE TITLE
"java.lang.NoClassDefFoundError: java/nio/channels/FileLock" during shutdown and restart

### ISSUE THREAD

**Issue by Alfred6556** [ehcache/ehcache3#2536]
We have implemented Ehcache on ColdFusion 2016. During every single shutdown and restart of ColdFusion, we get the following error:

Nov 27, 2018 8:52:42 AM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["ajp-nio-8013"]
Exception in thread "Thread-8" java.lang.NoClassDefFoundError: java/nio/channels/FileLock
	at net.sf.ehcache.DiskStorePathManager$DiskStorePath.unlock(DiskStorePathManager.java:358)
	at net.sf.ehcache.DiskStorePathManager.releaseLock(DiskStorePathManager.java:236)
	at net.sf.ehcache.CacheManager.shutdown(CacheManager.java:1571)
	at coldfusion.tagext.io.cache.ehcache.GenericEhcache$CacheCleanUpAgent.run(GenericEhcache.java:1166)
	at coldfusion.scheduling.Scheduler.run(Scheduler.java:245)
	at java.lang.Thread.run(Thread.java:748)

I would be grateful for any ideas to fix this.

**Comment by henri-tremblay** [comment]
Please use the [user group](https://groups.google.com/forum/#!forum/ehcache-users) for such questions.

Also, this is an Ehcache 3 issue tracker. You are using Ehcache 2. So you are in the wrong place.

FileLock must be there so I suspect you are running under a security manager that forbid disk. Or a really old JVM.

Closing this now.

**Comment by Alfred6556** [comment]
Thanks for your remarks, @henri-tremblay. I am curious what you mean by a really old JVM; we're on 1.8.0_181. In any case, sorry for posting at the wrong place. I am moving this to the [user group](https://groups.google.com/forum/#!forum/ehcache-users)
