### ISSUE TITLE
NullPointerException with the Ehcache configuration

### ISSUE THREAD

**Issue by bvalluri** [ehcache/ehcache3#2542]
I am using the ehcache as my second level cache in the hibernate. Initialisation happens through the persitence manger of spring.   Below are my ehcache configuration. In case of the scale environment i am facing the NullPointerException. I  am hoping these might be due to offheap and ttl configuration. 

**My Ehcache configuration is** 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
		xmlns='http://www.ehcache.org/v3'
		xmlns:jsr107='http://www.ehcache.org/v3/jsr107'
		xsi:schemaLocation="
                http://www.ehcache.org/v3 http://www.ehcache.org/schema/ehcache-core-3.0.xsd
                http://www.ehcache.org/v3/jsr107 http://www.ehcache.org/schema/ehcache-107-ext-3.0.xsd">


	<cache alias="XXX">
		<expiry>
			<ttl unit="minutes">10</ttl>
		</expiry>

		<resources>
			<heap unit="entries">50000</heap>
			<offheap unit="MB">500</offheap>
		</resources>
		<jsr107:mbeans enable-management="true" enable-statistics="true"/>
	</cache>
</config>
```

**1) First NullPointerException**
```
2018-Dec-04 08:29:13.562 [Naas_Event_Bus-147] !**! ERROR CommandGeneratorService.() - java.lang.NullPointerException
java.lang.NullPointerException: null
        at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore$27.apply(AbstractOffHeapStore.java:910) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
        at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore$27.apply(AbstractOffHeapStore.java:907) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
        at org.ehcache.impl.internal.store.offheap.EhcacheConcurrentOffHeapClockCache$4.apply(EhcacheConcurrentOffHeapClockCache.java:218) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
        at org.ehcache.impl.internal.store.offheap.EhcacheConcurrentOffHeapClockCache$4.apply(EhcacheConcurrentOffHeapClockCache.java:213) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
        at org.terracotta.offheapstore.OffHeapHashMap.computeIfPresentWithMetadata(OffHeapHashMap.java:2105) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
        at org.terracotta.offheapstore.AbstractLockedOffHeapHashMap.computeIfPresentWithMetadata(AbstractLockedOffHeapHashMap.java:604) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
        at org.terracotta.offheapstore.concurrent.AbstractConcurrentOffHeapMap.computeIfPresentWithMetadata(AbstractConcurrentOffHeapMap.java:785) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
        at org.ehcache.impl.internal.store.offheap.EhcacheConcurrentOffHeapClockCache.computeIfPinned(EhcacheConcurrentOffHeapClockCache.java:213) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
        at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.flush(AbstractOffHeapStore.java:907) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
        at org.ehcache.impl.internal.store.tiering.TieredStore$NoopCachingTier.getOrComputeIfAbsent(TieredStore.java:498) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
        at org.ehcache.impl.internal.store.tiering.TieredStore.get(TieredStore.java:96) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
        at org.ehcache.core.Ehcache.get(Ehcache.java:169) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
        at org.ehcache.jsr107.Eh107Cache.get(Eh107Cache.java:94) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
        at org.hibernate.cache.jcache.JCacheTransactionalDataRegion.get(JCacheTransactionalDataRegion.java:60) ~[hibernate-jcache-5.2.10.Final.jar:5.2.10.Final]
        at org.hibernate.cache.jcache.access.AbstractReadWriteRegionAccessStrategy.get(AbstractReadWriteRegionAccessStrategy.java:48) ~[hibernate-jcache-5.2.10.Final.jar:5.2.10.Final]
        at org.hibernate.cache.jcache.access.ReadWriteNaturalIdRegionAccessStrategy.get(ReadWriteNaturalIdRegionAccessStrategy.java:21) ~[hibernate-jcache-5.2.10.Final.jar:5.2.10.Final]
        at org.hibernate.engine.internal.CacheHelper.fromSharedCache(CacheHelper.java:32) ~[hibernate-core-5.2.10.Final.jar:5.2.10.Final]
        at 
```
**2) Second NullPointerException**
```
2018-Nov-28 05:21:56.248 [MaintenanceJobs-991] !*tLWM5_3dQam4vcv4YafuXQ*! ERROR PurgeEventsTask.() - null
java.lang.NullPointerException: null
	at org.terracotta.offheapstore.paging.OffHeapStorageArea.readInt(OffHeapStorageArea.java:173) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.terracotta.offheapstore.storage.OffHeapBufferStorageEngine.readKeyBuffer(OffHeapBufferStorageEngine.java:156) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.terracotta.offheapstore.storage.PortabilityBasedStorageEngine.readKey(PortabilityBasedStorageEngine.java:119) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.terracotta.offheapstore.OffHeapHashMap$DirectEntry.<init>(OffHeapHashMap.java:1554) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.terracotta.offheapstore.OffHeapHashMap$EntryIterator.create(OffHeapHashMap.java:1532) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.terracotta.offheapstore.OffHeapHashMap$EntryIterator.create(OffHeapHashMap.java:1525) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.terracotta.offheapstore.OffHeapHashMap$HashIterator.next(OffHeapHashMap.java:1421) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.terracotta.offheapstore.AbstractLockedOffHeapHashMap$LockedEntryIterator.next(AbstractLockedOffHeapHashMap.java:399) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.terracotta.offheapstore.AbstractLockedOffHeapHashMap$LockedEntryIterator.next(AbstractLockedOffHeapHashMap.java:392) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.terracotta.offheapstore.concurrent.AbstractConcurrentOffHeapMap$AggregateIterator.next(AbstractConcurrentOffHeapMap.java:557) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore$21.next(AbstractOffHeapStore.java:602) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore$21.next(AbstractOffHeapStore.java:592) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.ehcache.core.Ehcache$Jsr107CacheImpl.removeAll(Ehcache.java:835) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.ehcache.jsr107.Eh107Cache.removeAll(Eh107Cache.java:311) ~[ehcache-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.hibernate.cache.jcache.JCacheTransactionalDataRegion.clear(JCacheTransactionalDataRegion.java:56) ~[hibernate-jcache-5.2.10.Final.jar:5.2.10.Final]
	at 
```

Does anything wrong with my configuration of ehcahce?
Is there any fix for these above NullPointers?

**Comment by henri-tremblay** [comment]
Can you provide a full test case (including the java code) reproducing the error?

Can you try Ehcache 3.6.1?

**Comment by bvalluri** [comment]
Thank you. I will prepare and post. Current version i am using is 3.4.0. Quick question from my side is the TTL can be used with the offheap configuration?

**Comment by chrisdennis** [comment]
That shouldn’t be a problem.

**Comment by bvalluri** [comment]
When i execute the simple test case we don't have any issue. We have python script at the background that adds Database Entities to postgres Db. Two use this as a second level cache we used persistenceManager. 



   <bean id="entityManagerFactory" class="org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean" depends-on="ehcacheInit">
      <property name="jpaDialect">
         <bean class="org.springframework.orm.jpa.vendor.HibernateJpaDialect" />
      </property>
 
      <property name="persistenceUnitManager" ref="persistenceUnitManager"/>
      <property name="jpaProperties">
         <value>
            hibernate.dialect=${hibernate.dialect}
            hibernate.query.substitutions=true 'Y', false 'N'
            hibernate.cache.use_second_level_cache=true
            hibernate.cache.use_query_cache=true
            hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory
            hibernate.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider
            hibernate.javax.cache.uri=#{new org.springframework.core.io.ClassPathResource("ehcache.xml").getURI().toString()}
            hibernate.generate_statistics=false
            hibernate.jdbc.batch_size=512
            hibernate.default_batch_fetch_size=8
            hibernate.max_fetch_depth=2
            
            hibernate.jdbc.fetch_size=500
            hibernate.jdbc.batch_versioned_data=true
            hibernate.connection.pool_size=0
            hibernate.pool_size=0
            
            hibernate.show_sql=false
            hibernate.format_sql=false
			hibernate.discriminator.ignore_explicit_for_joined=true
			hibernate.temp.use_jdbc_metadata_defaults=false
            hibernate.entity_dirtiness_strategy=com.anuta.model.base.dirtycheck.EntityDirtinessStrategyImpl
            
            hibernate.cache.auto_evict_collection_cache=true
         </value>
         
         
      </property>
   </bean>

**Comment by chrisdennis** [comment]
If I had to guess at this point... I would guess it's a hole in the locking when accessing the cache through 107 module layer... but that's a very blind guess. I'll try and find some more time to look at this properly this week.

**Comment by bvalluri** [comment]
Yes i am using the Ehcache through 107 module Layer.  Wanted to use offheap configuration, so we upgraded ehcache to 3.4.0 . In scale we are facing these above NullPointers. It will good if any one provide any immediate workaround to proceed through our release.

**Comment by henri-tremblay** [comment]
Can you try to upgrade to 3.6.1?

**Comment by chrisdennis** [comment]
The exception you're seeing is a symptom of this bug: Terracotta-OSS/offheap-store#54

There's also another issue with the iterator here that I think can only be exposed by a pure offheap cache. I'm going to leave this open and track both issues in this one place.  Fixes in to master some time tomorrow hopefully - by the end of the week for sure.
