### ISSUE TITLE
XML config parser not working in OSGi environment

### ISSUE THREAD

**Issue by seelmann** [ehcache/ehcache3#2554]
Pax exam 4.11.0 with Apache Felix 6.0.0 and Eclipse 4.9
OpenJDK 1.8.0_192
Error with versions 3.6.1 and 3.6.3
Works with version 3.5.3

Reason seems to be that in 3.6.x `JAXBContext.newInstance()` is called without explicit classloader. Probably that happened during refactoring of `ResourceConfigurationParser`.
* 3.6.3: https://github.com/ehcache/ehcache3/blob/v3.6.3/xml/src/main/java/org/ehcache/xml/ResourceConfigurationParser.java#L61
* 3.5.3: https://github.com/ehcache/ehcache3/blob/v3.5.3/xml/src/main/java/org/ehcache/xml/ConfigurationParser.java#L175

```
javax.xml.bind.JAXBException: "org.ehcache.xml.model" doesnt contain ObjectFactory.class or jaxb.index
	at com.sun.xml.internal.bind.v2.ContextFactory.createContext(ContextFactory.java:266)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:171)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:131)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:356)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:431)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:394)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:298)
	at org.ehcache.xml.ResourceConfigurationParser.<init>(ResourceConfigurationParser.java:61)
	at org.ehcache.xml.ConfigurationParser.<init>(ConfigurationParser.java:173)
	at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:118)
	at org.ehcache.xml.XmlConfiguration.<init>(XmlConfiguration.java:87)
	at org.apache.directory.server.core.api.CacheService.initialize(CacheService.java:141)

```

**Comment by chrisdennis** [comment]
This does indeed look like an oversight.  I believe this should be working okay in current master since I've just revamped a lot of the OSGi related code there.  If you could confirm that master is working okay that would be great.

**Comment by chrisdennis** [comment]
Pretty sure this is working in current master... if you still see the same issue please reopen this and I'll investigate.
