### ISSUE TITLE
java.lang.ClassNotFoundException:org.ehcache.jsr107.EhcacheCachingProvider

### ISSUE THREAD

**Issue by qichangleixin** [ehcache/ehcache3#2646]
I get this excpetion in hibernate:
It worked well at local IDEA,but I used springboot to package it.Unbelievable problem has happened.
```
Caused by: java.lang.ClassNotFoundException: org.ehcache.jsr107.EhcacheCachingPr
ovider
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at javax.cache.Caching$CachingProviderRegistry.loadCachingProvider(Cachi
ng.java:495)
```
pom.xml dependencys:
```
     	<dependency>
		    <groupId>org.springframework.boot</groupId>
		    <artifactId>spring-boot-starter-cache</artifactId>
		</dependency> 
		<dependency>
		 <groupId>javax.cache</groupId>
          <artifactId>cache-api</artifactId>
        </dependency>
        <dependency>
          <groupId>org.ehcache</groupId>
          <artifactId>ehcache</artifactId>
        </dependency>
```
EhcacheCachingProvider exists in ehcache.jar.After packaging,ehcache.jar still exists.But the problem is strange.
please help me.

**Comment by chrisdennis** [comment]
Almost certainly something going wrong in spring-boot when packaging things. Not an Ehcache issue.

**Comment by rusxakep** [comment]
<dependency>
            <groupId>org.ehcache</groupId>
            <artifactId>ehcache</artifactId>
            <classifier>jakarta</classifier>
            <version>${ehcache3.version}</version>
        </dependency>
