### ISSUE TITLE
Terracotta server crashes on synchronization when cluster server active

### ISSUE THREAD

**Issue by rajendarg** [ehcache/ehcache3#2651]
I got the error with version 3.7.1 (cluster api) with 3.7.0 terracotta server

Server A starts (as active)
Server B starts (as passive)
Server A is stopped, B becomes active
Server A is restarted ... server B crashes with above exception when synchronizing

```
2019-05-21 23:08:30,397 [main] INFO com.tc.l2.logging.TCLogbackLogging - Log file: /root/failover-server-logs/terracotta.server.log
2019-05-21 23:08:30,408 INFO - Available Max Runtime Memory: 1822MB
2019-05-21 23:08:30,487 WARN - Running the server in AVAILABILITY mode with the risk of split brain scenarios.
2019-05-21 23:08:30,829 INFO - NodeID[172.16.1.23:9410] joined the cluster
2019-05-21 23:08:30,834 INFO - Moved to State[ PASSIVE-UNINITIALIZED ]
2019-05-21 23:08:30,835 INFO - Moved to State[ PASSIVE-SYNCING ]
2019-05-21 23:08:30,920 INFO - Moved to State[ PASSIVE-STANDBY ]

[root@appserver bin]# 2019-05-21 23:12:35,070 WARN - NodeID[172.16.1.23:9410] left the cluster
2019-05-21 23:12:40,071 INFO - Becoming State[ ACTIVE-COORDINATOR ]
2019-05-21 23:12:40,087 INFO - Starting reconnect window: 120000 ms. Waiting for 1 clients to connect. Unconnected Clients - [ClientID[10]]
2019-05-21 23:12:40,087 INFO - Terracotta Server instance has started up as ACTIVE node on 0:0:0:0:0:0:0:0:9410 successfully, and is now ready for work.
2019-05-21 23:13:18,126 INFO - NodeID[172.16.1.23:9410] joined the cluster
com.tc.exception.TCRuntimeException: Uncaught exception in stage
        at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:307)
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: org.ehcache.clustered.server.internal.messages.EhcacheStateRepoSyncMessage cannot be cast to org.ehcache.clustered.server.internal.messages.EhcacheStateRepoSyncMessage
        at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:611)
        at com.tc.objectserver.entity.ManagedEntityImpl.lambda$sync$22(ManagedEntityImpl.java:1110)
        at com.tc.objectserver.entity.RequestProcessor$EntityRequest.invoke(RequestProcessor.java:194)
        at com.tc.objectserver.entity.RequestProcessor$EntityRequest.run(RequestProcessor.java:185)
        at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:28)
        at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:24)
        at com.tc.async.impl.StageImpl.lambda$null$1(StageImpl.java:105)
        at com.tc.async.impl.MonitoringEventCreator.lambda$createEvent$0(MonitoringEventCreator.java:77)
        at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:284)
Caused by: java.lang.ClassCastException: org.ehcache.clustered.server.internal.messages.EhcacheStateRepoSyncMessage cannot be cast to org.ehcache.clustered.server.internal.messages.EhcacheStateRepoSyncMessage
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.ehcache.clustered.server.store.ClusterTierActiveEntity.synchronizeKeyToPassive(ClusterTierActiveEntity.java:650)
        at com.tc.objectserver.entity.ManagedEntityImpl.performSync(ManagedEntityImpl.java:814)
        at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:590)
        ... 8 more
2019-05-21 23:13:18,534 [WorkerThread(request_processor_during_sync_stage, 0, 0)] INFO org.terracotta.dump - [dump] {
  className=com.tc.async.impl.StageManagerImpl
  monitor=false
  stages=[
    {
      name=single_threaded_fastpath
```

**Comment by chrisdennis** [comment]
If I'm reading your description correctly then this is expected.  The bug fix is server side and it's fixed in 3.7.1. If you're running 3.7.1 clients with 3.7.0 servers then you're not getting the bug fix.

**Comment by rajendarg** [comment]
Thank you for your response, But I didn't find 3.7.1 server kit, only 3.7.0 is available in releases, where I can get terracotta 3.7.1 server?

**Comment by chrisdennis** [comment]
It looks like some steps were missed when the 3.7.1 release was cut.  I'm chasing that up at the moment. In the meantime you can find the 3.7.1 kit here: https://repo1.maven.org/maven2/org/ehcache/ehcache-clustered/3.7.1/

**Comment by rajendarg** [comment]
thank you very much that solved the issue
