### ISSUE TITLE
ehcache clustered in osgi works only with 1st installation

### ISSUE THREAD

**Issue by mkovacek** [ehcache/ehcache3#2665]
Having troubles with clustered ehcache in osgi/aem. Only with first project build/installation it works fine, but with second build/installation it stops working, generate a lot of errors. It looks like terracotta connection, cachemanager or something third is not properly closed.

More details here
https://stackoverflow.com/questions/56727761/ehcache-clustered-not-working-in-osgi-when-project-is-installed-several-times

Did I miss some dependencies or import packages? Do you have some example how pom.xml should look like for osgi?

```
23.06.2019 21:40:37.162 *INFO* [BasicConnectionReader-/127.0.0.1:56840<-localhost/127.0.0.1:9410] com.tc.object.DistributedObjectClient closing down Terracotta Connection force=false channel=ChannelID=[860] client=ClientID[860]
23.06.2019 21:40:37.162 *INFO* [BasicConnectionReader-/127.0.0.1:56840<-localhost/127.0.0.1:9410] com.tc.cluster.ClientChannelEventController Got channel event - type: TRANSPORT_CLOSED_EVENT, event: com.tc.net.protocol.tcm.ChannelEventImpl@1137694871[type = TRANSPORT_CLOSED_EVENT, timestamp = Sun Jun 23 21:40:37 CEST 2019, channel  = ChannelID=[860]:0.0.0.0:56840 <--> 127.0.0.1:9410 product  : Permanent
23.06.2019 21:40:37.162 *INFO* [BasicConnectionReader-/127.0.0.1:56840<-localhost/127.0.0.1:9410] com.tc.cluster.ClientChannelEventController Got channel event - type: CHANNEL_CLOSED_EVENT, event: com.tc.net.protocol.tcm.ChannelEventImpl@1206928438[type = CHANNEL_CLOSED_EVENT, timestamp = Sun Jun 23 21:40:37 CEST 2019, channel  = ChannelID=[860]:0.0.0.0:56840 <--> 127.0.0.1:9410 product  : Permanent
23.06.2019 21:40:37.162 *INFO* [OsgiInstallerImpl] org.ehcache.clustered.client.internal.service.ConnectionState Disconnected from the server
org.terracotta.exception.ConnectionClosedException: Entity: org.ehcache.clustered.client.internal.lock.VoltronReadWriteLockClient:VoltronReadWriteLock-ClusterTierManagerClientEntityFactory-AccessLock-clustered Connection closed under in-flight message
	at com.tc.object.ClientEntityManagerImpl.throwClosedExceptionOnMessage(ClientEntityManagerImpl.java:385)
	at com.tc.object.ClientEntityManagerImpl.shutdown(ClientEntityManagerImpl.java:366)
	at com.tc.object.handshakemanager.ClientHandshakeManagerImpl.shutdownCallbacks(ClientHandshakeManagerImpl.java:182)
	at com.tc.object.handshakemanager.ClientHandshakeManagerImpl.shutdown(ClientHandshakeManagerImpl.java:85)
	at com.tc.object.ClientShutdownManager.closeLocalWork(ClientShutdownManager.java:82)
	at com.tc.object.ClientShutdownManager.execute(ClientShutdownManager.java:75)
	at com.tc.object.DistributedObjectClient.shutdownClient(DistributedObjectClient.java:697)
	at com.tc.object.DistributedObjectClient.shutdown(DistributedObjectClient.java:715)
	at com.tc.object.DistributedObjectClient.shutdown(DistributedObjectClient.java:524)
	at com.tc.object.DistributedObjectClient$4.notifyChannelEvent(DistributedObjectClient.java:290)
	at com.tc.net.protocol.tcm.AbstractMessageChannel.fireEvent(AbstractMessageChannel.java:271)
	at com.tc.net.protocol.tcm.AbstractMessageChannel.notifyTransportClosed(AbstractMessageChannel.java:240)
	at com.tc.net.protocol.tcm.ClientMessageChannelImpl.notifyTransportClosed(ClientMessageChannelImpl.java:164)
	at com.tc.net.protocol.transport.ConnectionWatcher.notifyTransportClosed(ConnectionWatcher.java:54)
	at com.tc.net.protocol.transport.AbstractMessageTransport.fireTransportEvent(AbstractMessageTransport.java:123)
	at com.tc.net.protocol.transport.AbstractMessageTransport.fireTransportClosedEvent(AbstractMessageTransport.java:100)
	at com.tc.net.protocol.transport.MessageTransportBase.terminate(MessageTransportBase.java:174)
	at com.tc.net.protocol.transport.MessageTransportBase.close(MessageTransportBase.java:148)
	at com.tc.net.protocol.transport.ClientMessageTransport.close(ClientMessageTransport.java:51)
	at com.tc.net.protocol.tcm.AbstractMessageChannel.close(AbstractMessageChannel.java:151)
	at com.tc.net.protocol.tcm.ClientMessageChannelImpl.close(ClientMessageChannelImpl.java:52)
	at com.tc.net.protocol.tcm.TCMessageHydrateAndConvertSink.putMessage(TCMessageHydrateAndConvertSink.java:50)
	at com.tc.net.protocol.tcm.TCMessageRouterImpl.putMessage(TCMessageRouterImpl.java:64)
	at com.tc.net.protocol.tcm.AbstractMessageChannel.receive(AbstractMessageChannel.java:215)
	at com.tc.net.protocol.transport.MessageTransportBase.receiveToReceiveLayer(MessageTransportBase.java:134)
	at com.tc.net.protocol.transport.ClientMessageTransport.receiveTransportMessageImpl(ClientMessageTransport.java:270)
	at com.tc.net.protocol.transport.MessageTransportBase.receiveTransportMessage(MessageTransportBase.java:112)
	at com.tc.net.protocol.transport.ClientMessageTransport$1.putMessage(ClientMessageTransport.java:462)
	at com.tc.net.protocol.transport.WireProtocolAdaptorImpl.addReadData(WireProtocolAdaptorImpl.java:75)
	at com.tc.net.basic.BasicConnection.lambda$readMessages$3(BasicConnection.java:298)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
23.06.2019 21:40:37.167 *INFO* [Connection Maker - f93a030074e2486d911a314c1e777bd0] com.tc.cluster.ClientChannelEventController Got channel event - type: TRANSPORT_CONNECTED_EVENT, event: com.tc.net.protocol.tcm.ChannelEventImpl@1486408836[type = TRANSPORT_CONNECTED_EVENT, timestamp = Sun Jun 23 21:40:37 CEST 2019, channel  = ChannelID=[861]:127.0.0.1:56841 <--> 127.0.0.1:9410 product  : Permanent
23.06.2019 21:40:37.167 *INFO* [Connection Maker - f93a030074e2486d911a314c1e777bd0] com.tc.net.protocol.transport.ClientMessageTransport ConnectionID(861.73cf4115ac334b69911548d9a4be155a.4f4bec0b-c1ce-4214-9e19-e3373e8e53f3-16b83ffd124.Permanent): Handshake is complete
23.06.2019 21:40:37.167 *INFO* [Connection Maker - f93a030074e2486d911a314c1e777bd0] com.tc.cluster.ClientChannelEventController Got channel event - type: CHANNEL_OPENED_EVENT, event: com.tc.net.protocol.tcm.ChannelEventImpl@496654835[type = CHANNEL_OPENED_EVENT, timestamp = Sun Jun 23 21:40:37 CEST 2019, channel  = ChannelID=[861]:127.0.0.1:56841 <--> 127.0.0.1:9410 product  : Permanent
23.06.2019 21:40:37.167 *INFO* [Connection Maker - f93a030074e2486d911a314c1e777bd0] com.tc.object.DistributedObjectClient Connection successfully established to server at 127.0.0.1:9410
23.06.2019 21:40:37.167 *INFO* [OsgiInstallerImpl] org.terracotta.lease.LeaseMaintainerFactory Creating LeaseMaintainer for connection: com.terracotta.connection.TerracottaConnection@62295c00
23.06.2019 21:40:37.168 *INFO* [OsgiInstallerImpl] org.ehcache.clustered.client.internal.service.ConnectionState New connection to server is established, reconnect count is 850
23.06.2019 21:40:37.169 *ERROR* [BasicConnectionReader-/127.0.0.1:56841<-localhost/127.0.0.1:9410] com.tc.net.protocol.tcm.TCMessageHydrateAndConvertSink Error hydrating message of type VOLTRON_ENTITY_COMPLETED_RESPONSE
java.lang.UnsupportedOperationException: Deserialization not allowed for class org.terracotta.exception.EntityAlreadyExistsException (on Sun Jun 23 21:40:37 CEST 2019)
	at org.kantega.notsoserial.DefaultNotSoSerial.preventDeserialization(DefaultNotSoSerial.java:256)
	at org.kantega.notsoserial.DefaultNotSoSerial.onBeforeResolveClass(DefaultNotSoSerial.java:248)
	at org.kantega.notsoserial.ObjectInputStreamClassVisitor.onBeforeResolveClass(ObjectInputStreamClassVisitor.java:48)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1859)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1745)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2033)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1567)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
	at com.tc.entity.VoltronEntityAppliedResponseImpl.hydrateValue(VoltronEntityAppliedResponseImpl.java:143)
	at com.tc.net.protocol.tcm.TCMessageImpl.hydrate(TCMessageImpl.java:177)
	at com.tc.net.protocol.tcm.TCMessageHydrateAndConvertSink.putMessage(TCMessageHydrateAndConvertSink.java:39)
	at com.tc.net.protocol.tcm.TCMessageRouterImpl.putMessage(TCMessageRouterImpl.java:64)
	at com.tc.net.protocol.tcm.AbstractMessageChannel.receive(AbstractMessageChannel.java:215)
	at com.tc.net.protocol.transport.MessageTransportBase.receiveToReceiveLayer(MessageTransportBase.java:134)
	at com.tc.net.protocol.transport.ClientMessageTransport.receiveTransportMessageImpl(ClientMessageTransport.java:270)
	at com.tc.net.protocol.transport.MessageTransportBase.receiveTransportMessage(MessageTransportBase.java:112)
	at com.tc.net.protocol.transport.ClientMessageTransport$1.putMessage(ClientMessageTransport.java:462)
	at com.tc.net.protocol.transport.WireProtocolAdaptorImpl.addReadData(WireProtocolAdaptorImpl.java:75)
	at com.tc.net.basic.BasicConnection.lambda$readMessages$3(BasicConnection.java:298)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
23.06.2019 21:40:37.169 *INFO* [BasicConnectionReader-/127.0.0.1:56841<-localhost/127.0.0.1:9410] com.tc.object.DistributedObjectClient closing down Terracotta Connection force=false channel=ChannelID=[861] client=ClientID[861]
23.06.2019 21:40:37.169 *INFO* [BasicConnectionReader-/127.0.0.1:56841<-localhost/127.0.0.1:9410] com.tc.cluster.ClientChannelEventController Got channel event - type: TRANSPORT_CLOSED_EVENT, event: com.tc.net.protocol.tcm.ChannelEventImpl@655583679[type = TRANSPORT_CLOSED_EVENT, timestamp = Sun Jun 23 21:40:37 CEST 2019, channel  = ChannelID=[861]:0.0.0.0:56841 <--> 127.0.0.1:9410 product  : Permanent
23.06.2019 21:40:37.169 *INFO* [BasicConnectionReader-/127.0.0.1:56841<-localhost/127.0.0.1:9410] com.tc.cluster.ClientChannelEventController Got channel event - type: CHANNEL_CLOSED_EVENT, event: com.tc.net.protocol.tcm.ChannelEventImpl@590145925[type = CHANNEL_CLOSED_EVENT, timestamp = Sun Jun 23 21:40:37 CEST 2019, channel  = ChannelID=[861]:0.0.0.0:56841 <--> 127.0.0.1:9410 product  : Permanent
23.06.2019 21:40:37.169 *INFO* [OsgiInstallerImpl] org.ehcache.clustered.client.internal.service.ConnectionState Disconnected from the server
org.terracotta.exception.ConnectionClosedException: Entity: org.ehcache.clustered.client.internal.lock.VoltronReadWriteLockClient:VoltronReadWriteLock-ClusterTierManagerClientEntityFactory-AccessLock-clustered Connection closed under in-flight message

==========

23.06.2019 22:00:20.338 *INFO* [ConnectionEstablisher-[localhost:9410]-547381477] com.tc.net.protocol.transport.ClientMessageTransport ConnectionID(1054.f0582996dd1340b0a05dc5fd10a863e7.4f4bec0b-c1ce-4214-9e19-e3373e8e53f3-16b83ffd124.Permanent): Reconnect attempt 20 to localhost:9410
23.06.2019 22:00:29.998 *INFO* [sling-default-263-Registered Service.1033] com.adobe.granite.taskmanagement.impl.jcr.TaskArchiveService archiving tasks at: 'Sun Jun 23 22:00:29 CEST 2019'
23.06.2019 22:00:40.607 *INFO* [ConnectionEstablisher-[localhost:9410]-547381477] com.tc.net.protocol.transport.ClientMessageTransport ConnectionID(1054.f0582996dd1340b0a05dc5fd10a863e7.4f4bec0b-c1ce-4214-9e19-e3373e8e53f3-16b83ffd124.Permanent): Reconnect attempt 40 to localhost:9410
23.06.2019 22:01:00.674 *INFO* [ConnectionEstablisher-[localhost:9410]-547381477] com.tc.net.protocol.transport.ClientMessageTransport ConnectionID(1054.f0582996dd1340b0a05dc5fd10a863e7.4f4bec0b-c1ce-4214-9e19-e3373e8e53f3-16b83ffd124.Permanent): Reconnect attempt 60 to localhost:9410

==========
23.06.2019 22:02:18.917 *INFO* [LeaseExpiryConnectionKillingThread] org.terracotta.lease.LeaseExpiryConnectionKillingThread Lease lost, so closing connection to server: [ LeaseImpl: startOfContiguousLeasedPeriod: 99847794102376 leaseExpiry: 99997793676778 ]
23.06.2019 22:02:18.917 *INFO* [LeaseExpiryConnectionKillingThread] org.terracotta.lease.LeaseExpiryConnectionKillingThread Lease lost, so closing connection to server: [ LeaseImpl: startOfContiguousLeasedPeriod: 99847687955424 leaseExpiry: 99997687609464 ]
23.06.2019 22:02:18.917 *INFO* [LeaseExpiryConnectionKillingThread] org.terracotta.lease.LeaseExpiryConnectionKillingThread Lease lost, so closing connection to server: [ LeaseImpl: startOfContiguousLeasedPeriod: 99847849467287 leaseExpiry: 99997849005237 ]
23.06.2019 22:02:18.924 *INFO* [LeaseExpiryConnectionKillingThread] org.terracotta.lease.LeaseExpiryConnectionKillingThread Lease lost, so closing connection to server: [ LeaseImpl: startOfContiguousLeasedPeriod: 99847777793083 leaseExpiry: 99997777444935 ]

```

**Comment by chrisdennis** [comment]
Sorry... somehow my GitHub notification for this got filtered in to my junk mail. I've been trying to improve the OSGi support so I'll try to have a dig in to this later this week (perhaps tomorrow).

**Comment by mkovacek** [comment]
No probs, so title of issue is wrong. This errors happens when you try to execute more than once the basic code. If you need some additional info, logs, just ask. 

`
    LOGGER.info("Creating clustered cache manager from XML");

    URL myUrl = ClusteredService.class.getResource("/com/myco/services/ehcache-clustered-local2.xml");
    Configuration xmlConfig = new XmlConfiguration(myUrl);

    try (CacheManager cacheManager = CacheManagerBuilder.newCacheManager(xmlConfig) ) {
        cacheManager.init();

        org.ehcache.Cache<String, String> basicCache = cacheManager.getCache("basicCache4", String.class, String.class);

        LOGGER.info("1. Putting to cache");
        basicCache.put("1","abc");

        LOGGER.info("1. Getting from cache");
        String value = basicCache.get("1");
        LOGGER.info("1. Retrieved '{}'", value);

        LOGGER.info("cache manager status, " + cacheManager.getStatus().toString());

    }`

**Comment by wellenfront** [comment]
Is there any update on this topic or a plan to fix it? 
We would really love to include clustered ehcache in our osgi implementation and are waiting for this to be fixed.

**Comment by jitendra-nalwaya** [comment]
Apologies for too late response.
We observe that "UnsupportedOperationException: Deserialization not allowed for class org.terracotta.exception.EntityAlreadyExistsException" in logs.

 java.lang.UnsupportedOperationException: Deserialization not allowed for class org.terracotta.exception.EntityAlreadyExistsException (on Sun Jun 23 21:40:37 CEST 2019)
    at org.kantega.notsoserial.DefaultNotSoSerial.preventDeserialization(DefaultNotSoSerial.java:256)
    at org.kantega.notsoserial.DefaultNotSoSerial.onBeforeResolveClass(DefaultNotSoSerial.java:248)
    at org.kantega.notsoserial.ObjectInputStreamClassVisitor.onBeforeResolveClass(ObjectInputStreamClassVisitor.java:48)

It looks failing to deserialize, so you need to whitelist deserialization of this type.

**Comment by jitendra-nalwaya** [comment]
Please follow the solution in the previous comment. Hope that should resolve the issue. Closing the ticket.
