### ISSUE TITLE
Springboot issue with @EnableCaching

### ISSUE THREAD

**Issue by maghibus** [ehcache/ehcache3#2714]
Hi,

- ISSUE: 
  Spring application failed to start with the following error:

```
2019-10-29 17:46:01.385 ERROR 7596 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Exception starting filter [ljsaProfileManagerFilter]

java.lang.NullPointerException: null
	at org.springframework.web.filter.GenericFilterBean.init(GenericFilterBean.java:241) ~[spring-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:270) ~[tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:106) ~[tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4533) [tomcat-embed-core-9.0.27.jar:9.0.27]
```

- Environment:
     SpringBoot 2.2.0.RELEASE
     Ehcache 3.8.1

- Java
```java
public class LjsaProfileManagerFilter  extends OncePerRequestFilter{

...
 
    @Override
    protected UsernamePasswordAuthenticationToken giveMePrincipal(HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse, LjsaUserDTO ljsaUserDTO) {

        ProfileDTO profileDTO = getCachedProfile(ljsaUserDTO.getUsername(), (List<String>) ljsaUserDTO.getGroups(), (List<String>) ljsaUserDTO.getRoles() );
    
      ...
    }

    @Cacheable(value = "profileCache", key = "#userid")
    public ProfileDTO getCachedProfile(String userid, List<String> wso2groups, List<String> wso2roles) {
            ResponseEntity<ProfileDTO> profileUsingGET = profileControllerApiClient
                .getProfileUsingGET(request.getHeader("X-Auth-Token"), wso2groups, userManagerId, wso2roles);
            return  profileUsingGET.getBody();
    }
 ...

@EnableCaching
public class UserManagerBoot {
    public static void main(String[] args) {
        SpringApplication.run(UserManagerBoot.class, args);
    }
}
```

``` xml
<config
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xmlns='http://www.ehcache.org/v3'
  xsi:schemaLocation="http://www.ehcache.org/v3 http://www.ehcache.org/schema/ehcache-core.xsd">

  <cache alias="profileCache">
    <key-type>java.lang.String</key-type>
    <value-type>ProfileDTO</value-type>
    <resources>
      <heap unit="entries">20</heap>
      <offheap unit="MB">10</offheap>
    </resources>
  </cache>

</config>

```
spring.cache.jcache.config=classpath:ehcache.xml

- Workaround:
With Programmatic configuration it works !!! 
What's the matter with XML configuration ?
Thanks

**Comment by chrisdennis** [comment]
The stack trace you quote seems to point at something other than Ehcache:

https://github.com/spring-projects/spring-framework/blob/v5.2.0.RELEASE/spring-web/src/main/java/org/springframework/web/filter/GenericFilterBean.java#L241
```java
if (logger.isDebugEnabled()) {
	logger.debug("Filter '" + filterConfig.getFilterName() + "' configured for use");
}
```

Right now I'm thinking this is either and environmental or maybe a Spring issue?

**Comment by maghibus** [comment]
Deleting @EnableCaching from bootstrap  springboot runs, without caching.

**Comment by chrisdennis** [comment]
It's hard to tell without seeing the full project but trawling around the internet suggest you might be seeing something like this: https://github.com/spring-projects/spring-boot/issues/8605

**Comment by maghibus** [comment]
I'll try this remedy,
Thank you

**Comment by maghibus** [comment]
I moved the method annotated with the ** @Cachable** annotation to a Service  and works satisfactorily.
Thank you
