### ISSUE TITLE
Does ehcache3.x support openjdk?

### ISSUE THREAD

**Issue by RockeyCui** [ehcache/ehcache3#2726]
env ==>

openjdk-1.8.0.102-4.b14.el7.x86_64
ehcache3.8.0

code ==>

```java
public class AllCache extends AbstractCache<String, Row> {
    private static final long serialVersionUID = -3639314692125067324L;

    private PersistentUserManagedCache<String, Row> cache;
    private String tempDir;
    private LocalPersistenceService persistenceService;

    public AllCache(CacheInfo cacheInfo) {
        super(cacheInfo);
    }

    @Override
    public void init() {
        tempDir = System.getProperty("java.io.tmpdir") + File.separator
                + cacheInfo.getCacheTmpDir() + File.separator
                + UUID.randomUUID().toString() + File.separator
                + Thread.currentThread().getId();
        persistenceService = new DefaultLocalPersistenceService(
                new DefaultPersistenceConfiguration(new File(tempDir)));
        cache = UserManagedCacheBuilder.newUserManagedCacheBuilder(String.class, Row.class)
                .with(new UserManagedPersistenceContext<>("persistentCache", persistenceService))
                .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder()
                        .heap(cacheInfo.getCacheMaxMb(), MemoryUnit.MB)
                        .disk(10, MemoryUnit.GB, false)
                ).build(true);
    }

    @Override
    public Row get(String key) {
        return cache.get(key);
    }

    @Override
    public void put(String key, Row value) {
        cache.put(key, value);
    }

    @Override
    public void putAll(Map<String, Row> data) {
        cache.putAll(data);
    }

    @Override
    public void close() {
        try {
            cache.close();
            cache.destroy();
            persistenceService.stop();
            FileUtils.deleteDirectory(new File(tempDir));
        } catch (Exception ignore) {
        }
    }
}
```

expection ==>
```
Caused by: java.lang.IllegalStateException: org.ehcache.core.spi.ServiceLocator$DependencyException: Failed to find provider with satisfied dependency set for interface org.ehcache.core.spi.store.Store$Provider [candidates [org.ehcache.impl.internal.store.heap.OnHeapStoreProviderFactory@5a58dd22, org.ehcache.impl.internal.store.offheap.OffHeapStoreProviderFactory@4d766540, org.ehcache.impl.internal.store.disk.OffHeapDiskStoreProviderFactory@784d016d, org.ehcache.impl.internal.store.tiering.TieredStoreProviderFactory@25b63026, org.ehcache.impl.internal.store.loaderwriter.LoaderWriterStoreProviderFactory@776ed22b]]
 at org.ehcache.core.spi.ServiceLocator$DependencySet.build(ServiceLocator.java:350)
 at org.ehcache.config.builders.UserManagedCacheBuilder.build(UserManagedCacheBuilder.java:179)
 ... 15 more
Caused by: org.ehcache.core.spi.ServiceLocator$DependencyException: Failed to find provider with satisfied dependency set for interface org.ehcache.core.spi.store.Store$Provider [candidates [org.ehcache.impl.internal.store.heap.OnHeapStoreProviderFactory@5a58dd22, org.ehcache.impl.internal.store.offheap.OffHeapStoreProviderFactory@4d766540, org.ehcache.impl.internal.store.disk.OffHeapDiskStoreProviderFactory@784d016d, org.ehcache.impl.internal.store.tiering.TieredStoreProviderFactory@25b63026, org.ehcache.impl.internal.store.loaderwriter.LoaderWriterStoreProviderFactory@776ed22b]]
 at org.ehcache.core.spi.ServiceLocator$DependencySet.lookupService(ServiceLocator.java:401)
 at org.ehcache.core.spi.ServiceLocator$DependencySet.build(ServiceLocator.java:322)
 ... 16 more
```

**Comment by chrisdennis** [comment]
Yes this should work fine and your code works fine locally for me. Could you maybe describe your environment in more detail... maybe something is going wrong there that is tripping things up. Thing thats might be interesting are:
* Operating System
* Which Ehcache Jars are on the classpath.
* Classloader environment: are you running in Tomcat or another JavaEE container for example?

**Comment by chrisdennis** [comment]
Closing... please reopen if you have further questions.
