### ISSUE TITLE
Ehcache keys in possible inconsistent state

### ISSUE THREAD

**Issue by Joepher** [ehcache/ehcache3#2729]
While trying to getAll elements from cache, an error occured:**Ehcache keys in possible inconsistent state**

ehcache version: ehcache-3.5.0

ehcache configuration:
```
<ehcache:persistence directory="user.dir"/>
<ehcache:cache-template name="CACHE_TEMPLATE">
  <ehcache:expiry>
    <ehcache:tti unit="minutes">120</ehcache:tti>
  </ehcache:expiry>
  <ehcache:resources>
    <ehcache:heap unit="entries">10000</ehcache:heap>
    <ehcache:disk unit="MB">1024</ehcache:disk>
  </ehcache:resources>
</ehcache:cache-template>

<ehcache:cache alias="taskInfoCache" uses-template="CACHE_TEMPLATE">
  <ehcache:key-type>java.lang.Integer</ehcache:key-type>
  <ehcache:value-type>com.***.TaskInfo</ehcache:value-type>
</ehcache:cache>
```

My code:
`Map<Integer,TaskInfo> map = cache.getAll(taskSet);`

Below is the log:

[org.ehcache.core.internal.resilience.AbstractResilienceStrategy 190] Ehcache keys [143506, 143507] in possible inconsistent state - Similar messages will be suppressed for 30 seconds org.ehcache.spi.resilience.StoreAccessException: java.lang.reflect.UndeclaredThrowableException
	at org.ehcache.core.exceptions.StorePassThroughException.handleException(StorePassThroughException.java:78)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.computeWithRetry(AbstractOffHeapStore.java:966)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.internalComputeIfAbsent(AbstractOffHeapStore.java:644)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.computeIfAbsent(AbstractOffHeapStore.java:599)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.bulkComputeIfAbsent(AbstractOffHeapStore.java:735)
	at org.ehcache.impl.internal.store.tiering.TieredStore.bulkComputeIfAbsent(TieredStore.java:281)
	at org.ehcache.core.Ehcache.doGetAllInternal(Ehcache.java:94)
	at org.ehcache.core.EhcacheBase.getAllInternal(EhcacheBase.java:348)
	at org.ehcache.core.EhcacheBase.getAll(EhcacheBase.java:334)
	...
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy123.equals(Unknown Source)
	at org.terracotta.offheapstore.storage.PortabilityBasedStorageEngine.equalsKey(PortabilityBasedStorageEngine.java:125)
	at org.terracotta.offheapstore.OffHeapHashMap.keyEquals(OffHeapHashMap.java:993)
	at org.terracotta.offheapstore.OffHeapHashMap.computeWithMetadata(OffHeapHashMap.java:1949)
	at org.terracotta.offheapstore.AbstractLockedOffHeapHashMap.computeWithMetadata(AbstractLockedOffHeapHashMap.java:582)
	at org.terracotta.offheapstore.concurrent.AbstractConcurrentOffHeapMap.computeWithMetadata(AbstractConcurrentOffHeapMap.java:725)
	at org.ehcache.impl.internal.store.disk.EhcachePersistentConcurrentOffHeapClockCache.compute(EhcachePersistentConcurrentOffHeapClockCache.java:158)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.computeWithRetry(AbstractOffHeapStore.java:951)
	... 51 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ehcache.impl.internal.store.disk.OffHeapDiskStore.lambda$persistent$0(OffHeapDiskStore.java:513)
	... 59 more
Caused by: java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:361)
	at org.ehcache.impl.serialization.IntegerSerializer.read(IntegerSerializer.java:62)
	at org.ehcache.impl.serialization.IntegerSerializer.equals(IntegerSerializer.java:70)
	at org.ehcache.impl.serialization.IntegerSerializer.equals(IntegerSerializer.java:27)
	at org.ehcache.impl.internal.store.offheap.portability.SerializerPortability.equals(SerializerPortability.java:56)
	... 63 more

**Comment by BalajiSasank** [comment]
@Joepher. Can you tell us how did you solve this?
