### ISSUE TITLE
IOException while attempting to extend file 

### ISSUE THREAD

**Issue by cdalexndr** [ehcache/ehcache3#2799]
**EhCache 3.8.1**

Originally this was reported back in 2017 https://groups.google.com/forum/#!topic/ehcache-users/QpelMYURf4k, and led to opening https://github.com/Terracotta-OSS/offheap-store/issues/49.

An interrupted thread cannot write to cache disk store. This leads to missing cache entries.
```
5:05:02.121 [Thread-0] WARN org.ehcache.shadow.org.terracotta.offheapstore.disk.paging.MappedPageSource - IOException while attempting to extend file C:\Developer\issues\spring-issues\ehcache-issue\.\cache\file\test_a94a8fe5ccb19ba61c4c0873d391e987982fbbd3\offheap-disk-store\ehcache-disk-store.data
java.nio.channels.ClosedByInterruptException: null
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162)
	at java.base/sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:388)
	at org.ehcache.shadow.org.terracotta.offheapstore.disk.paging.MappedPageSource.allocateRegion(MappedPageSource.java:104)
	at org.ehcache.shadow.org.terracotta.offheapstore.disk.storage.FileBackedStorageEngine$FileChunk.<init>(FileBackedStorageEngine.java:505)
	at org.ehcache.shadow.org.terracotta.offheapstore.disk.storage.FileBackedStorageEngine.writeMappingBuffers(FileBackedStorageEngine.java:318)
	at org.ehcache.shadow.org.terracotta.offheapstore.storage.PortabilityBasedStorageEngine.writeMapping(PortabilityBasedStorageEngine.java:65)
	at org.ehcache.shadow.org.terracotta.offheapstore.OffHeapHashMap.tryWriteEntry(OffHeapHashMap.java:692)
	at org.ehcache.shadow.org.terracotta.offheapstore.OffHeapHashMap.writeEntry(OffHeapHashMap.java:676)
	at org.ehcache.shadow.org.terracotta.offheapstore.OffHeapHashMap.computeWithMetadata(OffHeapHashMap.java:1944)
	at org.ehcache.shadow.org.terracotta.offheapstore.AbstractLockedOffHeapHashMap.computeWithMetadata(AbstractLockedOffHeapHashMap.java:520)
	at org.ehcache.shadow.org.terracotta.offheapstore.concurrent.AbstractConcurrentOffHeapMap.computeWithMetadata(AbstractConcurrentOffHeapMap.java:725)
	at org.ehcache.impl.internal.store.disk.EhcachePersistentConcurrentOffHeapClockCache.compute(EhcachePersistentConcurrentOffHeapClockCache.java:158)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.computeWithRetry(AbstractOffHeapStore.java:1031)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.put(AbstractOffHeapStore.java:250)
	at org.ehcache.core.Ehcache.doPut(Ehcache.java:94)
	at org.ehcache.core.EhcacheBase.put(EhcacheBase.java:189)
	at org.ehcache.jsr107.Eh107Cache.put(Eh107Cache.java:175)
	at example.CacheTest.lambda$testInterrupt$0(CacheTest.java:47)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Reproductible test repository: https://github.com/cdalexndr/ehcache-issue

**Comment by chrisdennis** [comment]
This is likely fixed by: https://github.com/Terracotta-OSS/offheap-store/pull/61

If this is reproducible with the latest release please reopen this issue.
