### ISSUE TITLE
JDK11 with --illegal-access=deny cause InaccessibleObjectException

### ISSUE THREAD

**Issue by zeitiger** [ehcache/ehcache3#2849]
```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field final byte[] java.nio.ByteBuffer.hb accessible: module java.base does not "opens java.nio" to unnamed module @2f1f80b3
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340) ~[na:na]
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280) ~[na:na]
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176) ~[na:na]
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:170) ~[na:na]
	at org.ehcache.sizeof.ObjectGraphWalker.getAllFields(ObjectGraphWalker.java:275) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.sizeof.ObjectGraphWalker.getFilteredFields(ObjectGraphWalker.java:234) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.sizeof.ObjectGraphWalker.walk(ObjectGraphWalker.java:176) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.sizeof.SizeOf.deepSizeOf(SizeOf.java:71) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.sizeof.DefaultSizeOfEngine.sizeof(DefaultSizeOfEngine.java:52) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.heap.OnHeapStore.getSizeOfKeyValuePairs(OnHeapStore.java:982) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.heap.OnHeapStore.makeValue(OnHeapStore.java:1527) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.heap.OnHeapStore.makeValue(OnHeapStore.java:1514) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.heap.OnHeapStore.newCreateValueHolder(OnHeapStore.java:1465) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.heap.OnHeapStore.lambda$put$6(OnHeapStore.java:346) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.heap.KeyCopyBackend.lambda$compute$1(KeyCopyBackend.java:154) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1934) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.heap.KeyCopyBackend.compute(KeyCopyBackend.java:154) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.heap.OnHeapStore.put(OnHeapStore.java:334) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	... 129 common frames omitted
```

**Comment by chrisdennis** [comment]
If you want to use memory based sizing units for the in-heap caches then you'll need to open up the JDK to allow Ehcache to walk the complete object graph so that it can size the stored objects. There isn't really a practical way around this at the moment.

**Comment by zeitiger** [comment]
Ok, good to know. 

Additional for others that run into this issue. 
`--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED` is a workaround for this issue.

Maybe in future it's possible reduce this opening to only ehcache? (I'm new in this JPMS stuff)

**Comment by chrisdennis** [comment]
Ehcache isn't currently a 'real' module... you should be able to make it an auto-module by putting the jar on the module-path rather than the classpath though. That should allow you to open things to only the Ehcache auto-module rather than everything.
