### ISSUE TITLE
java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by cdalexndr** [ehcache/ehcache3#2908]
EhCache 3.8.1

Multi-thread environment.

Stacktrace:
```
java.lang.RuntimeException:  java.nio.channels.ClosedChannelException
	at org.ehcache.shadow.org.terracotta.offheapstore.disk.storage.FileBackedStorageEngine$FileChunk$1.setLong(FileBackedStorageEngine.java:675) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.offheap.LazyOffHeapValueHolder.writeBack(LazyOffHeapValueHolder.java:82) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.lambda$flush$16(AbstractOffHeapStore.java:869) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.disk.EhcachePersistentConcurrentOffHeapClockCache.lambda$computeIfPinned$3(EhcachePersistentConcurrentOffHeapClockCache.java:213) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.shadow.org.terracotta.offheapstore.OffHeapHashMap.computeIfPresentWithMetadata(OffHeapHashMap.java:2108) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.shadow.org.terracotta.offheapstore.AbstractLockedOffHeapHashMap.computeIfPresentWithMetadata(AbstractLockedOffHeapHashMap.java:542) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.shadow.org.terracotta.offheapstore.concurrent.AbstractConcurrentOffHeapMap.computeIfPresentWithMetadata(AbstractConcurrentOffHeapMap.java:781) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.disk.EhcachePersistentConcurrentOffHeapClockCache.computeIfPinned(EhcachePersistentConcurrentOffHeapClockCache.java:210) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.flush(AbstractOffHeapStore.java:862) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.heap.OnHeapStore.lambda$setInvalidationListener$19(OnHeapStore.java:956) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.heap.OnHeapStore.lambda$evict$28(OnHeapStore.java:1594) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.concurrent.ConcurrentHashMap.computeIfPresent(ConcurrentHashMap.java:1848) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.heap.SimpleBackend.computeIfPresent(SimpleBackend.java:130) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.heap.OnHeapStore.evict(OnHeapStore.java:1589) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.heap.OnHeapStore.enforceCapacity(OnHeapStore.java:1556) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.heap.OnHeapStore.resolveFault(OnHeapStore.java:787) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.heap.OnHeapStore.getOrComputeIfAbsent(OnHeapStore.java:707) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.impl.internal.store.tiering.TieredStore.get(TieredStore.java:87) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.core.Ehcache.doGet(Ehcache.java:90) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.core.EhcacheBase.get(EhcacheBase.java:127) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.jsr107.Eh107Cache.get_aroundBody0(Eh107Cache.java:90) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.jsr107.Eh107Cache$AjcClosure1.run(Eh107Cache.java:1) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
...
Caused by: java.nio.channels.ClosedChannelException: null
	at java.base/sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:150) ~[na:na]
	at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:830) ~[na:na]
	at org.ehcache.shadow.org.terracotta.offheapstore.disk.storage.FileBackedStorageEngine.writeBufferToChannel(FileBackedStorageEngine.java:393) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.shadow.org.terracotta.offheapstore.disk.storage.FileBackedStorageEngine.writeLongToChannel(FileBackedStorageEngine.java:388) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.shadow.org.terracotta.offheapstore.disk.storage.FileBackedStorageEngine.access$700(FileBackedStorageEngine.java:60) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	at org.ehcache.shadow.org.terracotta.offheapstore.disk.storage.FileBackedStorageEngine$FileChunk$1.setLong(FileBackedStorageEngine.java:673) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
	... 169 common frames omitted
```

Related stackoverflow: https://stackoverflow.com/questions/56373698/closedchannelexception-exception-when-using-ehcache

**Comment by chrisdennis** [comment]
Yes I think there is a hole here. I'll file a bug in offheap-store where the issue needs fixing shortly and a PR will follow.

**Comment by chrisdennis** [comment]
https://github.com/Terracotta-OSS/offheap-store/pull/73

**Comment by cdalexndr** [comment]
That was fast! 

This issue is problematic because it leaves the cache in an unrecoverable invalid state, throwing exceptions. 
These exceptions can propagate to the mvc controller returning an error page to the client.

**Comment by chrisdennis** [comment]
I can't see enough of your stack trace to know if this is practical, but I you may be able to reduce the chances of this happening by recording before and then reasserting thread interrupts after every cache operation, i.e.:
```java
boolean interrupted = Thread.interrupted();
try {
  //do cache operation
} finally {
  if (interrupted) {
    Thread.currentThread().interrupt();
  }
}
```

**Comment by cdalexndr** [comment]
Can you make a new release with these changes?

**Comment by cdalexndr** [comment]
Fast fix, slow release... getting `java.nio.channels.ClosedChannelException` in production is not fun.
Shouldn't you release a hot patch for this?

Also note that github's `latest release` tag is on an old 3.8.1 version (24 sep 2019).

**Comment by chrisdennis** [comment]
If you want to get faster access you can just pull the source and build it yourself. There is no need to wait for a central build/release to get access to bug fixes for an open source project. That said there is an Ehcache release in process at the moment on the 3.9.x line which should include this fix. I will endeavor to get the housekeeping back up to date on Github and the ehcache.org website, limited time and multiple responsibilities sometimes mean that things like that often get skipped over.

Chris

From: cdalexndr ***@***.***>
Date: Wednesday, July 21, 2021 at 8:57 AM
To: ehcache/ehcache3 ***@***.***>
Cc: Chris Dennis ***@***.***>, Comment ***@***.***>
Subject: Re: [ehcache/ehcache3] java.nio.channels.ClosedChannelException (#2908)

Fast fix, slow release... getting java.nio.channels.ClosedChannelException in production is not fun.
Shouldn't you release a hot patch for this?

Also note that github's latest release tag is on an old 3.8.1 version (24 sep 2019).
