### ISSUE TITLE
Relocate issue

### ISSUE THREAD

**Issue by yChusy** [ehcache/ehcache3#2941]
I've this error when I relocated the ehCache using maven.
`
<relocation>
   <pattern>org.ehcache</pattern>
   <shadedPattern>com.ystoreplugins.ypoints.ehcache</shadedPattern>
</relocation>
 `

`Error occurred while enabling yPoints v2.0.5-STABLE (Is it up to date?)
java.lang.IllegalStateException: No factories exist for interface com.ystoreplugins.ypoints.ehcache.core.spi.service.LocalPersistenceService
        at com.ystoreplugins.ypoints.ehcache.core.spi.ServiceLocator$DependencySet.with(ServiceLocator.java:271) ~[?:?]
        at com.ystoreplugins.ypoints.ehcache.core.EhcacheManager.resolveServices(EhcacheManager.java:152) ~[?:?]
        at com.ystoreplugins.ypoints.ehcache.core.EhcacheManager.<init>(EhcacheManager.java:125) ~[?:?]
        at com.ystoreplugins.ypoints.ehcache.core.EhcacheManager.<init>(EhcacheManager.java:115) ~[?:?]
        at com.ystoreplugins.ypoints.ehcache.core.EhcacheManager.<init>(EhcacheManager.java:111) ~[?:?]
        at com.ystoreplugins.ypoints.ehcache.config.builders.CacheManagerBuilder.newCacheManager(CacheManagerBuilder.java:117) ~[?:?]
        at com.ystoreplugins.ypoints.ehcache.config.builders.CacheManagerBuilder.build(CacheManagerBuilder.java:73) ~[?:?]
        at com.ystoreplugins.ypoints.models.storager.PointStorager.<init>(PointStorager.java:42) ~[?:?]
        at com.ystoreplugins.ypoints.database.DatabaseEngine.<init>(DatabaseEngine.java:21) ~[?:?]
        at com.ystoreplugins.ypoints.Main.register(Main.java:64) ~[?:?]
        at com.ystoreplugins.ypoints.Main.onEnable(Main.java:48) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-db6de12-18fbb24]
        at rush.comandos.ComandoSystem.onCommand(ComandoSystem.java:444) [System.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:576) [server.jar:git-Spigot-db6de12-18fbb24]
        at rush.comandos.ComandoSystem.onCommand(ComandoSystem.java:661) [System.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]`

**Comment by chrisdennis** [comment]
Not sure what mechanism you are using for relocate but this is exactly the failure I would expect if you didn't process the `META-INF/services` files correctly. I would go back and check the documentation for the relocate mechanism you are using.
