### ISSUE TITLE
Infinite loop in ObjectInputStream readFully() when getting cache from OffheadDiskStorge

### ISSUE THREAD

**Issue by Tinker1024** [ehcache/ehcache3#2979]
I am dealing with a problem in our production environment.
Our programs run on Docker and we found thas the CPU usage of one docker image keeps increasing.
So I used the TOP command and jstack tool to check the threads and I found that there were two threads used most of CPU resource.
The thread stacks of these two threads are the same. Shows as follows:
```
"group0-1-thread-18" #285 prio=5 os_prio=0 tid=0x00005635a6b3e000 nid=0xa99 runnable [0x00007ff7bb91d000]
   java.lang.Thread.State: RUNNABLE
        at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2955)
        at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3427)
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:1009)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:448)
        at org.ehcache.impl.serialization.CompactJavaSerializer$OIS.<init>(CompactJavaSerializer.java:228)
        at org.ehcache.impl.serialization.CompactJavaSerializer.getObjectInputStream(CompactJavaSerializer.java:124)
        at org.ehcache.impl.serialization.CompactJavaSerializer.read(CompactJavaSerializer.java:109)
        at org.ehcache.impl.serialization.CompactJavaSerializer.equals(CompactJavaSerializer.java:132)
        at org.ehcache.impl.internal.store.offheap.portability.SerializerPortability.equals(SerializerPortability.java:56)
        at sun.reflect.GeneratedMethodAccessor442.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.ehcache.impl.internal.store.disk.OffHeapDiskStore.lambda$persistent$0(OffHeapDiskStore.java:506)
        at org.ehcache.impl.internal.store.disk.OffHeapDiskStore$$Lambda$912/1927284068.invoke(Unknown Source)
        at com.sun.proxy.$Proxy206.equals(Unknown Source)
        at org.ehcache.shadow.org.terracotta.offheapstore.storage.PortabilityBasedStorageEngine.equalsKey(PortabilityBasedStorageEngine.java:125)
        at org.ehcache.shadow.org.terracotta.offheapstore.OffHeapHashMap.keyEquals(OffHeapHashMap.java:1005)
        at org.ehcache.shadow.org.terracotta.offheapstore.OffHeapHashMap.computeIfPresentWithMetadata(OffHeapHashMap.java:2101)
        at org.ehcache.shadow.org.terracotta.offheapstore.AbstractLockedOffHeapHashMap.computeIfPresentWithMetadata(AbstractLockedOffHeapHashMap.java:542)
        at org.ehcache.shadow.org.terracotta.offheapstore.concurrent.AbstractConcurrentOffHeapMap.computeIfPresentWithMetadata(AbstractConcurrentOffHeapMap.java:781)
        at org.ehcache.impl.internal.store.disk.EhcachePersistentConcurrentOffHeapClockCache.computeIfPresentAndPin(EhcachePersistentConcurrentOffHeapClockCache.java:192)
        at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.getAndFault(AbstractOffHeapStore.java:826)
        at org.ehcache.impl.internal.store.tiering.TieredStore.lambda$get$0(TieredStore.java:89)
        at org.ehcache.impl.internal.store.tiering.TieredStore$$Lambda$1842/1352919690.apply(Unknown Source)
        at org.ehcache.impl.internal.store.heap.OnHeapStore.lambda$getOrComputeIfAbsent$12(OnHeapStore.java:703)
        at org.ehcache.impl.internal.store.heap.OnHeapStore$$Lambda$1843/483781110.get(Unknown Source)
        at org.ehcache.impl.internal.store.heap.OnHeapStore$Fault.getValueHolder(OnHeapStore.java:1017)
        - locked <0x00000000e1612448> (a org.ehcache.impl.internal.store.heap.OnHeapStore$Fault)
        at org.ehcache.impl.internal.store.heap.OnHeapStore$Fault.access$300(OnHeapStore.java:990)
        at org.ehcache.impl.internal.store.heap.OnHeapStore.resolveFault(OnHeapStore.java:768)
        at org.ehcache.impl.internal.store.heap.OnHeapStore.getOrComputeIfAbsent(OnHeapStore.java:707)
        at org.ehcache.impl.internal.store.tiering.TieredStore.get(TieredStore.java:87)
        at org.ehcache.core.Ehcache.doGet(Ehcache.java:90)
        at org.ehcache.core.EhcacheBase.get(EhcacheBase.java:127)
```
By the way, their thread id are 2271 and 2272. In other words, They were generated at the same time.
And I also found that these two thread have stuck in ObjectInputStream readFully() for hours.
I tried to solve the problem myself, but I didn't succeed.
I can't figure out why there is an infinite loop when reading a stream.
Help me please~

**Comment by chrisdennis** [comment]
Apologies for the delay in responding. If this is still an issue could you attach version numbers, configuration, and as much detail about your use case (methods invoked, and types stored) as is possible. Thanks.

**Comment by chrisdennis** [comment]
Closed - no response. Please reopen if this is still reproducible.
