### ISSUE TITLE
SpringMVC4.3.7.RELEASE+Ehcache3.3.0读取缓存时报错：org.ehcache.core.spi.store.StoreAccessException: java.lang.RuntimeException: java.io.EOFException

### ISSUE THREAD

**Issue by ai180508** [ehcache/ehcache3#3153]
环境：
jdk1.7.0_80
SpringMVC4.3.7.RELEASE
Ehcache3.3.0

Ehcache配置：
<?xml version="1.0" encoding="UTF-8"?>
<ehcache xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="http://ehcache.org/ehcache.xsd"
         updateCheck="false">
    <diskStore path="F:\develop\ehcache"/>
    <defaultCache
            maxElementsInMemory="1000"
            overflowToDisk="false"
            diskPersistent="false"
            timeToIdleSeconds="1800"
            timeToLiveSeconds="259200"
            memoryStoreEvictionPolicy="LRU"/>
</ehcache>

EhcacheUtil：
package com.mdsw.utils;

import org.ehcache.Cache;
import org.ehcache.PersistentCacheManager;
import org.ehcache.config.builders.CacheConfigurationBuilder;
import org.ehcache.config.builders.CacheManagerBuilder;
import org.ehcache.config.builders.ResourcePoolsBuilder;
import org.ehcache.expiry.Expirations;

import java.io.File;

public class EhcacheUtil {
    private EhcacheUtil(){}
    private static volatile PersistentCacheManager persistentCacheManager = CacheManagerBuilder.newCacheManagerBuilder()
            .with(CacheManagerBuilder.persistence(getStoragePath() + File.separator + "testCache")).build(true);

    private static String getStoragePath() {
        return  System.getProperty("catalina.home");
    }

    public static <K, V> Cache<K, V> creatCache(String alias, Class<K> k, Class<V> v, ResourcePoolsBuilder resourcePoolsBuilder) {
        return persistentCacheManager.createCache(alias,
                CacheConfigurationBuilder.newCacheConfigurationBuilder(
                        k, v,
                        resourcePoolsBuilder
                ).withExpiry(Expirations.noExpiration()));
    }

    public static <K, V> Cache<K, V> getCache(String alias, Class<K> k, Class<V> v) {
        return persistentCacheManager.getCache(alias, k, v);
    }

    private static boolean isClose = false;
    public static void close() {
        if (!isClose) {
            isClose = true;
            persistentCacheManager.close();
        }
    }
}

异常信息：
org.ehcache.CacheIterationException: org.ehcache.core.spi.store.StoreAccessException: java.lang.RuntimeException: java.io.EOFException
	at org.ehcache.core.internal.resilience.LoggingRobustResilienceStrategy.iteratorFailure(LoggingRobustResilienceStrategy.java:40)
	at org.ehcache.core.Ehcache$CacheEntryIterator.next(Ehcache.java:898)
	at org.ehcache.core.Ehcache$CacheEntryIterator.next(Ehcache.java:844)
	at com.mdsw.asmt.util.A1ImportTimerTask.importData(A1ImportTimerTask.java:55)
	at com.mdsw.exm.service.imp.ExmAdviceServiceImp.testImportData(ExmAdviceServiceImp.java:67)
	at com.mdsw.exm.controller.ExmAdviceController.testExmDataImport(ExmAdviceController.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2517)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2506)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.ehcache.core.spi.store.StoreAccessException: java.lang.RuntimeException: java.io.EOFException
	at org.ehcache.core.Ehcache$CacheEntryIterator.advance(Ehcache.java:868)
	at org.ehcache.core.Ehcache$CacheEntryIterator.<init>(Ehcache.java:855)
	at org.ehcache.core.Ehcache.iterator(Ehcache.java:294)
	at com.mdsw.asmt.util.A1ImportTimerTask.importData(A1ImportTimerTask.java:52)
	... 44 more
Caused by: java.lang.RuntimeException: java.io.EOFException
	at org.terracotta.offheapstore.disk.storage.FileBackedStorageEngine$FileChunk.readKeyBuffer(FileBackedStorageEngine.java:560)
	at org.terracotta.offheapstore.disk.storage.FileBackedStorageEngine.readKeyBuffer(FileBackedStorageEngine.java:282)
	at org.terracotta.offheapstore.storage.PortabilityBasedStorageEngine.readKey(PortabilityBasedStorageEngine.java:119)
	at org.terracotta.offheapstore.OffHeapHashMap$DirectEntry.<init>(OffHeapHashMap.java:1554)
	at org.terracotta.offheapstore.OffHeapHashMap$EntryIterator.create(OffHeapHashMap.java:1532)
	at org.terracotta.offheapstore.OffHeapHashMap$EntryIterator.create(OffHeapHashMap.java:1525)
	at org.terracotta.offheapstore.OffHeapHashMap$HashIterator.next(OffHeapHashMap.java:1421)
	at org.terracotta.offheapstore.AbstractLockedOffHeapHashMap$LockedEntryIterator.next(AbstractLockedOffHeapHashMap.java:399)
	at org.terracotta.offheapstore.AbstractLockedOffHeapHashMap$LockedEntryIterator.next(AbstractLockedOffHeapHashMap.java:392)
	at org.terracotta.offheapstore.concurrent.AbstractConcurrentOffHeapMap$AggregateIterator.next(AbstractConcurrentOffHeapMap.java:557)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore$21.next(AbstractOffHeapStore.java:602)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore$21.next(AbstractOffHeapStore.java:592)
	at org.ehcache.core.Ehcache$CacheEntryIterator.advance(Ehcache.java:861)
	... 47 more
Caused by: java.io.EOFException
	at org.terracotta.offheapstore.disk.storage.FileBackedStorageEngine.readIntFromChannel(FileBackedStorageEngine.java:388)
	at org.terracotta.offheapstore.disk.storage.FileBackedStorageEngine.access$500(FileBackedStorageEngine.java:61)
	at org.terracotta.offheapstore.disk.storage.FileBackedStorageEngine$FileChunk.readKeyBuffer(FileBackedStorageEngine.java:554)
	... 59 more

尝试使用Ehcache3.1.3时，相同的缓存文件不会提示该错误，但是缓存内容不能正常读取

**Comment by ai180508** [comment]
补充配置：
<?xml version="1.0" encoding="UTF-8"?>
<ehcache xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="http://ehcache.org/ehcache.xsd"
         updateCheck="false">
    <diskStore path="F:\develop\ehcache"/>
    <defaultCache
            maxElementsInMemory="1000"
            overflowToDisk="false"
            diskPersistent="false"
            timeToIdleSeconds="1800"
            timeToLiveSeconds="259200"
            memoryStoreEvictionPolicy="LRU"/>
</ehcache>

**Comment by chrisdennis** [comment]
I suspect that this is a variant of https://github.com/ehcache/ehcache3/issues/2619. The suspicion would be therefore that this is fixed in more recent releases. Please reopen this issue if you can reproduce using the latest release (3.10.8).
