### ISSUE TITLE
Error while cache.iterator() in ehcache-3.10.8.jar

### ISSUE THREAD

**Issue by sathishkumar08082001** [ehcache/ehcache3#3209]
Here is my configuration

LocalPersistenceService persistenceService= new DefaultLocalPersistenceService(new DefaultPersistenceConfiguration(new File(cacheDirectory)));
PersistentUserManagedCache cache = UserManagedCacheBuilder.newUserManagedCacheBuilder(keyClass, valueClass)
                .with(new UserManagedPersistenceContext<>(cacheName, persistenceService))
                .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder()
                        .heap(100L, MemoryUnit.MB)
                        .disk(1024L, MemoryUnit.MB, true)).build();
cache.init();

cache.putAll(hashMap); // hashMap is loaded with data
Iterator iterator = cache.iterator();

Find the stack trace below,

[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: java.lang.NullPointerException|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.shadow.org.terracotta.offheapstore.disk.storage.FileBackedStorageEngine.findChunk(FileBackedStorageEngine.java:363)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.shadow.org.terracotta.offheapstore.disk.storage.FileBackedStorageEngine.readKeyBuffer(FileBackedStorageEngine.java:264)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.shadow.org.terracotta.offheapstore.storage.PortabilityBasedStorageEngine.readKey(PortabilityBasedStorageEngine.java:119)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.shadow.org.terracotta.offheapstore.OffHeapHashMap$DirectEntry.<init>(OffHeapHashMap.java:1562)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.shadow.org.terracotta.offheapstore.OffHeapHashMap$EntryIterator.create(OffHeapHashMap.java:1540)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.impl.internal.store.disk.factories.EhcachePersistentSegmentFactory$EhcachePersistentSegment$EntrySet$1.create(EhcachePersistentSegmentFactory.java:133)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.impl.internal.store.disk.factories.EhcachePersistentSegmentFactory$EhcachePersistentSegment$EntrySet$1.create(EhcachePersistentSegmentFactory.java:130)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.shadow.org.terracotta.offheapstore.OffHeapHashMap$HashIterator.<init>(OffHeapHashMap.java:1400)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.shadow.org.terracotta.offheapstore.OffHeapHashMap$EntryIterator.<init>(OffHeapHashMap.java:1535)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.shadow.org.terracotta.offheapstore.AbstractLockedOffHeapHashMap$LockedEntryIterator.<init>(AbstractLockedOffHeapHashMap.java:385)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.impl.internal.store.disk.factories.EhcachePersistentSegmentFactory$EhcachePersistentSegment$EntrySet$1.<init>(EhcachePersistentSegmentFactory.java:130)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.impl.internal.store.disk.factories.EhcachePersistentSegmentFactory$EhcachePersistentSegment$EntrySet.iterator(EhcachePersistentSegmentFactory.java:130)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.shadow.org.terracotta.offheapstore.concurrent.AbstractConcurrentOffHeapMap$AggregateEntrySet$1.getNextIterator(AbstractConcurrentOffHeapMap.java:454)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.shadow.org.terracotta.offheapstore.concurrent.AbstractConcurrentOffHeapMap$AggregateIterator.<init>(AbstractConcurrentOffHeapMap.java:520)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.shadow.org.terracotta.offheapstore.concurrent.AbstractConcurrentOffHeapMap$AggregateEntrySet$1.<init>(AbstractConcurrentOffHeapMap.java:450)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.shadow.org.terracotta.offheapstore.concurrent.AbstractConcurrentOffHeapMap$AggregateEntrySet.iterator(AbstractConcurrentOffHeapMap.java:450)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore$1.<init>(AbstractOffHeapStore.java:501)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.iterator(AbstractOffHeapStore.java:500)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.impl.internal.store.tiering.TieredStore.iterator(TieredStore.java:234)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.core.EhcacheBase$CacheEntryIterator.<init>(EhcacheBase.java:727)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.core.EhcacheBase.iterator(EhcacheBase.java:321)|
[08:21:08:300]|[01-02-2024]|[SYSERR]|[INFO]|[139]: at org.ehcache.core.PersistentUserManagedEhcache.iterator(PersistentUserManagedEhcache.java:245)|

The data is being stored in cache directory. When i try to iterate over the data , the above issue reproduces, but not always. Once i faced this issue, I have manually deleted the cached data from cache directory. Again i have executed the same code,, the data is loaded in to disk and used iterator,, then its working fine... Hence this issue is not reproducing always.. Please help me with the solution as soon as possible.

**Comment by chrisdennis** [comment]
The first thing that springs to mind here is some kind of issue with either not shutting the cache down properly, or with the logic that detects this. There have been improvements to the "dirty shutdown" detection logic recently but they're not in any official release yet. As a quick fix you could try using one of the internal releases available via the Terracotta Maven repository to see if that solves the problem: https://mvnrepository.com/artifact/org.ehcache/ehcache/3.10.9-internal17

If not we're probably going to need more information about how the cache is lifecycled, when is it shutdown, when is it created, and could anything else be messing with the contents of the persistence directory other than Ehcache.

**Comment by sathishkumar08082001** [comment]
Thank you so much for your valuable comments, chris. Let me once again look in to my cache shutdown flow.
