### ISSUE TITLE
EHcache + JDK 17 results test failures but works fine with JDK 11

### ISSUE THREAD

**Issue by ProbotisOP** [ehcache/ehcache3#3245]
Hi when i am running my code which uses ehcache 3.8.1 it works fine but with JDK 17 the test's are failing with error :
<hr>
<img width="1434" alt="Screenshot 2024-09-02 at 8 03 43 PM" src="https://github.com/user-attachments/assets/4e463374-a72a-4264-8609-2b68d5b3b750">

ERRORS IN TEXT : 

```
02.09.2024 14:00:42.530 *INFO* [org.ehcache.impl.internal.resilience.RobustResilienceStrategy] AbstractResilienceStrategy.java:116 Ehcache key agooddevicetoken recovered from
org.ehcache.spi.resilience.StoreAccessException: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.util.LinkedHashMap$Entry java.util.LinkedHashMap.head accessible:
module java.base does not "opens java.util" to unnamed module @445b84c0
at org.ehcache.core.exceptions.StorePassThroughException.handleException(StorePassThroughException.java:78) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
at org.ehcache.impl.internal.store.heap.OnHeapStore.put(OnHeapStore.java:382) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]
at org.ehcache.core.Ehcache.doPut(Ehcache.java:94) ~[ehcache-3.8.1.jar:3.8.1 a19322e8d4b3f7157e878112c2afc0b6e3090fdd]

```
### I have tried to add --add-opens in JVM args as well but that dosn't work.

Any solution or anything i am doing wrong ?

**Comment by ProbotisOP** [comment]
Added this `--add-opens java.base/java.lang=ALL-UNNAMED` in jvmArgs as well but that dosn't work at all.

is version `3.8.1` is compatible with JDK 17 ?

**Comment by ProbotisOP** [comment]
Upgrade to 3.9.X or 3.10.X helps 👍 , closing this thread :)
