### ISSUE TITLE
cvc-elt.1.a: Cannot find the declaration of element 'ehcache:config'.

### ISSUE THREAD

**Issue by Naros** [ehcache/ehcache3#3246]
I recently updated to ehcache 3.10.8, and I am facing this error:
```
Caused by: org.xml.sax.SAXParseException: cvc-elt.1.a: Cannot find the declaration of element 'ehcache:config'.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2133)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:830)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.beginNode(DOMValidatorHelper.java:277)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.validate(DOMValidatorHelper.java:244)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.validate(DOMValidatorHelper.java:190)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:108)
	at org.ehcache.xml.ConfigurationParser.copyAndValidate(ConfigurationParser.java:286)
```
I've tried even the most basic XML below for ehcache and the validation fails:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<ehcache:config
        xmlns:ehcache="http://www.ehcache.org/v3"
        xmlns:jcache="http://www.ehcache.org/v3/jsr107">

</ehcache:config>
```
Any idea whats going on?

**Comment by Naros** [comment]
I should also note that our code builds the XML from another configuration system as follows:
```
final DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
final DocumentBuilder builder = factory.newDocumentBuilder();
final Document xmlDocument = builder.parse(new InputSource(new StringReader(xmlConfigString)));
return CacheManagerBuilder.newCacheManager(new XmlConfiguration(xmlDocument));
```

**Comment by chrisdennis** [comment]
You need to make the `DocumentBuilderFactory` namespace aware to propagate the namespace info in the XML in to the DOM. I think the following should work:
```java
final DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
factory.setNamespaceAware(true);
final DocumentBuilder builder = factory.newDocumentBuilder();
final Document xmlDocument = builder.parse(new InputSource(new StringReader(xmlConfigString)));
return CacheManagerBuilder.newCacheManager(new XmlConfiguration(xmlDocument));
```

**Comment by Naros** [comment]
Thanks, that was what I was missing :+1:
