### ISSUE TITLE
Exception when using a persistent cache but not indicating a persistenceMode 

### ISSUE THREAD

**Issue by aurbroszniowski** [ehcache/ehcache3#339]
The follwing will create an exception
```
    PersistentCacheManager persistentCacheManager = CacheManagerBuilder.newCacheManagerBuilder()
        .with(new PersistenceConfiguration(new File(System.getProperty("java.io.tmpdir") + "/myData"))) 
        .withCache("persistent-cache", CacheConfigurationBuilder.newCacheConfigurationBuilder()
            .withResourcePools(newResourcePoolsBuilder()
                .heap(10, EntryUnit.ENTRIES)
                .disk(100, EntryUnit.ENTRIES) // <2>
                .build())
            .buildConfig(Long.class, String.class))
        .build();
```

However it is working when indicating a persistenceMode
```
.persistenceMode(CacheConfiguration.PersistenceMode.CREATE_IF_ABSENT)
```

```
org.ehcache.exceptions.StateTransitionException: Cache 'persistent-cache' creation in EhcacheManager failed.
	at org.ehcache.EhcacheManager.init(EhcacheManager.java:356)
	at org.ehcache.CacheManagerBuilder.newCacheManager(CacheManagerBuilder.java:59)
	at org.ehcache.CacheManagerBuilder.build(CacheManagerBuilder.java:48)
	at org.ehcache.GettingStarted.persistentCacheManager(GettingStarted.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:355)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.IllegalStateException: Cache 'persistent-cache' creation in EhcacheManager failed.
	at org.ehcache.EhcacheManager.createCache(EhcacheManager.java:205)
	at org.ehcache.EhcacheManager.init(EhcacheManager.java:340)
	... 45 more
Caused by: org.ehcache.exceptions.StateTransitionException: java.io.FileNotFoundException: Data file /scratch/jenkins/workspace/ehcache3/jdk/Sun JDK 1.6 (latest)/impl/build/persistent-cache-data/persistent-cache.data or index file /scratch/jenkins/workspace/ehcache3/jdk/Sun JDK 1.6 (latest)/impl/build/persistent-cache-data/persistent-cache.index missing.
	at org.ehcache.Ehcache.init(Ehcache.java:1045)
	at org.ehcache.EhcacheManager.createCache(EhcacheManager.java:187)
	... 46 more
Caused by: java.lang.IllegalStateException: java.io.FileNotFoundException: Data file /scratch/jenkins/workspace/ehcache3/jdk/Sun JDK 1.6 (latest)/impl/build/persistent-cache-data/persistent-cache.data or index file /scratch/jenkins/workspace/ehcache3/jdk/Sun JDK 1.6 (latest)/impl/build/persistent-cache-data/persistent-cache.index missing.
	at org.ehcache.internal.store.disk.DiskStore.init(DiskStore.java:474)
	at org.ehcache.internal.store.tiering.CacheStore.init(CacheStore.java:198)
	at org.ehcache.Ehcache.init(Ehcache.java:1042)
	... 47 more
Caused by: java.io.FileNotFoundException: Data file /scratch/jenkins/workspace/ehcache3/jdk/Sun JDK 1.6 (latest)/impl/build/persistent-cache-data/persistent-cache.data or index file /scratch/jenkins/workspace/ehcache3/jdk/Sun JDK 1.6 (latest)/impl/build/persistent-cache-data/persistent-cache.index missing.
	at org.ehcache.internal.store.disk.DiskStorageFactory.<init>(DiskStorageFactory.java:249)
	at org.ehcache.internal.store.disk.DiskStore.init(DiskStore.java:470)
	... 49 more
```

**Comment by rishabhmonga** [comment]
xml configuration wiring for persistence mode also needs to be taken care of
