### ISSUE TITLE
No compile time error when defining size in heap(MemoryUnit.MB)

### ISSUE THREAD

**Issue by SanjayBansal** [ehcache/ehcache3#398]
I have a 4 cache with configuration : 
{Code}
cacheConfigurationBuilder.withResourcePools(resourcePoolsBuilder.heap(1000L, MemoryUnit.MB)
				.offheap(1, MemoryUnit.MB)
{Code}

I am able to compile the code without any error.but when I execute  i am getting  this stack during execution:
 {Code}
Caused by: java.lang.IllegalArgumentException: OnHeap store only handles resource unit 'entries'
	at org.ehcache.internal.store.heap.OnHeapStore.<init>(OnHeapStore.java:109)
	at org.ehcache.internal.store.heap.OnHeapStore$Provider.createStore(OnHeapStore.java:928)
	at org.ehcache.internal.store.heap.OnHeapStore$Provider.createCachingTier(OnHeapStore.java:967)
	at org.ehcache.internal.store.tiering.CacheStore$Provider.createStore(CacheStore.java:343)
	at org.ehcache.internal.store.DefaultStoreProvider.createStore(DefaultStoreProvider.java:79)
	at org.ehcache.EhcacheManager.createNewEhcache(EhcacheManager.java:199)
	at org.ehcache.EhcacheManager.createCache(EhcacheManager.java:149)
{Code}

**Comment by ljacomet** [comment]
This is not yet available but plans to be. Issue #33 needs to be resolved before this becomes valid.
