### ISSUE TITLE
Getting exception while configuring jsr107 cache Statistics

### ISSUE THREAD

**Issue by JSAhuja** [ehcache/ehcache3#498]
When configuring jsr107 cache statistics on windows machine, getting error:

`javax.management.MalformedObjectNameException: Invalid character ':' in value part of property`

Sample code:

```java
ObjectName objectName = new ObjectName("javax.cache:type=CacheStatistics"
        + ",CacheManager=" + (heapCache.getCacheManager().getURI().toString())
        + ",Cache=" + heapCache.getName());
```

The getURI is returning the xml location as below and probably of which its throwing exception:

`file:/C:/Users/jia/Documents/SourceTree/ehcachetest/jsr107/target/test-classes/ehcache-107-stats.xml`

**Comment by alexsnaps** [comment]
@ JSAhuja  Can you post a complete reproducible test case... Cause the only constructor usage of `ObjectName` I can find is in `org.ehcache.jsr107.Eh107MXBean#createObjectName` and that uses sanitized strings to create it... where is that code you quote above from?!

**Comment by alexsnaps** [comment]
No bug in our code, assigning to you @chrisdennis to check against the spec... maybe something the spec needs to address

**Comment by JSAhuja** [comment]
Go this code sample from 
https://docs.google.com/document/d/1YZ-lrH6nW871Vd9Z34Og_EqbX_kxxJi55UrSn4yL2Ak/edit

Page 129-130

**Comment by JSAhuja** [comment]
Full code:
```
public void basicTest() throws Exception {
		CachingProvider provider = Caching.getCachingProvider();
		CacheManager cacheManager = provider.getCacheManager(getClass().getResource("/ehcache-107-stats.xml").toURI(), ClassLoader.getSystemClassLoader());
		MutableConfiguration<String, String> configuration = new MutableConfiguration<String, String>();
		configuration.setTypes(String.class, String.class).setStatisticsEnabled(true);
		Cache<String, String> heapCache = cacheManager.createCache("heap", configuration);
		MBeanServer mBeanServer = ManagementFactory.getPlatformMBeanServer();
		System.out.println(heapCache.getCacheManager().getURI().toString());
		ObjectName objectName = new ObjectName("javax.cache:type=CacheStatistics"
				+ ",CacheManager=" + (heapCache.getCacheManager().getURI().toString())
				+ ",Cache=" + heapCache.getName());
		System.out.println(mBeanServer.getAttribute(objectName,"CacheHitPercentage"));
	}
```

Stack-Trace:
```
FAILED: basicTest
javax.management.MalformedObjectNameException: Invalid character ':' in value part of property
	at javax.management.ObjectName.construct(ObjectName.java:618)
	at javax.management.ObjectName.<init>(ObjectName.java:1382)
	at com.terracotta.qa.ehcache.test.StatisticsTest.basicTest(StatisticsTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
```

**Comment by chrisdennis** [comment]
This is a JSR-107 spec bug: jsr107/jsr107spec#329
