### ISSUE TITLE
JSR107 Cache with Disk Store stats missing

### ISSUE THREAD

**Issue by JSAhuja** [ehcache/ehcache3#506]
I am using javax.cache.CacheManager & javax.cache.Cache, but PersistentCacheManager code you comment is from ehcache.
Please let me know how to configure PersistenceConfiguration in javax.cache.CacheManager.

And corresponding to  XML based configuration the sample code and XML is:
```java
public void heapDiskTest() throws URISyntaxException 
{
		CacheManager cacheManager = Caching.getCachingProvider().getCacheManager(getClass().getResource("/ehcache/trials.xml").toURI(),getClass().getClassLoader());
		javax.cache.Cache<Long, String>  cache = cacheManager.getCache("HeapDiskConfigPFCache",Long.class,String.class);
		cache.put(1l, "value");
		cacheManager.close();
}
```

```xml
<ehcache:config xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns:ehcache='http://www.ehcache.org/v3' 
xmlns:jsr107='http://www.ehcache.org/v3/jsr107'
xsi:schemaLocation="http://www.ehcache.org/v3 ../../../../xml/src/main/resources/ehcache-core.xsd
                        http://www.ehcache.org/v3/jsr107 ../../main/resources/ehcache-107ext.xsd">
	<ehcache:service>
		<ehcache:persistence>
			<ehcache:directory>target/customSerializerTest/EhcacheDiskStore</ehcache:directory>
		</ehcache:persistence>
	</ehcache:service>
	<ehcache:cache alias="HeapDiskConfigPFCache" storeByValueOnHeap="true">
		<ehcache:key-type>java.lang.Long</ehcache:key-type>
		<ehcache:value-type>java.lang.String</ehcache:value-type>
		<ehcache:resources>
			<ehcache:heap size="20" unit="entries" />
			<ehcache:disk size="500" unit="mb" persistent="false" />
		</ehcache:resources>
	</ehcache:cache> 
</ehcache:config>
```

And below is the stack trace;
```
FAILED: heapDiskPFTest
java.lang.RuntimeException: stat result must not be null
	at org.ehcache.jsr107.Eh107CacheStatisticsMXBean.findAuthoritativeTierStatistic(Eh107CacheStatisticsMXBean.java:272)
	at org.ehcache.jsr107.Eh107CacheStatisticsMXBean.<init>(Eh107CacheStatisticsMXBean.java:85)
	at org.ehcache.jsr107.Eh107Cache.<init>(Eh107Cache.java:72)
	at org.ehcache.jsr107.Eh107CacheManager.wrapEhcacheCache(Eh107CacheManager.java:114)
	at org.ehcache.jsr107.Eh107CacheManager.wrapEhcacheCache(Eh107CacheManager.java:98)
	at org.ehcache.jsr107.Eh107CacheManager.loadExistingEhcaches(Eh107CacheManager.java:92)
	at org.ehcache.jsr107.Eh107CacheManager.<init>(Eh107CacheManager.java:81)
	at org.ehcache.jsr107.EhcacheCachingProvider.getCacheManager(EhcacheCachingProvider.java:112)
	at org.ehcache.jsr107.EhcacheCachingProvider.getCacheManager(EhcacheCachingProvider.java:155)
	at com.terracotta.qa.ehcache.test.trials.heapDiskPFTest(trials.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
```

**Comment by ljacomet** [comment]
On the programatic configuration, you need to specify the persistence configuration at the `CacheManager` level in a slightly different way:

````java
PersistentCacheManager persistentCacheManager = CacheManagerBuilder.newCacheManagerBuilder()
    .with(new CacheManagerPersistenceConfiguration(new File("target/EhcacheDiskStore")))
    .withCache("persistent-cache", CacheConfigurationBuilder.newCacheConfigurationBuilder()
        .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder()
            .heap(10, EntryUnit.ENTRIES)
            .disk(10L, MemoryUnit.MB, true)) // <2>
        .buildConfig(Long.class, String.class))
    .build(true);
````

The fix for issue #457 contains improvement around error reporting for this case.

And the issue on the XML config is similar, you need to specify the persistence configuration at the service level:

````xml
<ehcache:service>
  <ehcache:persistence>
    <ehcache:directory>/some/dir</ehcache:directory>
  </ehcache:persistence>
</ehcache:service>
````

Can you confirm these changes fix your problem?

**Comment by JSAhuja** [comment]
Full xml

<ehcache:config xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns:ehcache='http://www.ehcache.org/v3' xsi:schemaLocation="http://www.ehcache.org/v3 ../../../main/resources/ehcache-core.xsd" xmlns:jsr107='http://www.ehcache.org/v3/jsr107'>
	<ehcache:service>
		<ehcache:persistence>
			<ehcache:directory>target/customSerializerTest/EhcacheDiskStore</ehcache:directory>
		</ehcache:persistence>
	</ehcache:service>

	<ehcache:service>
		<jsr107:defaults default-template="defaultConfigCache">
			<jsr107:cache name="HeapCache" template="HeapTemplCache" />
		</jsr107:defaults>
	</ehcache:service>

	<ehcache:cache-template name="HeapTemplCache" storeByValueOnHeap="true">
		<ehcache:key-type>java.lang.Long</ehcache:key-type>
		<ehcache:value-type>java.lang.String</ehcache:value-type>
		<ehcache:integration>
			<ehcache:loaderwriter>
				<ehcache:class>com.terracotta.qa.ehcache.logic.LoaderWriter</ehcache:class>
			</ehcache:loaderwriter>
		</ehcache:integration>
		<ehcache:heap size="200" unit="entries" />
	</ehcache:cache-template>

	<ehcache:cache-template name="defaultConfigCache">
		<ehcache:resources>
			<ehcache:heap size="20" unit="entries" />
		</ehcache:resources>
	</ehcache:cache-template>

	<ehcache:cache alias="HeapConfigCache" storeByValueOnHeap="true">
		<ehcache:key-type>java.lang.Long</ehcache:key-type>
		<ehcache:value-type>java.lang.String</ehcache:value-type>
		<ehcache:integration>
			<ehcache:loaderwriter>
				<ehcache:class>com.terracotta.qa.ehcache.logic.LoaderWriter</ehcache:class>
			</ehcache:loaderwriter>
		</ehcache:integration>
		<ehcache:heap size="200" unit="entries" />
	</ehcache:cache>

	<ehcache:cache alias="HeapOffHeapConfigCache" storeByValueOnHeap="true">
		<ehcache:key-type>java.lang.Long</ehcache:key-type>
		<ehcache:value-type>java.lang.String</ehcache:value-type>
		<ehcache:integration>
			<ehcache:loaderwriter>
				<ehcache:class>com.terracotta.qa.ehcache.logic.LoaderWriter</ehcache:class>
			</ehcache:loaderwriter>
		</ehcache:integration>
		<ehcache:resources>
			<ehcache:heap size="2000" unit="entries" />
			<ehcache:offheap size="100" unit="mb" />
		</ehcache:resources>
	</ehcache:cache>

	<ehcache:cache alias="HeapOffHeapConfigCache" storeByValueOnHeap="true">
		<ehcache:key-type>java.lang.Long</ehcache:key-type>
		<ehcache:value-type>java.lang.String</ehcache:value-type>
		<ehcache:integration>
			<ehcache:loaderwriter>
				<ehcache:class>com.terracotta.qa.ehcache.logic.LoaderWriter</ehcache:class>
			</ehcache:loaderwriter>
		</ehcache:integration>
		<ehcache:resources>
			<ehcache:heap size="20" unit="entries" />
			<ehcache:offheap size="10" unit="mb" />
		</ehcache:resources>
	</ehcache:cache>

	<ehcache:cache alias="HeapDiskConfigPFCache" storeByValueOnHeap="true">
		<ehcache:key-type>java.lang.Long</ehcache:key-type>
		<ehcache:value-type>java.lang.String</ehcache:value-type>
		<ehcache:integration>
			<ehcache:loaderwriter>
				<ehcache:class>com.terracotta.qa.ehcache.logic.LoaderWriter</ehcache:class>
			</ehcache:loaderwriter>
		</ehcache:integration>
		<ehcache:resources>
			<ehcache:heap size="20" unit="entries" />
			<ehcache:disk size="500" unit="mb" persistent="false" />
		</ehcache:resources>
	</ehcache:cache> 
	
	
</ehcache:config>

**Comment by ljacomet** [comment]
You are missing the xsd definition for jsr107 namespace. Nothing to do with persistent caches.

**Comment by JSAhuja** [comment]
@ljacomet regarding with first comment:
I am using javax.cache.CacheManager & javax.cache.Cache, but PersistentCacheManager code you comment is from ehcache.
Please let me know how to configure PersistenceConfiguration in javax.cache.CacheManager.


And corresponding to  XML based configuration the sample code and XML is:
public void heapDiskTest() throws URISyntaxException 
{
		CacheManager cacheManager = Caching.getCachingProvider().getCacheManager(getClass().getResource("/ehcache/trials.xml").toURI(),getClass().getClassLoader());
		javax.cache.Cache<Long, String>  cache = cacheManager.getCache("HeapDiskConfigPFCache",Long.class,String.class);
		cache.put(1l, "value");
		cacheManager.close();
}

<ehcache:config xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns:ehcache='http://www.ehcache.org/v3' 
xmlns:jsr107='http://www.ehcache.org/v3/jsr107'
xsi:schemaLocation="http://www.ehcache.org/v3 ../../../../xml/src/main/resources/ehcache-core.xsd
                        http://www.ehcache.org/v3/jsr107 ../../main/resources/ehcache-107ext.xsd">
	<ehcache:service>
		<ehcache:persistence>
			<ehcache:directory>target/customSerializerTest/EhcacheDiskStore</ehcache:directory>
		</ehcache:persistence>
	</ehcache:service>
	<ehcache:cache alias="HeapDiskConfigPFCache" storeByValueOnHeap="true">
		<ehcache:key-type>java.lang.Long</ehcache:key-type>
		<ehcache:value-type>java.lang.String</ehcache:value-type>
		<ehcache:resources>
			<ehcache:heap size="20" unit="entries" />
			<ehcache:disk size="500" unit="mb" persistent="false" />
		</ehcache:resources>
	</ehcache:cache> 
</ehcache:config>



And below is the stack trace;
FAILED: heapDiskPFTest
java.lang.RuntimeException: stat result must not be null
	at org.ehcache.jsr107.Eh107CacheStatisticsMXBean.findAuthoritativeTierStatistic(Eh107CacheStatisticsMXBean.java:272)
	at org.ehcache.jsr107.Eh107CacheStatisticsMXBean.<init>(Eh107CacheStatisticsMXBean.java:85)
	at org.ehcache.jsr107.Eh107Cache.<init>(Eh107Cache.java:72)
	at org.ehcache.jsr107.Eh107CacheManager.wrapEhcacheCache(Eh107CacheManager.java:114)
	at org.ehcache.jsr107.Eh107CacheManager.wrapEhcacheCache(Eh107CacheManager.java:98)
	at org.ehcache.jsr107.Eh107CacheManager.loadExistingEhcaches(Eh107CacheManager.java:92)
	at org.ehcache.jsr107.Eh107CacheManager.<init>(Eh107CacheManager.java:81)
	at org.ehcache.jsr107.EhcacheCachingProvider.getCacheManager(EhcacheCachingProvider.java:112)
	at org.ehcache.jsr107.EhcacheCachingProvider.getCacheManager(EhcacheCachingProvider.java:155)
	at com.terracotta.qa.ehcache.test.trials.heapDiskPFTest(trials.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

**Comment by ljacomet** [comment]
@JSAhuja With regards to the question at programatic level:
In _JSR-107_, you can only configure persistence by having an XML configuration loaded by the `CacheManager`. You cannot configure the `CacheManager` in any other way. So every CM level configuration must come through 'a config' and that means XML since there is no JSR-107 way of configuring a CM but give it a URI.
