### ISSUE TITLE
Configuring a cache with a disk pool without configuring a CacheManagerPersistenceConfiguration throws NPE

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#594]
Here's a simple test that reproduces the problem:

```
    CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
        .withCache("aCache", CacheConfigurationBuilder.newCacheConfigurationBuilder()
                .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder()
                        .heap(10, EntryUnit.ENTRIES)
                        .disk(20, MemoryUnit.MB)
                )
                .buildConfig(Long.class, String.class)
        )
        .build(true);
```

**Comment by lorban** [comment]
And here's the stack trace:

```
SEVERE: Initialize failed.
Exception in thread "main" org.ehcache.exceptions.StateTransitionException: Cache 'aCache' creation in EhcacheManager failed.
	at org.ehcache.StatusTransitioner$Transition.failed(StatusTransitioner.java:223)
	at org.ehcache.EhcacheManager.init(EhcacheManager.java:485)
	at org.ehcache.CacheManagerBuilder.build(CacheManagerBuilder.java:48)
	at sample.Main.main(Main.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.IllegalStateException: Cache 'aCache' creation in EhcacheManager failed.
	at org.ehcache.EhcacheManager.createCache(EhcacheManager.java:223)
	at org.ehcache.EhcacheManager.init(EhcacheManager.java:470)
	... 7 more
Caused by: java.lang.NullPointerException
	at org.ehcache.EhcacheManager.createNewEhcache(EhcacheManager.java:269)
	at org.ehcache.EhcacheManager.createCache(EhcacheManager.java:204)
	... 8 more
```
