### ISSUE TITLE
SerializingCopier at cache manager level

### ISSUE THREAD

**Issue by JSAhuja** [ehcache/ehcache3#605]
Getting exception while configuring SerializingCopier at cache manager level.
Both Person & Description implements Serializable

```java
DefaultCopyProviderConfiguration copierType=new DefaultCopyProviderConfiguration()
        .addCopierFor(Person.class,(Class)SerializingCopier.class)
        .addCopierFor(Description.class, (Class) SerializingCopier.class);

    CacheConfiguration<Description, Person> cacheConfiguration = CacheConfigurationBuilder.newCacheConfigurationBuilder()
        .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder().heap(10, EntryUnit.ENTRIES).build())
        .buildConfig(Description.class, Person.class);

    CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
        .withCache("cache", cacheConfiguration)
        .using(copierType)
        .build(true);

    Cache<Description, Person> cache = cacheManager.getCache("cache", Description.class, Person.class);
```

Stack trace
```
16:31:35.623 [main] ERROR org.ehcache.EhcacheManager - Initialize failed.
org.ehcache.exceptions.StateTransitionException: Cache 'cache' creation in EhcacheManager failed.
	at org.ehcache.StatusTransitioner$Transition.failed(StatusTransitioner.java:223)
	at org.ehcache.EhcacheManager.init(EhcacheManager.java:489)
	at org.ehcache.CacheManagerBuilder.build(CacheManagerBuilder.java:48)
	at com.terracotta.qa.ehcache.DefaultCopierTest.defaultCopierTest(DefaultCopierTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.IllegalStateException: Cache 'cache' creation in EhcacheManager failed.
	at org.ehcache.EhcacheManager.createCache(EhcacheManager.java:223)
	at org.ehcache.EhcacheManager.init(EhcacheManager.java:474)
	... 32 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: No such accessible constructor on object: org.ehcache.internal.copy.SerializingCopier
	at org.ehcache.internal.classes.ClassInstanceProvider.newInstance(ClassInstanceProvider.java:85)
	at org.ehcache.internal.classes.ClassInstanceProvider.newInstance(ClassInstanceProvider.java:68)
	at org.ehcache.spi.copy.DefaultCopyProvider.createCopier(DefaultCopyProvider.java:72)
	at org.ehcache.spi.copy.DefaultCopyProvider.createCopier(DefaultCopyProvider.java:64)
	at org.ehcache.spi.copy.DefaultCopyProvider.createKeyCopier(DefaultCopyProvider.java:47)
	at org.ehcache.internal.store.heap.OnHeapStore$Provider.createStore(OnHeapStore.java:1058)
	at org.ehcache.internal.store.heap.OnHeapStore$Provider.createStore(OnHeapStore.java:1048)
	at org.ehcache.internal.store.DefaultStoreProvider.createStore(DefaultStoreProvider.java:87)
	at org.ehcache.EhcacheManager.createNewEhcache(EhcacheManager.java:313)
	at org.ehcache.EhcacheManager.createCache(EhcacheManager.java:204)
	... 33 more
Caused by: java.lang.NoSuchMethodException: No such accessible constructor on object: org.ehcache.internal.copy.SerializingCopier
	at org.ehcache.internal.classes.commonslang.reflect.ConstructorUtils.invokeConstructor(ConstructorUtils.java:119)
	at org.ehcache.internal.classes.commonslang.reflect.ConstructorUtils.invokeConstructor(ConstructorUtils.java:89)
	at org.ehcache.internal.classes.ClassInstanceProvider.newInstance(ClassInstanceProvider.java:79)
	... 42 more
```

**Comment by JSAhuja** [comment]
The Problem in this issue is probabaly becaue of the absence of no arg constructor ````SerializingCopier````

Test:
````
public class testClass {

    @Test
    public void test605() {
        DefaultCopyProviderConfiguration copierType = new DefaultCopyProviderConfiguration()
                .addCopierFor(Person.class, (Class) SerializingCopier.class)
                .addCopierFor(Description.class, (Class) SerializingCopier.class);

        CacheConfiguration<Description, Person> cacheConfiguration = CacheConfigurationBuilder.newCacheConfigurationBuilder()
                .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder().heap(10, EntryUnit.ENTRIES).build())
                .buildConfig(Description.class, Person.class);

        CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
                .withCache("cache", cacheConfiguration)
                .using(copierType)
                .build(true);

        Cache<Description, Person> cache = cacheManager.getCache("cache", Description.class, Person.class);
        cacheManager.close();

    }
}
 class Description implements Serializable {
    int id;
    String alias;

    Description(Description other) {
        this.id = other.id;
        this.alias = other.alias;
    }

    Description(int id, String alias) {
        this.id = id;
        this.alias = alias;
    }

    @Override
    public boolean equals(final Object other) {
        if(this == other) return true;
        if(other == null || this.getClass() != other.getClass()) return false;

        Description that = (Description)other;
        if(id != that.id) return false;
        if ((alias == null) ? (alias != null) : !alias.equals(that.alias)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + id;
        result = 31 * result + (alias == null ? 0 : alias.hashCode());
        return result;
    }
}

 class Person implements Serializable {
    String name;
    int age;

    Person(Person other) {
        this.name = other.name;
        this.age = other.age;
    }

    Person(String name, int age) {
        this.name = name;
        this.age = age;
    }

    @Override
    public boolean equals(final Object other) {
        if(this == other) return true;
        if(other == null || this.getClass() != other.getClass()) return false;

        Person that = (Person)other;
        if(age != that.age) return false;
        if((name == null) ? (that.name != null) : !name.equals(that.name)) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = 31 * result + age;
        result = 31 * result + (name == null ? 0 : name.hashCode());
        return result;
    }
}

 class DescriptionCopier extends ReadWriteCopier<Description> {

    @Override
    public Description copy(final Description obj) {
        return new Description(obj);
    }
}

 class PersonCopier extends ReadWriteCopier<Person> {
    @Override
    public Person copy(final Person obj) {
        return new Person(obj);
    }
}
````

Full Console Log;
````
[main] INFO org.ehcache.spi.ServiceLocator - All Services successfully started.
[main] INFO org.ehcache.EhcacheManager - Cache 'cache' is getting created in EhcacheManager.
[main] INFO org.ehcache.spi.serialization.DefaultSerializationProvider - Serializer for <org.ehcache.docs.Description> : org.ehcache.internal.serialization.CompactJavaSerializer@1a4f27a3
[main] INFO org.ehcache.spi.serialization.DefaultSerializationProvider - Serializer for <org.ehcache.docs.Person> : org.ehcache.internal.serialization.CompactJavaSerializer@6e26d149
[main] ERROR org.ehcache.EhcacheManager - Initialize failed.

org.ehcache.exceptions.StateTransitionException: Cache 'cache' creation in EhcacheManager failed.
	at org.ehcache.StatusTransitioner$Transition.failed(StatusTransitioner.java:223)
	at org.ehcache.EhcacheManager.init(EhcacheManager.java:489)
	at org.ehcache.CacheManagerBuilder.build(CacheManagerBuilder.java:48)
	at org.ehcache.docs.testClass.test605(testClass.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.IllegalStateException: Cache 'cache' creation in EhcacheManager failed.
	at org.ehcache.EhcacheManager.createCache(EhcacheManager.java:223)
	at org.ehcache.EhcacheManager.init(EhcacheManager.java:474)
	... 28 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: No such accessible constructor on object: org.ehcache.internal.copy.SerializingCopier
	at org.ehcache.internal.classes.ClassInstanceProvider.newInstance(ClassInstanceProvider.java:85)
	at org.ehcache.internal.classes.ClassInstanceProvider.newInstance(ClassInstanceProvider.java:68)
	at org.ehcache.spi.copy.DefaultCopyProvider.createCopier(DefaultCopyProvider.java:72)
	at org.ehcache.spi.copy.DefaultCopyProvider.createCopier(DefaultCopyProvider.java:64)
	at org.ehcache.spi.copy.DefaultCopyProvider.createKeyCopier(DefaultCopyProvider.java:47)
	at org.ehcache.internal.store.heap.OnHeapStore$Provider.createStore(OnHeapStore.java:1058)
	at org.ehcache.internal.store.heap.OnHeapStore$Provider.createStore(OnHeapStore.java:1048)
	at org.ehcache.internal.store.DefaultStoreProvider.createStore(DefaultStoreProvider.java:87)
	at org.ehcache.EhcacheManager.createNewEhcache(EhcacheManager.java:313)
	at org.ehcache.EhcacheManager.createCache(EhcacheManager.java:204)
	... 29 more
Caused by: java.lang.NoSuchMethodException: No such accessible constructor on object: org.ehcache.internal.copy.SerializingCopier
	at org.ehcache.internal.classes.commonslang.reflect.ConstructorUtils.invokeConstructor(ConstructorUtils.java:119)
	at org.ehcache.internal.classes.commonslang.reflect.ConstructorUtils.invokeConstructor(ConstructorUtils.java:89)
	at org.ehcache.internal.classes.ClassInstanceProvider.newInstance(ClassInstanceProvider.java:79)
	... 38 more
````
