### ISSUE TITLE
NPE for invalid Cache config & non existing XML

### ISSUE THREAD

**Issue by JSAhuja** [ehcache/ehcache3#620]
Cont.. from the chain mail, getting NPE exception for below case.
Something meaningful messages can help user understand the NPE which are cause by user errors.

i)       Pointed xml is not available.
````
public void identityCopierTest() throws ClassNotFoundException, SAXException, InstantiationException, IOException, IllegalAccessException {
  CopierCallCounter.resetCounter();
  String initialAlias="Hello", modifiedAlias="Verifying store by reference";
  Configuration xmlConfig = new XmlConfiguration(getClass().getResource("/XMLNotAvailable123.xml"));//NPE, #42
  CacheManager cacheManager = CacheManagerBuilder.newCacheManager(xmlConfig);
  cacheManager.init();
  Cache<Integer, Description> cache = cacheManager.getCache("IdentityCopier", Integer.class, Description.class);
  cacheManager.close();
}
````

Stack trace:
````
java.lang.NullPointerException
    at org.ehcache.config.xml.XmlConfiguration.parseConfiguration(XmlConfiguration.java:158)
    at org.ehcache.config.xml.XmlConfiguration.<init>(XmlConfiguration.java:152)
    at org.ehcache.config.xml.XmlConfiguration.<init>(XmlConfiguration.java:127)
    at org.ehcache.config.xml.XmlConfiguration.<init>(XmlConfiguration.java:107)
    at com.terracotta.qa.ehcache.CustomCopierTest.identityCopierTest(CustomCopierTest.java:42)
```` 
 
ii) Cache config is not available in the XML, i.e. the xml is present but have only <ehcache:config> </ehcache:config> tags
````` 
public void identityCopierTest() throws ClassNotFoundException, SAXException, InstantiationException, IOException, IllegalAccessException {
  CopierCallCounter.resetCounter();
  String initialAlias="Hello", modifiedAlias="Verifying store by reference";
  Configuration xmlConfig = new XmlConfiguration(getClass().getResource("/ehcache/CustomCopierTest.xml"));
  CacheManager cacheManager = CacheManagerBuilder.newCacheManager(xmlConfig);
  cacheManager.init();
  Cache<Integer, Description> cache = cacheManager.getCache("CacheNotDefined", Integer.class, Description.class);// CacheNotDefined is not defined in the XML

  Description desc = new Description(1234, initialAlias);
  cache.put(1, desc);//NPE #48

  cacheManager.close();
}
```` 
XML Something like this:
````
<ehcache:config
    xmlns:ehcache='http://www.ehcache.org/v3'>
</ehcache:config>
````
 
Stack Trace:
````
20:43:45.231 [main] INFO  o.e.config.xml.XmlConfiguration - Loading Ehcache XML configuration from /C:/Users/jia/Documents/SourceTree/ehcachetest/copier/target/test-classes/ehcache/CustomCopierTest.xml.
20:43:45.925 [main] INFO  org.ehcache.spi.ServiceLocator - All Services successfully started.
20:43:45.928 [main] INFO  org.ehcache.EhcacheManager - Initialize successful.
java.lang.NullPointerException
at com.terracotta.qa.ehcache.CustomCopierTest.identityCopierTest(CustomCopierTest.java:48)
````

**Comment by ljacomet** [comment]
@JSAhuja We cannot and should not cope for user errors.

However in the case of example 1, we can improve the exception thrown by adding a meaningful message to it.

Nothing more should be done in this context.
