### ISSUE TITLE
Issue between a Fault and the AbstractValueHolder.equals contract

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache3#634]
From the mailing list:

> Caused by: java.lang.UnsupportedOperationException
        at org.ehcache.internal.store.heap.OnHeapStore$Fault.creationTime(OnHeapStore.java:655)
        at org.ehcache.spi.cache.AbstractValueHolder.equals(AbstractValueHolder.java:127)
        at org.ehcache.internal.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1114)
        at org.ehcache.internal.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1533)
        at org.ehcache.internal.store.heap.OnHeapStore$MapWrapper.remove(OnHeapStore.java:1153)
        at org.ehcache.internal.store.heap.OnHeapStore.getOrComputeIfAbsent(OnHeapStore.java:505)
        at org.ehcache.internal.store.tiering.CompoundCachingTier.getOrComputeIfAbsent(CompoundCachingTier.java:98)
        at org.ehcache.internal.store.tiering.CacheStore.computeIfAbsent(CacheStore.java:263)
        at org.ehcache.Ehcache.get(Ehcache.java:199)
        at org.ehcache.jsr107.Eh107Cache.get(Eh107Cache.java:88)

This shows that using CAS operations with a Fault causes problem. We need to revise the Fault impl and / or the `AbstractValueHolder.equals` contract.

**Comment by rishabhmonga** [comment]
While trying to reproduce this bug I stumbled upon a similar issue when pounding the cache with a very small heap size, using multiple threads.

````java
java.lang.UnsupportedOperationException: You should NOT call that?!
	at org.ehcache.internal.store.heap.OnHeapStore$Fault.getId(OnHeapStore.java:628)
	at org.ehcache.internal.store.offheap.AbstractOffHeapStore$12.apply(AbstractOffHeapStore.java:557)
	at org.ehcache.internal.store.offheap.AbstractOffHeapStore$12.apply(AbstractOffHeapStore.java:554)
	at org.ehcache.internal.store.offheap.factories.EhcacheSegmentFactory$EhcacheSegment.computeIfPinned(EhcacheSegmentFactory.java:156)
	at org.ehcache.internal.store.offheap.EhcacheConcurrentOffHeapClockCache.computeIfPinned(EhcacheConcurrentOffHeapClockCache.java:59)
	at org.ehcache.internal.store.offheap.AbstractOffHeapStore.flush(AbstractOffHeapStore.java:554)
	at org.ehcache.internal.store.tiering.CacheStore$1.onInvalidation(CacheStore.java:74)
	at org.ehcache.internal.store.heap.OnHeapStore$13.onEviction(OnHeapStore.java:567)
	at org.ehcache.internal.store.heap.OnHeapStore.evict(OnHeapStore.java:1013)
	at org.ehcache.internal.store.heap.OnHeapStore.enforceCapacity(OnHeapStore.java:983)
	at org.ehcache.internal.store.heap.OnHeapStore.getOrComputeIfAbsent(OnHeapStore.java:480)
	at org.ehcache.internal.store.tiering.CacheStore.computeIfAbsent(CacheStore.java:263)
	at org.ehcache.Ehcache.get(Ehcache.java:199)
````
I will be working towards resolving this bug within this issue.
