### ISSUE TITLE
Using 2 cache

### ISSUE THREAD

**Issue by ansarrafique** [ehcache/ehcache3#638]
I have a ehcache.xml file where I have defined two caches: one for the storage (name="storage") and the other for the search(name="search"). These two are defined separately because I want the data stored in "search" cache to be persisted on disk, whereas the data stored in "storage" cache only required to be stored in cache (no disk persistent required). If I use both caches using a single java class -> a single Cache Manager, it doesn't work because, in order to persist data on disk, I need to  shutdown cache manager and when the other cache try to access the data, it get an exception that the cache manager is shut down. I decided to create two java classes, one for the Storage Cache and the other for the Search Cache, which means I am creating two separate cache managers. This would help me to only shutdown one cache manager in order to persist data on disk.

Please find the code for both classes below

public class StorageCache implements ICache {
	public static CacheManager cacheManager = null;
	public Ehcache storageCache = null;
	
	private static Ehcache getStorageCache(){
		if(cacheManager == null){
			ClassLoader contextClassLoader = Thread.currentThread().getContextClassLoader();
			InputStream resourceAsStream = contextClassLoader.getResourceAsStream("/main/resources/ehcache.xml");
			CacheManager manager = new CacheManager(resourceAsStream);
			cacheManager = manager.getInstance();
			
		}
		return cacheManager.getEhcache(CacheName.STORAGE.toString().toLowerCase());
	}
	public StorageCache() {
		storageCache = getStorageCache();
	}
	@Override
	public void addElement(String key, Object Value) {
		Element element = new Element(key, Value);
		storageCache.put(element);
	}
	@Override
	public Object getElement(String key) {
		Element element = storageCache.get(key);
		if (element != null){
			return element.getObjectValue();
		}
		return null;
	}
	@Override
	public void shutDown(){
		if(storageCache != null){
			storageCache.getCacheManager().shutdown();
			cacheManager = null;
		}
	}
	public Ehcache getCache(){
		System.out.println(this.storageCache.getSize());
		return this.storageCache;
	}

public class SearchCache implements ICache{

	public static CacheManager searchCacheManager = null;
	public Ehcache cache = null;
	
	private static Ehcache getSearchCache(){
		if(searchCacheManager == null){
			ClassLoader contextClassLoader = Thread.currentThread().getContextClassLoader();
			InputStream resourceAsStream = contextClassLoader.getResourceAsStream("/main/resources/ehcache.xml");
			CacheManager manager = new CacheManager(resourceAsStream);
			searchCacheManager = CacheManager.getInstance();
		}
		return searchCacheManager.getEhcache(CacheName.SEARCH.toString().toLowerCase());
	}
	public SearchCache() {
		cache = getSearchCache();
	}
	@Override
	public void addElement(String key, Object Value) {
		Element element = new Element(key, Value);
		cache.put(element);
	}
	@Override
	public Object getElement(String key) {
		Element element = cache.get(key);
		if (element != null){
			return element.getObjectValue();
		}
		return null;
	}
	@Override
	public void shutDown(){
		if(cache != null){
			cache.getCacheManager().shutdown();
			searchCacheManager = null;
		}
	}
	public Ehcache getCache(){
		return this.cache;
	}

However, I am getting an exception

Oct 16, 2015 8:12:39 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Allocate exception for servlet com.leuven.distrinet.lmaas.client.controller.LogDataStorage
net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.
The source of the existing CacheManager is: InputStreamConfigurationSource [stream=java.io.BufferedInputStream@3a4b34a9]
	at net.sf.ehcache.CacheManager.assertNoCacheManagerExistsWithSameName(CacheManager.java:628)
	at net.sf.ehcache.CacheManager.init(CacheManager.java:392)
	at net.sf.ehcache.CacheManager.<init>(CacheManager.java:356)
	at com.leuven.distrinet.lmaas.dmmiddleware.ehcache.SearchCache.getSearchCache(SearchCache.java:18)
	at com.leuven.distrinet.lmaas.dmmiddleware.ehcache.SearchCache.<init>(SearchCache.java:24)
	at com.leuven.distrinet.lmaas.dmmiddleware.services.DataManagementService.<init>(DataManagementService.java:51)
	at com.leuven.distrinet.lmaas.client.controller.LogDataStorage.init(LogDataStorage.java:40)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1241)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1154)
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:827)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:135)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:534)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1081)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

If I remove the code  (see below) from the search cache then it works, but then I get the exception that the cache manager is shutdown

ClassLoader contextClassLoader = Thread.currentThread().getContextClassLoader();
			InputStream resourceAsStream = contextClassLoader.getResourceAsStream("/main/resources/ehcache.xml");
			CacheManager manager = new CacheManager(resourceAsStream);

Can you please help me fix this problem?

**Comment by ansarrafique** [comment]
I also don't want to shutdown cache manager for each operation and create it again.

**Comment by ljacomet** [comment]
These Ehcache 2.x questions belong on the [ehcache-users google group](https://groups.google.com/forum/#!forum/ehcache-users) and not on the issue tracker for Ehcache 3.
