### ISSUE TITLE
AssertionError thrown by 3-tier cache

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#641]
while applying some load to a 3-tiered cache, I sometimes get this error:

```
java.lang.AssertionError
	at org.ehcache.internal.store.offheap.AbstractOffHeapStore$18.apply(AbstractOffHeapStore.java:661)
	at org.ehcache.internal.store.offheap.AbstractOffHeapStore$18.apply(AbstractOffHeapStore.java:657)
	at org.ehcache.internal.store.offheap.factories.EhcacheSegmentFactory$EhcacheSegment.compute(EhcacheSegmentFactory.java:91)
	at org.ehcache.internal.store.offheap.EhcacheConcurrentOffHeapClockCache.compute(EhcacheConcurrentOffHeapClockCache.java:47)
	at org.ehcache.internal.store.offheap.AbstractOffHeapStore.getOrComputeIfAbsent(AbstractOffHeapStore.java:657)
	at org.ehcache.internal.store.tiering.CompoundCachingTier$1.onInvalidation(CompoundCachingTier.java:59)
	at org.ehcache.internal.store.heap.OnHeapStore$13.onEviction(OnHeapStore.java:567)
	at org.ehcache.internal.store.heap.OnHeapStore.evict(OnHeapStore.java:1013)
	at org.ehcache.internal.store.heap.OnHeapStore.enforceCapacity(OnHeapStore.java:983)
	at org.ehcache.internal.store.heap.OnHeapStore.getOrComputeIfAbsent(OnHeapStore.java:480)
	at org.ehcache.internal.store.tiering.CompoundCachingTier.getOrComputeIfAbsent(CompoundCachingTier.java:99)
	at org.ehcache.internal.store.tiering.CacheStore.computeIfAbsent(CacheStore.java:263)
	at org.ehcache.Ehcache.get(Ehcache.java:199)
	...
```
I have a load test that can reasonably easily trigger this error, ask me if you need it.

**Comment by ljacomet** [comment]
I believe a culprit has been identified:
* Eviction notification from the `OnHeapStore` currently does not happen under lock scope of the key being evicted.

This means that while a key is being evicted in a two caching tiers setup there is a moment where the mapping no longer is in the higher tier and not yet on the lower tier. This gives a window of opportunity for that key to be faulted by a concurrent thread from the authority again.
And when that mapping gets invalidated form the higher caching tier, by eviction as in the stack trace above, it will trigger the assertion error.

So this made me look into where we call listeners (event or invalidation) inside the `OnHeapStore` and it happens that there were only two places where that was not done under lock:
 * eviction, as described above
* when expiring during iteration

So I will also fix the iteration event firing to replace it by a call to the equivalent of `containsKey(key)` which will not update stats but will expire if needed and properly under lock.

**Comment by mknarula** [comment]
I am getting an AssertionError  Exception thrown : java.lang.AssertionError: NaN Eviction Cost [hit:Infinity miss:Infinity size:82]

**Comment by mknarula** [comment]
I dont get this all the time. But intermittently
