### ISSUE TITLE
java.lang.ClassNotFoundException: org.terracotta.management.capabilities.Capability

### ISSUE THREAD

**Issue by karuneshy** [ehcache/ehcache3#684]
Hi,
   While using Milestone 4 jar getting exception as below.

```
java.lang.NoClassDefFoundError: org/terracotta/management/capabilities/Capability
	at org.ehcache.management.registry.DefaultManagementRegistry.stateTransition(DefaultManagementRegistry.java:111)
	at org.ehcache.StatusTransitioner.fireTransitionEvent(StatusTransitioner.java:173)
	at org.ehcache.StatusTransitioner.access$200(StatusTransitioner.java:32)
	at org.ehcache.StatusTransitioner$Transition.succeeded(StatusTransitioner.java:210)
	at org.ehcache.EhcacheManager.init(EhcacheManager.java:486)
	at org.ehcache.jsr107.EhcacheCachingProvider.getCacheManager(EhcacheCachingProvider.java:118)
	at org.ehcache.jsr107.EhcacheCachingProvider.getCacheManager(EhcacheCachingProvider.java:162)
```

Please address the same.

Thanks & Regards,
Karunesh.Y

**Comment by ljacomet** [comment]
When using JSR-107, the following dependency is required:

```xml
<dependency>
  <groupId>org.terracotta</groupId>
  <artifactId>management-model</artifactId>
  <version>2.0.0</version>
</dependency>
```

**Comment by ljacomet** [comment]
To give more context:

The management-model dependency is required by Ehcache 3 as soon as you want some management capabilities, including looking at statistics.
As JSR-107 has mandatory requirements for this, it makes it mandatory in that context but not when using Ehcache 3 standalone.
As such, the current dependency information published with Ehcache 3 declares the dependency as `provided`.
While [documentation was updated](http://www.ehcache.org/#using_jsr107_api) to indicate this dependency requirement for JSR-107 use, I am not sure to be satisfied with the situation when using a build tool with dependency management.

So we have multiple options to consider:

1. Leave as-is, that is `provided` dependency and documentation
2. Change the dependency to be `compile` scope and documentation
3. Shade this dependency in the main Ehcache 3 jar, making it fatter but easier to use outside of a dependency management environment.

Opinions?

**Comment by alexsnaps** [comment]
I think we should shade it in... fatter indeed, but for a "distribution" that supports jcache, it should just support it... And I thought we had agreement we want a single ehcache.jar (but for logging impl) for people to use.

**Comment by karuneshy** [comment]
Louis, 
cache-api-1.0.0.jar is already part of classpath.

as mentioned i tried adding 
<dependency>
  <groupId>org.terracotta</groupId>
  <artifactId>management-model</artifactId>
  <version>2.0.0</version>
</dependency>

In the ehcache.xml file,  throwing below exception

java.lang.ExceptionInInitializerError

Caused by: javax.cache.CacheException: org.xml.sax.SAXParseException; systemId: file:/Development/ProductReleaseDB/properties/ehcache-jsr107-config.xml; lineNumber: 7; columnNumber: 17; cvc-complex-type.2.4.a: Invalid content was found starting with element 'dependency'. One of '{"http://www.ehcache.org/v3":service, "http://www.ehcache.org/v3":default-serializers, "http://www.ehcache.org/v3":default-copiers, "http://www.ehcache.org/v3":persistence, "http://www.ehcache.org/v3":thread-pools, "http://www.ehcache.org/v3":event-dispatch, "http://www.ehcache.org/v3":write-behind, "http://www.ehcache.org/v3":disk-store, "http://www.ehcache.org/v3":cache, "http://www.ehcache.org/v3":cache-template}' is expected.
	at org.ehcache.jsr107.EhcacheCachingProvider.getCacheManager(EhcacheCachingProvider.java:102)
	at org.ehcache.jsr107.EhcacheCachingProvider.getCacheManager(EhcacheCachingProvider.java:162)

Please let me know what i am missing.

Thanks & Regards,
Karunesh.Y

**Comment by ljacomet** [comment]
The XML extract was the maven dependency declaration, not something to be added to the Ehcache XML.

If you are not using maven, you need to [download the jar file](http://search.maven.org/#artifactdetails%7Corg.terracotta%7Cmanagement-model%7C2.0.0%7Cjar) and add it to your classpath.

**Comment by ljacomet** [comment]
@alexsnaps So shade it in indeed and apply the same to off heap so that external dependencies are indeed limited to slf4j-api.

And we can always design lighter versions in the future.

**Comment by karuneshy** [comment]
After including management-model-2.0.0.jar application started working. Thanks
