### ISSUE TITLE
org.ehcache.exceptions.CacheAccessException: java.lang.reflect.UndeclaredThrowableException

### ISSUE THREAD

**Issue by karuneshy** [ehcache/ehcache3#685]
Hi,
   Getting below exception.

org.ehcache.exceptions.CacheAccessException: java.lang.reflect.UndeclaredThrowableException
        at org.ehcache.exceptions.CachePassThroughException.handleRuntimeException(CachePassThroughException.java:58)
        at org.ehcache.internal.store.offheap.AbstractOffHeapStore.compute(AbstractOffHeapStore.java:474)
        at org.ehcache.internal.store.offheap.AbstractOffHeapStore.compute(AbstractOffHeapStore.java:420)
        at org.ehcache.internal.store.tiering.CacheStore.compute(CacheStore.java:246)
        at org.ehcache.Ehcache.put(Ehcache.java:256)
        at org.ehcache.jsr107.Eh107Cache.put(Eh107Cache.java:179)

Thanks & Regards,
Karunesh.Y

**Comment by karuneshy** [comment]
not an issue, its a non serialize able  list was tried to be serialized using diskstore. Closing issue.
