### ISSUE TITLE
multiple AssertionError's when pounding 3-tiered cache

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#715]
I got quite a few of these exceptions when running very short duration load tests:

```
10:49:15.895 [Rainfall-core Operations Thread] INFO  o.e.r.LoggingRobustResilienceStrategy - Ehcache key 51 recovered from
org.ehcache.exceptions.CacheAccessException: java.lang.AssertionError
	at org.ehcache.internal.store.heap.OnHeapStore.getOrComputeIfAbsent(OnHeapStore.java:661) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.internal.store.tiering.CompoundCachingTier.getOrComputeIfAbsent(CompoundCachingTier.java:98) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.internal.store.tiering.CacheStore.computeIfAbsent(CacheStore.java:263) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.Ehcache.get(Ehcache.java:191) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.terracotta.qa.ehcache.validation.ValidatingPutOperation.validate(ValidatingPutOperation.java:73) [test-classes/:na]
	at com.terracotta.qa.ehcache.validation.ValidatingPutOperation.exec(ValidatingPutOperation.java:56) [test-classes/:na]
	at io.rainfall.execution.RunsDuring$1.call(RunsDuring.java:79) [rainfall-core-1.1.3-SNAPSHOT.jar:na]
	at io.rainfall.execution.RunsDuring$1.call(RunsDuring.java:71) [rainfall-core-1.1.3-SNAPSHOT.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
Caused by: java.lang.AssertionError: null
	at org.ehcache.internal.store.offheap.AbstractOffHeapStore$18.apply(AbstractOffHeapStore.java:879) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.internal.store.offheap.AbstractOffHeapStore$18.apply(AbstractOffHeapStore.java:875) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.internal.store.offheap.factories.EhcacheSegmentFactory$EhcacheSegment.compute(EhcacheSegmentFactory.java:91) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.internal.store.offheap.EhcacheConcurrentOffHeapClockCache.compute(EhcacheConcurrentOffHeapClockCache.java:47) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.internal.store.offheap.AbstractOffHeapStore.installMapping(AbstractOffHeapStore.java:897) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.internal.store.tiering.CompoundCachingTier$1.onInvalidation(CompoundCachingTier.java:58) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.internal.store.heap.OnHeapStore$16.onInvalidation(OnHeapStore.java:756) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.internal.store.heap.OnHeapStore.notifyInvalidation(OnHeapStore.java:746) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.internal.store.heap.OnHeapStore.getOrComputeIfAbsent(OnHeapStore.java:647) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	... 11 common frames omitted
```

Here's one of the configs that uncovered this error:

Configuration: heap_offheap_disk
Variation: [Ordered Asynchronous Listener, Cache level copier variation: [Key copier: LongCopier ,Value copier: null], TTI Expiry, Cache level serializer variation: [Key serializer: LongSerializer ,Value serializer: CacheValueSerializer]]

**Comment by ljacomet** [comment]
The stack trace indicates that we again violate the invariant between two caching tiers.

I believe one culprit code is when inside `OnHeapStore#getOrComputeIfAbsent` we do invoke `OnHeapStore#notifyInvalidation` outside of exclusive access to the key.

**Comment by ljacomet** [comment]
Went back to issue #641 and indeed the exception matches the explanation over there. I missed that one more call site which was not under exclusive access.

Let's make suer another pair of eyes go over `OnHeapStore` so that none others are left this time ...
