### ISSUE TITLE
ResilienceStrategy getting OversizeMappingException: Storage Engine and Eviction Failed

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#727]
Pounding a 3-tiered cache sometimes result in this:

```
04:39:04.642 [Rainfall-core Operations Thread] INFO  o.e.r.LoggingRobustResilienceStrategy - Ehcache key 69531 recovered from
org.ehcache.exceptions.CacheAccessException: The element with key '69531' is too large to be stored in this offheap store.
	at org.ehcache.internal.store.offheap.AbstractOffHeapStore.handleOversizeMappingException(AbstractOffHeapStore.java:1010) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.internal.store.offheap.AbstractOffHeapStore.handleOversizeMappingException(AbstractOffHeapStore.java:991) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.internal.store.offheap.AbstractOffHeapStore.compute(AbstractOffHeapStore.java:470) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.internal.store.offheap.AbstractOffHeapStore.compute(AbstractOffHeapStore.java:418) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.internal.store.tiering.CacheStore.compute(CacheStore.java:246) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.Ehcache.put(Ehcache.java:247) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at com.terracotta.qa.ehcache.validation.ValidatingReplaceValueOperation.exec(ValidatingReplaceValueOperation.java:39) [test-classes/:na]
	at io.rainfall.execution.RunsDuring$1.call(RunsDuring.java:79) [rainfall-core-1.1.3-SNAPSHOT.jar:na]
	at io.rainfall.execution.RunsDuring$1.call(RunsDuring.java:71) [rainfall-core-1.1.3-SNAPSHOT.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_51]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]
Caused by: org.terracotta.offheapstore.exceptions.OversizeMappingException: Storage Engine and Eviction Failed.
Storage Engine : org.terracotta.offheapstore.disk.storage.FileBackedStorageEngine@7ea06be0
	at org.terracotta.offheapstore.AbstractOffHeapClockCache.storageEngineFailure(AbstractOffHeapClockCache.java:90) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.terracotta.offheapstore.OffHeapHashMap.writeEntry(OffHeapHashMap.java:684) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.terracotta.offheapstore.OffHeapHashMap.put(OffHeapHashMap.java:466) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.terracotta.offheapstore.AbstractLockedOffHeapHashMap.put(AbstractLockedOffHeapHashMap.java:142) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.internal.store.disk.factories.EhcachePersistentSegmentFactory$EhcachePersistentSegment.put(EhcachePersistentSegmentFactory.java:184) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.internal.store.disk.factories.EhcachePersistentSegmentFactory$EhcachePersistentSegment.compute(EhcachePersistentSegmentFactory.java:99) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.internal.store.disk.EhcachePersistentConcurrentOffHeapClockCache.compute(EhcachePersistentConcurrentOffHeapClockCache.java:52) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.ehcache.internal.store.offheap.AbstractOffHeapStore.compute(AbstractOffHeapStore.java:467) ~[ehcache-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	... 10 common frames omitted
```

**Comment by lorban** [comment]
Still actual.

**Comment by chrisdennis** [comment]
So I spent some time looking at this and there are three contributing factors here:

1. The test is 'close' to a tiering inversion.
2. The FileBackedStorageEngine has a pretty lousy shrink implementation (no ability to compress things that are not evictable (aka pinned things)).
3. The FileBackedStorageEngine allocates things in such a way that it's hard for it even have a 'good' shrink implementation (pages double in size as it grows so shrinking requires evicting 'half' of the things in a segment).

I think some discussion is required to understand how we should 'fix' this.

**Comment by chrisdennis** [comment]
I have filed Terracotta-OSS/offheap-store#30 for issue 2 and Terracotta-OSS/offheap-store#31 for issue 3 (in the above comment).
