### ISSUE TITLE
Problem ehcache 3 with WAS7

### ISSUE THREAD

**Issue by fabriciofconde** [ehcache/ehcache3#739]
Hi,

I have been with problem to use Ehcache 3 with WAS7 (Websphere Application Server 7).
I did simple application web, and run test some application servers different:
- Tomcat 7: works
- Jetty 8: works
- WAS7: Doesn't work

I did same test with other versions (3.0.0.m4, 3.0.0.m2 and 3.0.0.m1) into WAS7:
- 3.0.0.m4 doesn't work
- 3.0.0.m2 doesn't work
- 3.0.0.m1 works

**Follow the logs**
_[03/02/16 15:09:45:661 BRST] 00000011 SystemErr     R 	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.ready(HttpInboundLink.java:272)
[03/02/16 15:09:45:661 BRST] 00000011 SystemErr     R 	at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:214)
[03/02/16 15:09:45:662 BRST] 00000011 SystemErr     R 	at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:113)
[03/02/16 15:09:45:662 BRST] 00000011 SystemErr     R 	at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:165)
[03/02/16 15:09:45:662 BRST] 00000011 SystemErr     R 	at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
[03/02/16 15:09:45:662 BRST] 00000011 SystemErr     R 	at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
[03/02/16 15:09:45:662 BRST] 00000011 SystemErr     R 	at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
[03/02/16 15:09:45:663 BRST] 00000011 SystemErr     R 	at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:202)
[03/02/16 15:09:45:663 BRST] 00000011 SystemErr     R 	at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:766)
[03/02/16 15:09:45:663 BRST] 00000011 SystemErr     R 	at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:896)
[03/02/16 15:09:45:663 BRST] 00000011 SystemErr     R 	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1527)
[03/02/16 15:09:45:663 BRST] 00000011 SystemErr     R Caused by: java.lang.IllegalStateException: Cache 'cache' creation in EhcacheManager failed.
[03/02/16 15:09:45:664 BRST] 00000011 SystemErr     R 	at org.ehcache.EhcacheManager.createCache(EhcacheManager.java:213)
[03/02/16 15:09:45:664 BRST] 00000011 SystemErr     R 	at org.ehcache.EhcacheManager.init(EhcacheManager.java:427)
[03/02/16 15:09:45:664 BRST] 00000011 SystemErr     R 	... 32 more
[03/02/16 15:09:45:664 BRST] 00000011 SystemErr     R Caused by: org.ehcache.exceptions.StateTransitionException: Given store is not managed by this provider : org.ehcache.internal.store.heap.OnHeapStore@7ac97ac9
[03/02/16 15:09:45:665 BRST] 00000011 SystemErr     R 	at org.ehcache.StatusTransitioner$Transition.succeeded(StatusTransitioner.java:206)
[03/02/16 15:09:45:665 BRST] 00000011 SystemErr     R 	at org.ehcache.Ehcache.init(Ehcache.java:1030)
[03/02/16 15:09:45:665 BRST] 00000011 SystemErr     R 	at org.ehcache.EhcacheManager.createCache(EhcacheManager.java:195)
[03/02/16 15:09:45:666 BRST] 00000011 SystemErr     R 	... 33 more
[03/02/16 15:09:45:666 BRST] 00000011 SystemErr     R Caused by: java.lang.IllegalArgumentException: Given store is not managed by this provider : org.ehcache.internal.store.heap.OnHeapStore@7ac97ac9
[03/02/16 15:09:45:666 BRST] 00000011 SystemErr     R 	at org.ehcache.internal.store.heap.OnHeapStore$Provider.initStore(OnHeapStore.java:1056)
[03/02/16 15:09:45:666 BRST] 00000011 SystemErr     R 	at org.ehcache.internal.store.DefaultStoreProvider.initStore(DefaultStoreProvider.java:109)
[03/02/16 15:09:45:666 BRST] 00000011 SystemErr     R 	at org.ehcache.EhcacheManager$1.init(EhcacheManager.java:253)
[03/02/16 15:09:45:667 BRST] 00000011 SystemErr     R 	at org.ehcache.StatusTransitioner.runInitHooks(StatusTransitioner.java:134)
[03/02/16 15:09:45:667 BRST] 00000011 SystemErr     R 	at org.ehcache.StatusTransitioner.access$000(StatusTransitioner.java:32)
[03/02/16 15:09:45:667 BRST] 00000011 SystemErr     R 	at org.ehcache.StatusTransitioner$Transition.succeeded(StatusTransitioner.java:193)
[03/02/16 15:09:45:667 BRST] 00000011 SystemErr     R 	... 35 more_

Sample code
```
CacheManager cacheManager = CacheManagerBuilder
	.newCacheManagerBuilder() 
	.withCache(
		"cache", CacheConfigurationBuilder
			.newCacheConfigurationBuilder()
				.withResourcePools(
					ResourcePoolsBuilder
						.newResourcePoolsBuilder()
						.heap(2, EntryUnit.ENTRIES)
						.offheap(1, MemoryUnit.MB)
						.build()
				)
				.buildConfig(String.class, String.class)
	) 
	.build(false); 

cacheManager.init();
```
I think that found a bug. Someone could help me?

Thank you.

**Comment by ljacomet** [comment]
Thanks for your feedback.

As asked on the mailing list:
> As we are getting close to releasing milestone 5, could you try with the latest SNAPSHOT?
> You can get it from Sonatype snapshot repo - https://oss.sonatype.org/content/repositories/snapshots
>
> Interested to see first if the problem still occurs in the latest version.

**Comment by fabriciofconde** [comment]
Updated...
The problem happens only using JAVA IBM 6 (embedded in files WAS7).

I did the same test with WAS8.5 (Websphere 8.5) with JAVA IBM SDK 6 and 7: 
- WAS8.5 IBM SDK 6: Doesn't work
- WAS8.5 IBM SDK 7: Works

Then
I did the same test with tomcat using SDK IBM:
- Tomcat IBM SDK 6: Doesn't work
- Tomcat IBM SDK 7: Works

I think the problem is some incompatibily between JAVA IBM SDK 6 and ehcache3.

**Comment by ljacomet** [comment]
With which version were these additional tests performed?
Did you try with the latest SNAPSHOT?

**Comment by fabriciofconde** [comment]
Yes, I did.

I did additional tests with versions ehcache-3.0.0-20160203.125949-245.jar and 3.0.0.m4.jar, and both didn't work.

**Comment by ljacomet** [comment]
I confirm I can reproduce this issue. Will be looking into a fix.

**Comment by lorban** [comment]
The root cause of the problem is our implementation of `ConcurrentWeakIdentityHashMap.keySet()`: we return a set containing a snapshot of the existing keys while the contract says *changes to the map are reflected in the set, and vice-versa*.

It is the `Collections.newSetFromMap()` (used in `OnHeapStore.Provider` and other places) implementation of the IBM JDK 1.6 that relies on this contract that makes everything fail. It's just plain luck that other JDKs don't fail.

Our `ConcurrentWeakIdentityHashMap.entrySet()` imlementation is broken too for similar reasons.
