### ISSUE TITLE
BulkCacheWritingException under load

### ISSUE THREAD

**Issue by lorban** [ehcache/ehcache3#870]
Here's the cache config:
```
Configuration: heap_offheap_disk
Variation: [Cache level serializer variation: [Key serializer: null ,Value serializer: CacheValueSerializer], Eviction Veto Custom, Unordered Synchronous Listener, Cache level copier variation: [Key copier: LongCopier ,Value copier: CacheValueCopier]]
```
and the exception that I sometimes catch:

```
ERROR c.t.q.e.v.ValidatingPutAllOperation - Operation caught exception
org.ehcache.exceptions.BulkCacheWritingException: null
    at org.ehcache.core.EhcacheWithLoaderWriter.putAll(EhcacheWithLoaderWriter.java:566)
    at com.terracotta.qa.ehcache.validation.ValidatingPutAllOperation.exec(ValidatingPutAllOperation.java:67)
    ...
```

While the `BulkCacheWritingException` does contain the cause(s) of the problem, those are not reported in `toString()` nor in `printStackTrace()` which makes for a pretty poor readability of that exception.

**Comment by lorban** [comment]
Here is the sole nested exception of the `BulkCacheWritingException`:

```
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1124)
	at com.terracotta.qa.ehcache.configuration.CollectingCacheLoaderWriter.writeAll(CollectingCacheLoaderWriter.java:60)
	at org.ehcache.core.EhcacheWithLoaderWriter.cacheLoaderWriterWriteAllCall(EhcacheWithLoaderWriter.java:614)
	at org.ehcache.core.EhcacheWithLoaderWriter.access$400(EhcacheWithLoaderWriter.java:89)
	at org.ehcache.core.EhcacheWithLoaderWriter$6.apply(EhcacheWithLoaderWriter.java:535)
	at org.ehcache.core.EhcacheWithLoaderWriter$6.apply(EhcacheWithLoaderWriter.java:531)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore$23.apply(AbstractOffHeapStore.java:831)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore$21.apply(AbstractOffHeapStore.java:636)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore$21.apply(AbstractOffHeapStore.java:623)
	at org.ehcache.impl.internal.store.disk.EhcachePersistentConcurrentOffHeapClockCache$1.apply(EhcachePersistentConcurrentOffHeapClockCache.java:162)
	at org.ehcache.impl.internal.store.disk.EhcachePersistentConcurrentOffHeapClockCache$1.apply(EhcachePersistentConcurrentOffHeapClockCache.java:158)
	at org.terracotta.offheapstore.OffHeapHashMap.computeWithMetadata(OffHeapHashMap.java:1889)
	at org.terracotta.offheapstore.AbstractLockedOffHeapHashMap.computeWithMetadata(AbstractLockedOffHeapHashMap.java:581)
	at org.terracotta.offheapstore.OffHeapHashMap.computeWithMetadata(OffHeapHashMap.java:1928)
	at org.terracotta.offheapstore.AbstractLockedOffHeapHashMap.computeWithMetadata(AbstractLockedOffHeapHashMap.java:581)
	at org.terracotta.offheapstore.concurrent.AbstractConcurrentOffHeapMap.computeWithMetadata(AbstractConcurrentOffHeapMap.java:728)
	at org.ehcache.impl.internal.store.disk.EhcachePersistentConcurrentOffHeapClockCache.compute(EhcachePersistentConcurrentOffHeapClockCache.java:158)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.compute(AbstractOffHeapStore.java:674)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.bulkCompute(AbstractOffHeapStore.java:842)
	at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.bulkCompute(AbstractOffHeapStore.java:804)
	at org.ehcache.impl.internal.store.tiering.CacheStore.bulkCompute(CacheStore.java:289)
	at org.ehcache.core.EhcacheWithLoaderWriter.putAll(EhcacheWithLoaderWriter.java:562)
	at com.terracotta.qa.ehcache.validation.ValidatingPutAllOperation.exec(ValidatingPutAllOperation.java:70)
	at io.rainfall.execution.RunsDuring$1.call(RunsDuring.java:79)
	at io.rainfall.execution.RunsDuring$1.call(RunsDuring.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)	
```

`ConcurrentHashMap.java:1124` is throwing NPE after a null check on the value.

A short investigation of the code seems to indicate that the `Store.bulkCompute()` implementation slightly changed recently and that either the `putAll` compute function cannot cope with a legal `null` value because it never happened in the previous impl, or that `null` value is illegal and the offheap store's `bulkCompute()` implementation is buggy.

To be continued...

**Comment by lorban** [comment]
The root cause of this problem is that the recent `compute` method implementation rework in the OffHeapStore (and DiskStore) can call the compute method multiple times for the same key, while the `Store.bulkCompute()` contract explicitly states this is forbidden.

Based on the documented contract, `EhcacheWithLoaderWriter.putAll()` passes a stateful function to `Store.bulkCompute()` that expects that the function will never be called twice for the same key.

Knowing that preventing the OffHeapStore to call the function many times for a single key would at best seriously complicate its implementation, looking at what we currently do with `Store.bulkCompute` methods, and looking at the state of the latter methods I would recommend that we just plain gut them out of the `Store` API and replace their implementations with a simple loop in the `Ehcache` class instead.

Note that other `OffHeapStore.compute` calls should be safe as the function we pass always is (or should be?) memoized.
