### ISSUE TITLE
Put operation is bottlenecking while calculating size of KeyValuePair 

### ISSUE THREAD

**Issue by skbansal** [ehcache/ehcache3#906]
We have experienced bottleneck in put operation of Ehcache3.0. Its mainly around sizeof code flow. Due to this, Ehcache is not able to scale with increase in put() thread count.

Couple of threads dumps are uploaded.

Here are some snippets from thread dumps:
1. "Rainfall-core Operations Thread" prio=10 tid=0x00007f3b8800d800 nid=0x47b runnable [0x00007f3bcc511000]
   java.lang.Thread.State: RUNNABLE
   at java.lang.System.identityHashCode(Native Method)
   at java.util.IdentityHashMap.hash(IdentityHashMap.java:301)
   at java.util.IdentityHashMap.containsKey(IdentityHashMap.java:358)
   at org.ehcache.sizeof.ObjectGraphWalker.walk(ObjectGraphWalker.java:165)
   at org.ehcache.sizeof.SizeOf.deepSizeOf(SizeOf.java:71)
   at org.ehcache.impl.internal.sizeof.DefaultSizeOfEngine.sizeof(DefaultSizeOfEngine.java:53)
   at org.ehcache.impl.internal.store.heap.OnHeapStore.getSizeOfKeyValuePairs(OnHeapStore.java:913)

2."Rainfall-core Operations Thread" prio=10 tid=0x00007f3b8805d000 nid=0x479 runnable [0x00007f3bcca16000]
   java.lang.Thread.State: RUNNABLE
    at sun.instrument.InstrumentationImpl.getObjectSize0(Native Method)
    at sun.instrument.InstrumentationImpl.getObjectSize(InstrumentationImpl.java:188)
    at org.ehcache.sizeof.impl.AgentLoader.agentSizeOf(AgentLoader.java:229)
    at org.ehcache.sizeof.impl.AgentSizeOf.sizeOf(AgentSizeOf.java:85)
    at org.ehcache.sizeof.SizeOf$CachingSizeOfVisitor.visit(SizeOf.java:126)
    at org.ehcache.sizeof.ObjectGraphWalker.walk(ObjectGraphWalker.java:185)
    at org.ehcache.sizeof.SizeOf.deepSizeOf(SizeOf.java:71)
    at org.ehcache.impl.internal.sizeof.DefaultSizeOfEngine.sizeof(DefaultSizeOfEngine.java:53)
    at org.ehcache.impl.internal.store.heap.OnHeapStore.getSizeOfKeyValuePairs(OnHeapStore.java:913)
[Ehcache3.0-rc1-threadDump1.txt](https://github.com/ehcache/ehcache3/files/191092/Ehcache3.0-rc1-threadDump1.txt)
[Ehcache3.0-rc1-threadDump2.txt](https://github.com/ehcache/ehcache3/files/191093/Ehcache3.0-rc1-threadDump2.txt)

**Comment by chrisdennis** [comment]
Size-of is being deprecated (essentially) - this can go with it.
